import { describe, expect, test } from "vitest";
import { SqlTable } from "#/core/schema/sql-table.js";
import { SqlTableColumn } from "#/core/schema/sql-table-column.js";
import { Account } from "@test-models/vexnor_dev.account-table.js";
import { Sql } from "#/core/sql-base.js";

describe("SqlTable tests", () => {
   test("SqlTable inherits SqlBase", () => {
      expect(Account).instanceof(SqlTable);
      expect(Account).instanceof(Sql);
   });

   test("SqlTable should include expected columns", () => {
      expect(Account.$accountId).instanceof(SqlTableColumn);
      expect(Account.$status).instanceof(SqlTableColumn);
      expect(Account.$email).instanceof(SqlTableColumn);
   });

   test("Account table", () => {
      expect(Account).toMatchInlineSnapshot(`
        SqlTable {
          "$accountId": SqlTableColumn {
            "columnName": "account_id",
            "format": null,
            "id": "SqlTableColumn#1(account.account_id as accountId)",
            "key": "accountId",
            "tableInfo": {
              "alias": null,
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$createdAt": SqlTableColumn {
            "columnName": "created_at",
            "format": null,
            "id": "SqlTableColumn#7(account.created_at as createdAt)",
            "key": "createdAt",
            "tableInfo": {
              "alias": null,
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$email": SqlTableColumn {
            "columnName": "email",
            "format": null,
            "id": "SqlTableColumn#3(account.email)",
            "key": "email",
            "tableInfo": {
              "alias": null,
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$firstName": SqlTableColumn {
            "columnName": "first_name",
            "format": null,
            "id": "SqlTableColumn#4(account.first_name as firstName)",
            "key": "firstName",
            "tableInfo": {
              "alias": null,
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$lastName": SqlTableColumn {
            "columnName": "last_name",
            "format": null,
            "id": "SqlTableColumn#5(account.last_name as lastName)",
            "key": "lastName",
            "tableInfo": {
              "alias": null,
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$modifiedAt": SqlTableColumn {
            "columnName": "modified_at",
            "format": null,
            "id": "SqlTableColumn#8(account.modified_at as modifiedAt)",
            "key": "modifiedAt",
            "tableInfo": {
              "alias": null,
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$notes": SqlTableColumn {
            "columnName": "notes",
            "format": null,
            "id": "SqlTableColumn#6(account.notes)",
            "key": "notes",
            "tableInfo": {
              "alias": null,
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$parentId": SqlTableColumn {
            "columnName": "parent_id",
            "format": null,
            "id": "SqlTableColumn#9(account.parent_id as parentId)",
            "key": "parentId",
            "tableInfo": {
              "alias": null,
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$status": SqlTableColumn {
            "columnName": "status",
            "format": null,
            "id": "SqlTableColumn#2(account.status)",
            "key": "status",
            "tableInfo": {
              "alias": null,
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "_$$": Lazy {
            "_computed": false,
            "_value": null,
            "callback": [Function],
          },
          "_cols": Lazy {
            "_computed": true,
            "_value": {
              "$accountId": SqlTableColumn {
                "columnName": "account_id",
                "format": null,
                "id": "SqlTableColumn#1(account.account_id as accountId)",
                "key": "accountId",
                "tableInfo": {
                  "alias": null,
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$createdAt": SqlTableColumn {
                "columnName": "created_at",
                "format": null,
                "id": "SqlTableColumn#7(account.created_at as createdAt)",
                "key": "createdAt",
                "tableInfo": {
                  "alias": null,
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$email": SqlTableColumn {
                "columnName": "email",
                "format": null,
                "id": "SqlTableColumn#3(account.email)",
                "key": "email",
                "tableInfo": {
                  "alias": null,
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$firstName": SqlTableColumn {
                "columnName": "first_name",
                "format": null,
                "id": "SqlTableColumn#4(account.first_name as firstName)",
                "key": "firstName",
                "tableInfo": {
                  "alias": null,
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$lastName": SqlTableColumn {
                "columnName": "last_name",
                "format": null,
                "id": "SqlTableColumn#5(account.last_name as lastName)",
                "key": "lastName",
                "tableInfo": {
                  "alias": null,
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$modifiedAt": SqlTableColumn {
                "columnName": "modified_at",
                "format": null,
                "id": "SqlTableColumn#8(account.modified_at as modifiedAt)",
                "key": "modifiedAt",
                "tableInfo": {
                  "alias": null,
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$notes": SqlTableColumn {
                "columnName": "notes",
                "format": null,
                "id": "SqlTableColumn#6(account.notes)",
                "key": "notes",
                "tableInfo": {
                  "alias": null,
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$parentId": SqlTableColumn {
                "columnName": "parent_id",
                "format": null,
                "id": "SqlTableColumn#9(account.parent_id as parentId)",
                "key": "parentId",
                "tableInfo": {
                  "alias": null,
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$status": SqlTableColumn {
                "columnName": "status",
                "format": null,
                "id": "SqlTableColumn#2(account.status)",
                "key": "status",
                "tableInfo": {
                  "alias": null,
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
            },
            "callback": [Function],
          },
          "_crudConfig": {
            "delete": true,
            "insert": true,
            "select": true,
            "update": true,
          },
          "_out": Lazy {
            "_computed": false,
            "_value": null,
            "callback": [Function],
          },
          "dialect": "sql",
          "format": null,
          "id": "SqlTable#1(main.account)",
          "pk": [
            "accountId",
          ],
          "tableInfo": {
            "alias": null,
            "name": "account",
            "out": false,
            "schema": "main",
          },
          "tag": null,
          "type": "SqlTable",
        }
      `);
   });

   test("SqlTable alias should return new SqlTable instance", () => {
      expect(Account.as`parent`).toMatchInlineSnapshot(`
        SqlTable {
          "$accountId": SqlTableColumn {
            "columnName": "account_id",
            "format": null,
            "id": "SqlTableColumn#1(parent.account_id as accountId)",
            "key": "accountId",
            "tableInfo": {
              "alias": "parent",
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$createdAt": SqlTableColumn {
            "columnName": "created_at",
            "format": null,
            "id": "SqlTableColumn#7(parent.created_at as createdAt)",
            "key": "createdAt",
            "tableInfo": {
              "alias": "parent",
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$email": SqlTableColumn {
            "columnName": "email",
            "format": null,
            "id": "SqlTableColumn#3(parent.email)",
            "key": "email",
            "tableInfo": {
              "alias": "parent",
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$firstName": SqlTableColumn {
            "columnName": "first_name",
            "format": null,
            "id": "SqlTableColumn#4(parent.first_name as firstName)",
            "key": "firstName",
            "tableInfo": {
              "alias": "parent",
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$lastName": SqlTableColumn {
            "columnName": "last_name",
            "format": null,
            "id": "SqlTableColumn#5(parent.last_name as lastName)",
            "key": "lastName",
            "tableInfo": {
              "alias": "parent",
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$modifiedAt": SqlTableColumn {
            "columnName": "modified_at",
            "format": null,
            "id": "SqlTableColumn#8(parent.modified_at as modifiedAt)",
            "key": "modifiedAt",
            "tableInfo": {
              "alias": "parent",
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$notes": SqlTableColumn {
            "columnName": "notes",
            "format": null,
            "id": "SqlTableColumn#6(parent.notes)",
            "key": "notes",
            "tableInfo": {
              "alias": "parent",
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$parentId": SqlTableColumn {
            "columnName": "parent_id",
            "format": null,
            "id": "SqlTableColumn#9(parent.parent_id as parentId)",
            "key": "parentId",
            "tableInfo": {
              "alias": "parent",
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "$status": SqlTableColumn {
            "columnName": "status",
            "format": null,
            "id": "SqlTableColumn#2(parent.status)",
            "key": "status",
            "tableInfo": {
              "alias": "parent",
              "name": "account",
              "out": false,
              "schema": "main",
            },
            "tag": null,
            "type": "SqlTableColumn",
          },
          "_$$": Lazy {
            "_computed": false,
            "_value": null,
            "callback": [Function],
          },
          "_cols": Lazy {
            "_computed": true,
            "_value": {
              "$accountId": SqlTableColumn {
                "columnName": "account_id",
                "format": null,
                "id": "SqlTableColumn#1(parent.account_id as accountId)",
                "key": "accountId",
                "tableInfo": {
                  "alias": "parent",
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$createdAt": SqlTableColumn {
                "columnName": "created_at",
                "format": null,
                "id": "SqlTableColumn#7(parent.created_at as createdAt)",
                "key": "createdAt",
                "tableInfo": {
                  "alias": "parent",
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$email": SqlTableColumn {
                "columnName": "email",
                "format": null,
                "id": "SqlTableColumn#3(parent.email)",
                "key": "email",
                "tableInfo": {
                  "alias": "parent",
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$firstName": SqlTableColumn {
                "columnName": "first_name",
                "format": null,
                "id": "SqlTableColumn#4(parent.first_name as firstName)",
                "key": "firstName",
                "tableInfo": {
                  "alias": "parent",
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$lastName": SqlTableColumn {
                "columnName": "last_name",
                "format": null,
                "id": "SqlTableColumn#5(parent.last_name as lastName)",
                "key": "lastName",
                "tableInfo": {
                  "alias": "parent",
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$modifiedAt": SqlTableColumn {
                "columnName": "modified_at",
                "format": null,
                "id": "SqlTableColumn#8(parent.modified_at as modifiedAt)",
                "key": "modifiedAt",
                "tableInfo": {
                  "alias": "parent",
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$notes": SqlTableColumn {
                "columnName": "notes",
                "format": null,
                "id": "SqlTableColumn#6(parent.notes)",
                "key": "notes",
                "tableInfo": {
                  "alias": "parent",
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$parentId": SqlTableColumn {
                "columnName": "parent_id",
                "format": null,
                "id": "SqlTableColumn#9(parent.parent_id as parentId)",
                "key": "parentId",
                "tableInfo": {
                  "alias": "parent",
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
              "$status": SqlTableColumn {
                "columnName": "status",
                "format": null,
                "id": "SqlTableColumn#2(parent.status)",
                "key": "status",
                "tableInfo": {
                  "alias": "parent",
                  "name": "account",
                  "out": false,
                  "schema": "main",
                },
                "tag": null,
                "type": "SqlTableColumn",
              },
            },
            "callback": [Function],
          },
          "_crudConfig": {
            "delete": true,
            "insert": true,
            "select": true,
            "update": true,
          },
          "_out": Lazy {
            "_computed": false,
            "_value": null,
            "callback": [Function],
          },
          "dialect": "sql",
          "format": null,
          "id": "SqlTable#1(main.account as parent)",
          "pk": [
            "accountId",
          ],
          "tableInfo": {
            "alias": "parent",
            "name": "account",
            "out": false,
            "schema": "main",
          },
          "tag": null,
          "type": "SqlTable",
        }
      `);
   });

   test("SqlTable alias should return new SqlColumn instance", () => {
      expect(Account.as`parent`.$accountId).toMatchInlineSnapshot(`
        SqlTableColumn {
          "columnName": "account_id",
          "format": null,
          "id": "SqlTableColumn#1(parent.account_id as accountId)",
          "key": "accountId",
          "tableInfo": {
            "alias": "parent",
            "name": "account",
            "out": false,
            "schema": "main",
          },
          "tag": null,
          "type": "SqlTableColumn",
        }
      `);
   });

   test("SqlTable alias should return new SqlTable instance with respective $$ columns", () => {
      expect(Account.as`inserted`.$$).toMatchInlineSnapshot(`
        SqlTableAll {
          "id": "SqlTableAll#1($accountId, $status, $email, $firstName, $lastName, $notes, $createdAt, $modifiedAt, $parentId)",
          "row": {
            "$accountId": SqlTableColumn {
              "columnName": "account_id",
              "format": null,
              "id": "SqlTableColumn#1(inserted.account_id as accountId)",
              "key": "accountId",
              "tableInfo": {
                "alias": "inserted",
                "name": "account",
                "out": false,
                "schema": "main",
              },
              "tag": null,
              "type": "SqlTableColumn",
            },
            "$createdAt": SqlTableColumn {
              "columnName": "created_at",
              "format": null,
              "id": "SqlTableColumn#7(inserted.created_at as createdAt)",
              "key": "createdAt",
              "tableInfo": {
                "alias": "inserted",
                "name": "account",
                "out": false,
                "schema": "main",
              },
              "tag": null,
              "type": "SqlTableColumn",
            },
            "$email": SqlTableColumn {
              "columnName": "email",
              "format": null,
              "id": "SqlTableColumn#3(inserted.email)",
              "key": "email",
              "tableInfo": {
                "alias": "inserted",
                "name": "account",
                "out": false,
                "schema": "main",
              },
              "tag": null,
              "type": "SqlTableColumn",
            },
            "$firstName": SqlTableColumn {
              "columnName": "first_name",
              "format": null,
              "id": "SqlTableColumn#4(inserted.first_name as firstName)",
              "key": "firstName",
              "tableInfo": {
                "alias": "inserted",
                "name": "account",
                "out": false,
                "schema": "main",
              },
              "tag": null,
              "type": "SqlTableColumn",
            },
            "$lastName": SqlTableColumn {
              "columnName": "last_name",
              "format": null,
              "id": "SqlTableColumn#5(inserted.last_name as lastName)",
              "key": "lastName",
              "tableInfo": {
                "alias": "inserted",
                "name": "account",
                "out": false,
                "schema": "main",
              },
              "tag": null,
              "type": "SqlTableColumn",
            },
            "$modifiedAt": SqlTableColumn {
              "columnName": "modified_at",
              "format": null,
              "id": "SqlTableColumn#8(inserted.modified_at as modifiedAt)",
              "key": "modifiedAt",
              "tableInfo": {
                "alias": "inserted",
                "name": "account",
                "out": false,
                "schema": "main",
              },
              "tag": null,
              "type": "SqlTableColumn",
            },
            "$notes": SqlTableColumn {
              "columnName": "notes",
              "format": null,
              "id": "SqlTableColumn#6(inserted.notes)",
              "key": "notes",
              "tableInfo": {
                "alias": "inserted",
                "name": "account",
                "out": false,
                "schema": "main",
              },
              "tag": null,
              "type": "SqlTableColumn",
            },
            "$parentId": SqlTableColumn {
              "columnName": "parent_id",
              "format": null,
              "id": "SqlTableColumn#9(inserted.parent_id as parentId)",
              "key": "parentId",
              "tableInfo": {
                "alias": "inserted",
                "name": "account",
                "out": false,
                "schema": "main",
              },
              "tag": null,
              "type": "SqlTableColumn",
            },
            "$status": SqlTableColumn {
              "columnName": "status",
              "format": null,
              "id": "SqlTableColumn#2(inserted.status)",
              "key": "status",
              "tableInfo": {
                "alias": "inserted",
                "name": "account",
                "out": false,
                "schema": "main",
              },
              "tag": null,
              "type": "SqlTableColumn",
            },
          },
          "tag": null,
          "type": "SqlTableAll",
        }
      `);
   });
});
