import { getCodegenContext } from "../../codegen-context.js";
import { writeTableType } from "./write-table-type.js";
import { writeTableInsert } from "../write-table-insert.js";
import { writeTableSelect } from "../write-table-select.js";
import { PrintTableArgs } from "../../types/index.js";

export function writeTable({ table }: PrintTableArgs): string {
   const writer = getCodegenContext().newWriter();
   const { includeEnums } = getCodegenContext();
   const { table_schema } = table;
   writer.writeLine(`// File generated by Valnor. Do not edit.`);
   writer.writeLine(`import postgres from "postgres";`);
   writer.writeLine(`import * as lib from "./postgres-library.js";`);
   if (includeEnums) {
      // writer.writeLine(`// eslint-disable-next-line @typescript-eslint/no-unused-vars`);
      writer.writeLine(`import * as udt from "./${table_schema}-enums.js";`);
   }

   writer.blankLine();

   writeTableType(writer, { table });
   writeTableInsert(writer, { table });
   writeTableSelect(writer, { table });
   return writer.toString();
}
