/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";
import * as udt from "./vexnor_dev-enums.js";

export const Order = vexnor.newSqlTable<{
   Select: IOrderSelect;
   Insert: IOrderInsert;
   Update: IOrderUpdate;
   Delete: true;
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "order",
      schema: "vexnor_dev",
   },
   pk: ["orderId"],
   dialect: "postgresql",
   source: "@vexnor/example-postgres-cjs:src/codegen",
   columns: {

      /**
       * order_id uuid default gen_random_uuid()
       */
      orderId: "order_id",

      /**
       * status order_status default 'created'::vexnor_dev.order_status
       */
      status: "status",

      /**
       * created_at timestamptz default now()
       */
      createdAt: "created_at",

      /**
       * modified_at timestamptz default now()
       */
      modifiedAt: "modified_at",

      /**
       * account_id uuid
       */
      accountId: "account_id",
   },
   jsonSchema: {
      createdAt: "Date",
      modifiedAt: "Date",
   },
   fk: [
      { from: ["accountId"], to: { schema: "vexnor_dev", table: "account", columns: ["accountId"] } },
   ],
   dbSchema: {
      orderId: { dbType: "uuid", type: vexnor.SqlLiteralType.String, default: "gen_random_uuid()" },
      status: { dbType: "order_status", type: vexnor.SqlLiteralType.Udt, default: "'created'::vexnor_dev.order_status", values: ["created", "paid", "delivered", "received"] },
      createdAt: { dbType: "timestamptz", type: vexnor.SqlLiteralType.Date, default: "now()" },
      modifiedAt: { dbType: "timestamptz", type: vexnor.SqlLiteralType.Date, default: "now()" },
      accountId: { dbType: "uuid", type: vexnor.SqlLiteralType.String },
   },
});
export type IOrderInsert = {
   orderId?: string;
   status?: udt.OrderStatusUdt;
   createdAt?: Date;
   modifiedAt?: Date;
   accountId: string;
};

export type IOrderUpdate = Partial<IOrderInsert>;

export type IOrderSelect = {
   orderId: string;
   status: udt.OrderStatusUdt;
   createdAt: Date;
   modifiedAt: Date;
   accountId: string;
};

export type IOrderJson = vexnor.JsonRow<IOrderSelect>;