/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";
import * as udt from "./vexnor_dev-enums.js";

export const AccountOrderSummary = vexnor.newSqlTable<{
   Select: IAccountOrderSummarySelect;
}>( {
   crud: {
      select: true,
      insert: false,
      update: false,
      delete: false,
   },
   tableInfo: {
      name: "account_order_summary",
      schema: "vexnor_dev",
   },
   pk: [],
   dialect: "postgresql",
   source: "@vexnor/example-postgres-cjs:src/codegen",
   columns: {

      /**
       * account_id uuid
       */
      accountId: "account_id",

      /**
       * email varchar
       */
      email: "email",

      /**
       * first_name varchar
       */
      firstName: "first_name",

      /**
       * last_name varchar
       */
      lastName: "last_name",

      /**
       * status account_status
       */
      status: "status",

      /**
       * order_count int8
       */
      orderCount: "order_count",

      /**
       * latest_order_at timestamptz
       */
      latestOrderAt: "latest_order_at",
   },
   jsonSchema: {
      latestOrderAt: "Date",
   },
   dbSchema: {
      accountId: { dbType: "uuid", type: vexnor.SqlLiteralType.String, nullable: true },
      email: { dbType: "varchar", type: vexnor.SqlLiteralType.String, nullable: true },
      firstName: { dbType: "varchar", type: vexnor.SqlLiteralType.String, nullable: true },
      lastName: { dbType: "varchar", type: vexnor.SqlLiteralType.String, nullable: true },
      status: { dbType: "account_status", type: vexnor.SqlLiteralType.Udt, nullable: true, values: ["created", "confirmed", "deleted"] },
      orderCount: { dbType: "int8", type: vexnor.SqlLiteralType.String, nullable: true },
      latestOrderAt: { dbType: "timestamptz", type: vexnor.SqlLiteralType.Date, nullable: true },
   },
});
export type IAccountOrderSummarySelect = {
   accountId: string | null;
   email: string | null;
   firstName: string | null;
   lastName: string | null;
   status: udt.AccountStatusUdt | null;
   orderCount: string | null;
   latestOrderAt: Date | null;
};

export type IAccountOrderSummaryJson = vexnor.JsonRow<IAccountOrderSummarySelect>;