packages:
  - packages/**
  - examples/**
  - tests/**
  - '!**/dist/**'
  - '!**/build/**'
  - '!**/deploy/**'

allowBuilds:
  '@prisma/engines': true
  better-sqlite3: true
  esbuild: true
  prisma: true
  sqlite3: true

ignoredBuiltDependencies:
  - esbuild

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
