// Package mongodb provides a vexnor MongoDB executor for Go.
// It reads MongoDB query manifests (generated by @vexnor/mongodb) and
// executes them against a MongoDB database using the official Go driver.
package mongodb

import (
	"context"
	"encoding/json"
	"fmt"
	"os"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// Executor implements MongoDB query execution from manifest descriptors.
type Executor struct {
	db *mongo.Database
}

// New creates a new MongoDB Executor from an existing *mongo.Database.
func New(db *mongo.Database) *Executor {
	return &Executor{db: db}
}

// NewFromURI creates a new MongoDB Executor by connecting to the given URI and database name.
func NewFromURI(ctx context.Context, uri string, dbName string) (*Executor, error) {
	client, err := mongo.Connect(options.Client().ApplyURI(uri))
	if err != nil {
		return nil, fmt.Errorf("mongodb: failed to connect: %w", err)
	}

	// Verify connection
	if err := client.Ping(ctx, nil); err != nil {
		return nil, fmt.Errorf("mongodb: ping failed: %w", err)
	}

	return &Executor{db: client.Database(dbName)}, nil
}

// Close disconnects the underlying client.
func (e *Executor) Close(ctx context.Context) error {
	return e.db.Client().Disconnect(ctx)
}

// QueryRows executes a MongoDB query from a manifest descriptor and returns results as maps.
func (e *Executor) QueryRows(ctx context.Context, descriptor map[string]any, params map[string]any) ([]map[string]any, error) {
	collName, ok := descriptor["collection"].(string)
	if !ok {
		return nil, fmt.Errorf("mongodb: missing 'collection' in descriptor")
	}

	operation, ok := descriptor["operation"].(string)
	if !ok {
		return nil, fmt.Errorf("mongodb: missing 'operation' in descriptor")
	}

	// Substitute params in the descriptor
	resolved := substituteParams(descriptor, params).(map[string]any)

	coll := e.db.Collection(collName)

	switch operation {
	case "find":
		return e.executeFindQuery(ctx, coll, resolved)
	case "aggregate":
		return e.executeAggregateQuery(ctx, coll, resolved)
	case "deleteOne":
		return e.executeDeleteOne(ctx, coll, resolved)
	case "deleteMany":
		return e.executeDeleteMany(ctx, coll, resolved)
	case "insertOne":
		return e.executeInsertOne(ctx, coll, resolved)
	case "insertMany":
		return e.executeInsertMany(ctx, coll, resolved)
	case "updateOne":
		return e.executeUpdateOne(ctx, coll, resolved)
	case "updateMany":
		return e.executeUpdateMany(ctx, coll, resolved)
	default:
		return nil, fmt.Errorf("mongodb: unsupported operation: %s", operation)
	}
}

func (e *Executor) executeFindQuery(ctx context.Context, coll *mongo.Collection, desc map[string]any) ([]map[string]any, error) {
	filter := toBsonDoc(desc["filter"])

	opts := options.Find()
	if sort, ok := desc["sort"]; ok && sort != nil {
		opts.SetSort(toBsonDoc(sort))
	}
	if limit, ok := desc["limit"]; ok && limit != nil {
		if l, ok := toInt64(limit); ok {
			opts.SetLimit(l)
		}
	}
	if skip, ok := desc["skip"]; ok && skip != nil {
		if s, ok := toInt64(skip); ok {
			opts.SetSkip(s)
		}
	}
	if projection, ok := desc["projection"]; ok && projection != nil {
		opts.SetProjection(toBsonDoc(projection))
	}

	cursor, err := coll.Find(ctx, filter, opts)
	if err != nil {
		return nil, fmt.Errorf("mongodb: find failed: %w", err)
	}
	defer cursor.Close(ctx)

	var results []map[string]any
	for cursor.Next(ctx) {
		var doc bson.M
		if err := cursor.Decode(&doc); err != nil {
			return nil, fmt.Errorf("mongodb: decode failed: %w", err)
		}
		results = append(results, normalizeDoc(doc))
	}
	if err := cursor.Err(); err != nil {
		return nil, fmt.Errorf("mongodb: cursor error: %w", err)
	}

	return results, nil
}

func (e *Executor) executeAggregateQuery(ctx context.Context, coll *mongo.Collection, desc map[string]any) ([]map[string]any, error) {
	pipelineRaw, ok := desc["pipeline"].([]any)
	if !ok {
		return nil, fmt.Errorf("mongodb: aggregate requires 'pipeline' array")
	}

	pipeline := make(bson.A, len(pipelineRaw))
	for i, stage := range pipelineRaw {
		pipeline[i] = toBsonDoc(stage)
	}

	cursor, err := coll.Aggregate(ctx, pipeline)
	if err != nil {
		return nil, fmt.Errorf("mongodb: aggregate failed: %w", err)
	}
	defer cursor.Close(ctx)

	var results []map[string]any
	for cursor.Next(ctx) {
		var doc bson.M
		if err := cursor.Decode(&doc); err != nil {
			return nil, fmt.Errorf("mongodb: decode failed: %w", err)
		}
		results = append(results, normalizeDoc(doc))
	}
	if err := cursor.Err(); err != nil {
		return nil, fmt.Errorf("mongodb: cursor error: %w", err)
	}

	return results, nil
}

func (e *Executor) executeDeleteOne(ctx context.Context, coll *mongo.Collection, desc map[string]any) ([]map[string]any, error) {
	filter := toBsonDoc(desc["filter"])
	result, err := coll.DeleteOne(ctx, filter)
	if err != nil {
		return nil, fmt.Errorf("mongodb: deleteOne failed: %w", err)
	}
	return []map[string]any{{"deletedCount": result.DeletedCount}}, nil
}

func (e *Executor) executeDeleteMany(ctx context.Context, coll *mongo.Collection, desc map[string]any) ([]map[string]any, error) {
	filter := toBsonDoc(desc["filter"])
	result, err := coll.DeleteMany(ctx, filter)
	if err != nil {
		return nil, fmt.Errorf("mongodb: deleteMany failed: %w", err)
	}
	return []map[string]any{{"deletedCount": result.DeletedCount}}, nil
}

func (e *Executor) executeInsertOne(ctx context.Context, coll *mongo.Collection, desc map[string]any) ([]map[string]any, error) {
	doc := toBsonDoc(desc["document"])
	_, err := coll.InsertOne(ctx, doc)
	if err != nil {
		return nil, fmt.Errorf("mongodb: insertOne failed: %w", err)
	}
	return []map[string]any{normalizeDoc(doc.(bson.D))}, nil
}

func (e *Executor) executeInsertMany(ctx context.Context, coll *mongo.Collection, desc map[string]any) ([]map[string]any, error) {
	docsRaw, ok := desc["documents"].([]any)
	if !ok {
		return nil, fmt.Errorf("mongodb: insertMany requires 'documents' array")
	}

	docs := make([]any, len(docsRaw))
	for i, d := range docsRaw {
		docs[i] = toBsonDoc(d)
	}

	_, err := coll.InsertMany(ctx, docs)
	if err != nil {
		return nil, fmt.Errorf("mongodb: insertMany failed: %w", err)
	}

	results := make([]map[string]any, len(docs))
	for i, d := range docs {
		if bsonDoc, ok := d.(bson.D); ok {
			results[i] = normalizeDoc(bsonDoc)
		}
	}
	return results, nil
}

func (e *Executor) executeUpdateOne(ctx context.Context, coll *mongo.Collection, desc map[string]any) ([]map[string]any, error) {
	filter := toBsonDoc(desc["filter"])
	update := toBsonDoc(desc["update"])
	result, err := coll.UpdateOne(ctx, filter, update)
	if err != nil {
		return nil, fmt.Errorf("mongodb: updateOne failed: %w", err)
	}
	return []map[string]any{{
		"matchedCount":  result.MatchedCount,
		"modifiedCount": result.ModifiedCount,
	}}, nil
}

func (e *Executor) executeUpdateMany(ctx context.Context, coll *mongo.Collection, desc map[string]any) ([]map[string]any, error) {
	filter := toBsonDoc(desc["filter"])
	update := toBsonDoc(desc["update"])
	result, err := coll.UpdateMany(ctx, filter, update)
	if err != nil {
		return nil, fmt.Errorf("mongodb: updateMany failed: %w", err)
	}
	return []map[string]any{{
		"matchedCount":  result.MatchedCount,
		"modifiedCount": result.ModifiedCount,
	}}, nil
}

// LoadManifest loads a MongoDB query manifest from a file.
func LoadManifest(path string) (*MongoManifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("mongodb: failed to read manifest: %w", err)
	}

	var manifest MongoManifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return nil, fmt.Errorf("mongodb: failed to parse manifest: %w", err)
	}

	return &manifest, nil
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

// substituteParams replaces $param, $ctx, and $literal markers with actual values.
func substituteParams(value any, params map[string]any) any {
	if value == nil {
		return nil
	}

	switch v := value.(type) {
	case map[string]any:
		// Check for $param marker
		if paramName, ok := v["$param"].(string); ok {
			return params[paramName]
		}
		// Check for $ctx marker
		if ctxName, ok := v["$ctx"].(string); ok {
			return params[ctxName]
		}
		// Check for $literal marker
		if literal, ok := v["$literal"]; ok && len(v) == 1 {
			return literal
		}
		// Recurse into object
		result := make(map[string]any, len(v))
		for key, val := range v {
			result[key] = substituteParams(val, params)
		}
		return result

	case []any:
		result := make([]any, len(v))
		for i, item := range v {
			result[i] = substituteParams(item, params)
		}
		return result

	default:
		return value
	}
}

// toBsonDoc converts a generic map/value to a bson.D for ordered operations.
func toBsonDoc(value any) any {
	if value == nil {
		return bson.D{}
	}

	switch v := value.(type) {
	case map[string]any:
		doc := make(bson.D, 0, len(v))
		for key, val := range v {
			doc = append(doc, bson.E{Key: key, Value: toBsonValue(val)})
		}
		return doc
	default:
		return value
	}
}

// toBsonValue converts a generic value for use inside a bson document.
func toBsonValue(value any) any {
	if value == nil {
		return nil
	}

	switch v := value.(type) {
	case map[string]any:
		doc := make(bson.D, 0, len(v))
		for key, val := range v {
			doc = append(doc, bson.E{Key: key, Value: toBsonValue(val)})
		}
		return doc
	case []any:
		arr := make(bson.A, len(v))
		for i, item := range v {
			arr[i] = toBsonValue(item)
		}
		return arr
	default:
		return value
	}
}

// normalizeDoc converts a bson document to a plain map for consistent output.
func normalizeDoc(doc any) map[string]any {
	switch v := doc.(type) {
	case bson.M:
		result := make(map[string]any, len(v))
		for key, val := range v {
			result[key] = normalizeValue(val)
		}
		return result
	case bson.D:
		result := make(map[string]any, len(v))
		for _, elem := range v {
			result[elem.Key] = normalizeValue(elem.Value)
		}
		return result
	case map[string]any:
		result := make(map[string]any, len(v))
		for key, val := range v {
			result[key] = normalizeValue(val)
		}
		return result
	default:
		return map[string]any{}
	}
}

// normalizeValue converts BSON-specific types to standard Go types.
func normalizeValue(val any) any {
	switch v := val.(type) {
	case bson.M:
		return normalizeDoc(v)
	case bson.D:
		return normalizeDoc(v)
	case bson.A:
		result := make([]any, len(v))
		for i, item := range v {
			result[i] = normalizeValue(item)
		}
		return result
	default:
		return val
	}
}

// toInt64 attempts to convert a value to int64 (handles float64 from JSON).
func toInt64(v any) (int64, bool) {
	switch n := v.(type) {
	case int64:
		return n, true
	case int:
		return int64(n), true
	case float64:
		return int64(n), true
	case json.Number:
		i, err := n.Int64()
		return i, err == nil
	default:
		return 0, false
	}
}
