using System.Text.Json;
using Vexnor.Core.Execution;
using Vexnor.Core.Manifest;
using Xunit;

namespace Vexnor.Core.Tests;

/// <summary>
/// Cross-runtime snapshot tests — fully dynamic.
/// Loads the manifest + expected outputs (including params) generated by the TypeScript side,
/// runs the same params through the .NET SqlBuilder, and asserts identical output.
///
/// Adding a new test case in generate-cross-runtime.ts automatically creates a .NET test —
/// no manual [Fact] methods needed.
///
/// If these tests fail, it means the .NET execution diverges from Node.js.
/// Regenerate: cd stacks/fixtures && npx tsx generate-cross-runtime.ts
/// </summary>
public class CrossRuntimeSnapshotTests
{
    private static readonly string BaseDir = Path.GetFullPath(
        Path.Join("..", "..", "..", "..", "..", "..", "fixtures", "manifests", "cross-runtime"), AppContext.BaseDirectory);
    private static readonly string DuckDBDir = Path.Join(BaseDir, "duckdb");

    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };

    private readonly QueryRegistry _registry;
    private readonly QueryRegistry _mssqlRegistry;
    private readonly QueryRegistry _duckDBRegistry;
    private readonly Dictionary<string, ExpectedResult> _expected;
    private readonly Dictionary<string, ExpectedResult> _duckDBExpected;

    public CrossRuntimeSnapshotTests()
    {
        _registry = new QueryRegistry("postgresql");
        _mssqlRegistry = new QueryRegistry("transactsql");
        _duckDBRegistry = new QueryRegistry("duckdb");

        var manifestPath = Path.Join(BaseDir, "manifest.json");
        if (File.Exists(manifestPath))
        {
            _registry.LoadFile(manifestPath);
            _mssqlRegistry.LoadFile(manifestPath);
        }

        var expectedPath = Path.Join(BaseDir, "expected.json");
        _expected = File.Exists(expectedPath)
            ? JsonSerializer.Deserialize<Dictionary<string, ExpectedResult>>(File.ReadAllText(expectedPath), JsonOptions)!
            : new();

        var duckDBManifestPath = Path.Join(DuckDBDir, "manifest.json");
        if (File.Exists(duckDBManifestPath))
        {
            var duckDBManifest = ManifestLoader.LoadFile(duckDBManifestPath);
            if (duckDBManifest.Dialect != "duckdb")
                throw new InvalidDataException($"Manifest dialect is '{duckDBManifest.Dialect}', expected 'duckdb'.");
            _duckDBRegistry.Load(duckDBManifest);
        }

        var duckDBExpectedPath = Path.Join(DuckDBDir, "expected.json");
        _duckDBExpected = File.Exists(duckDBExpectedPath)
            ? JsonSerializer.Deserialize<Dictionary<string, ExpectedResult>>(File.ReadAllText(duckDBExpectedPath), JsonOptions)!
            : new();
    }

    // ─── Dynamic test: one test per manifest entry ───────────────────────────

    [Theory]
    [MemberData(nameof(GetPostgresTestCases))]
    public void CrossRuntime_Postgres(string testName)
    {
        var expected = _expected[testName];
        var parameters = DeserializeParams(expected.Params);

        if (expected.Error != null)
        {
            Assert.ThrowsAny<Exception>(() => _registry.Build(expected.Hash!, parameters));
            return;
        }

        var result = _registry.Build(expected.Hash!, parameters);

        Assert.Equal(expected.Text, result.Text);
        Assert.Equal(expected.Values!.Count, result.Values.Count);
        for (int i = 0; i < expected.Values.Count; i++)
        {
            Assert.Equal(expected.Values[i]?.ToString(), result.Values[i]?.ToString());
        }
    }

    [Theory]
    [MemberData(nameof(GetMssqlTestCases))]
    public void CrossRuntime_Mssql(string testName)
    {
        var expected = _expected[testName];
        var parameters = DeserializeParams(expected.Params);

        var result = _mssqlRegistry.Build(expected.Hash!, parameters);

        Assert.Equal(expected.Text, result.Text);
        Assert.Equal(expected.Values!.Count, result.Values.Count);
        for (int i = 0; i < expected.Values.Count; i++)
        {
            Assert.Equal(expected.Values[i]?.ToString(), result.Values[i]?.ToString());
        }
    }

    [Theory]
    [MemberData(nameof(GetDuckDBTestCases))]
    public void CrossRuntime_DuckDB(string testName)
    {
        var expected = _duckDBExpected[testName];
        var parameters = DeserializeParams(expected.Params);

        if (expected.Error != null)
        {
            Assert.ThrowsAny<Exception>(() => _duckDBRegistry.Build(expected.Hash!, parameters));
            return;
        }

        var result = _duckDBRegistry.Build(expected.Hash!, parameters);

        Assert.Equal(expected.Text, result.Text);
        Assert.Equal(expected.Values!.Count, result.Values.Count);
        for (int i = 0; i < expected.Values.Count; i++)
        {
            Assert.Equal(expected.Values[i]?.ToString(), result.Values[i]?.ToString());
        }
    }

    // ─── Completeness guard: manifest count == expected count ─────────────────

    [Fact]
    public void AllManifestEntries_HaveExpectedOutput()
    {
        var manifestPath = Path.Join(BaseDir, "manifest.json");
        var manifestJson = JsonSerializer.Deserialize<JsonElement>(File.ReadAllText(manifestPath));
        var manifestKeys = manifestJson.GetProperty("queries").EnumerateObject().Select(p => p.Name).ToHashSet();
        var expectedKeys = _expected.Keys.ToHashSet();

        var missingFromExpected = manifestKeys.Except(expectedKeys).ToList();
        var missingFromManifest = expectedKeys.Except(manifestKeys).ToList();

        Assert.Empty(missingFromExpected);
        Assert.Empty(missingFromManifest);
    }

    [Fact]
    public void AllDuckDBManifestEntries_HaveExpectedOutput()
    {
        var manifestPath = Path.Join(DuckDBDir, "manifest.json");
        var manifestJson = JsonSerializer.Deserialize<JsonElement>(File.ReadAllText(manifestPath));
        var manifestKeys = manifestJson.GetProperty("queries").EnumerateObject().Select(p => p.Name).ToHashSet();
        var expectedKeys = _duckDBExpected.Keys.ToHashSet();

        Assert.Empty(manifestKeys.Except(expectedKeys));
        Assert.Empty(expectedKeys.Except(manifestKeys));
    }

    // ─── Test case providers ─────────────────────────────────────────────────

    public static IEnumerable<object[]> GetPostgresTestCases()
    {
        var expectedPath = Path.Join(BaseDir, "expected.json");
        if (!File.Exists(expectedPath)) yield break;

        var expected = JsonSerializer.Deserialize<Dictionary<string, ExpectedResult>>(
            File.ReadAllText(expectedPath), new JsonSerializerOptions { PropertyNameCaseInsensitive = true })!;

        foreach (var name in expected.Keys.Where(k => !k.Contains("Mssql")))
            yield return [name];
    }

    public static IEnumerable<object[]> GetMssqlTestCases()
    {
        var expectedPath = Path.Join(BaseDir, "expected.json");
        if (!File.Exists(expectedPath)) yield break;

        var expected = JsonSerializer.Deserialize<Dictionary<string, ExpectedResult>>(
            File.ReadAllText(expectedPath), new JsonSerializerOptions { PropertyNameCaseInsensitive = true })!;

        foreach (var name in expected.Keys.Where(k => k.Contains("Mssql")))
            yield return [name];
    }

    public static IEnumerable<object[]> GetDuckDBTestCases()
    {
        var expectedPath = Path.Join(DuckDBDir, "expected.json");
        if (!File.Exists(expectedPath)) yield break;

        var expected = JsonSerializer.Deserialize<Dictionary<string, ExpectedResult>>(
            File.ReadAllText(expectedPath), new JsonSerializerOptions { PropertyNameCaseInsensitive = true })!;

        foreach (var name in expected.Keys)
            yield return [name];
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────

    /// <summary>
    /// Deserializes the params JsonElement from expected.json into the Dictionary shape
    /// that SqlBuilder.Build() expects.
    /// </summary>
    private static Dictionary<string, object?> DeserializeParams(JsonElement? paramsElement)
    {
        if (paramsElement == null || paramsElement.Value.ValueKind == JsonValueKind.Null)
            return new();

        return JsonElementToDict(paramsElement.Value);
    }

    private static Dictionary<string, object?> JsonElementToDict(JsonElement element)
    {
        var dict = new Dictionary<string, object?>();
        if (element.ValueKind != JsonValueKind.Object) return dict;

        foreach (var prop in element.EnumerateObject())
        {
            dict[prop.Name] = JsonElementToObject(prop.Value);
        }
        return dict;
    }

    private static object? JsonElementToObject(JsonElement element)
    {
        return element.ValueKind switch
        {
            JsonValueKind.Null => null,
            JsonValueKind.True => true,
            JsonValueKind.False => false,
            JsonValueKind.String => element.GetString(),
            JsonValueKind.Number => element.TryGetInt64(out var l) ? (object)l : element.GetDouble(),
            JsonValueKind.Array => element.EnumerateArray().Select(JsonElementToObject).ToArray(),
            JsonValueKind.Object => JsonElementToDict(element),
            _ => element.ToString()
        };
    }

    private sealed class ExpectedResult
    {
        public string? Hash { get; set; }
        public string? Text { get; set; }
        public List<object?>? Values { get; set; }
        public JsonElement? Params { get; set; }
        public string? Error { get; set; }
    }
}
