using System.Text.Json;
using Vexnor.Core.Execution;
using Vexnor.Core.Manifest;
using Xunit;

namespace Vexnor.Core.Tests;

/// <summary>
/// Cross-runtime snapshot tests.
/// Loads the manifest + expected outputs generated by the TypeScript side,
/// runs the same params through the .NET SqlBuilder, and asserts identical output.
///
/// If these tests fail, it means the .NET execution diverges from Node.js.
/// Regenerate: cd stacks/fixtures && npx tsx generate-cross-runtime.ts
/// </summary>
public class CrossRuntimeSnapshotTests
{
    private static readonly string BaseDir = Path.GetFullPath(
        Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "..", "fixtures", "manifests", "cross-runtime"));

    private readonly QueryRegistry _registry;
    private readonly QueryRegistry _mssqlRegistry;
    private readonly Dictionary<string, ExpectedResult> _expected;

    public CrossRuntimeSnapshotTests()
    {
        _registry = new QueryRegistry("postgresql");
        _mssqlRegistry = new QueryRegistry("transactsql");

        var manifestPath = Path.Combine(BaseDir, "manifest.json");
        if (File.Exists(manifestPath))
        {
            _registry.LoadFile(manifestPath);
            _mssqlRegistry.LoadFile(manifestPath);
        }

        var expectedPath = Path.Combine(BaseDir, "expected.json");
        var jsonOptions = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
        _expected = File.Exists(expectedPath)
            ? JsonSerializer.Deserialize<Dictionary<string, ExpectedResult>>(File.ReadAllText(expectedPath), jsonOptions)!
            : new();
    }

    private void AssertMatch(string testName, Dictionary<string, object?> parameters)
    {
        if (!_expected.TryGetValue(testName, out var expected))
        {
            Assert.Fail($"No expected output for test case: {testName}");
            return;
        }

        if (expected.Error != null)
        {
            // TS threw — .NET should too
            Assert.Throws<Exception>(() => _registry.Build(expected.Hash!, parameters));
            return;
        }

        var result = _registry.Build(expected.Hash!, parameters);

        Assert.Equal(expected.Text, result.Text);
        Assert.Equal(expected.Values!.Count, result.Values.Count);
        for (int i = 0; i < expected.Values.Count; i++)
        {
            var expectedVal = expected.Values[i]?.ToString();
            var actualVal = result.Values[i]?.ToString();
            Assert.Equal(expectedVal, actualVal);
        }
    }

    // ─── orderBy ─────────────────────────────────────────────────────────────

    [Fact] public void OrderBy_Single() => AssertMatch("xOrderBySingle", Params(("orderBy", Obj(("createdAt", "DESC")))));
    [Fact] public void OrderBy_Multi() => AssertMatch("xOrderByMulti", Params(("orderBy", Obj(("status", "ASC"), ("createdAt", "DESC")))));
    [Fact] public void OrderBy_Null() => AssertMatch("xOrderByNull", Params(("orderBy", null)));

    // ─── filterBy ────────────────────────────────────────────────────────────

    [Fact] public void Filter_Equality() => AssertMatch("xFilterEquality",
        Params(("filterBy", Obj(("email", "jane@example.com"), ("status", "active")))));

    [Fact] public void Filter_Operators() => AssertMatch("xFilterOperators",
        Params(("filterBy", new object?[] {
            Obj(("createdAt", new object?[] { ">=", "2024-01-01" })),
            Obj(("status", new object?[] { "in", new object?[] { "active", "confirmed" } })),
            Obj(("parentId", new object?[] { "isNull" })),
        })));

    [Fact] public void Filter_OrGroup() => AssertMatch("xFilterOrGroup",
        Params(("filterBy", new object?[] {
            Obj(("status", "active")),
            Obj(("or", new object?[] {
                Obj(("email", new object?[] { "like", "%@vip.com" })),
                Obj(("parentId", new object?[] { "isNotNull" })),
            })),
        })));

    [Fact] public void Filter_Empty() => AssertMatch("xFilterEmpty", Params(("filterBy", null)));

    // ─── insert ──────────────────────────────────────────────────────────────

    [Fact] public void Insert_Single() => AssertMatch("xInsertSingle",
        Params(("rows", new object?[] { Obj(("email", "a@test.com"), ("firstName", "A"), ("lastName", "B")) })));

    [Fact] public void Insert_Multi() => AssertMatch("xInsertMulti",
        Params(("rows", new object?[] {
            Obj(("email", "a@test.com"), ("firstName", "A"), ("lastName", "AA")),
            Obj(("email", "b@test.com"), ("firstName", "B"), ("lastName", "BB")),
        })));

    // ─── set ─────────────────────────────────────────────────────────────────

    [Fact] public void Set_Single() => AssertMatch("xSetSingle",
        Params(("set", Obj(("email", "updated@test.com"))), ("accountId", "uuid-123")));

    [Fact] public void Set_Multi() => AssertMatch("xSetMulti",
        Params(("set", Obj(("email", "new@test.com"), ("firstName", "Jane"), ("lastName", "Doe"))), ("accountId", "uuid-456")));

    // ─── when ────────────────────────────────────────────────────────────────

    [Fact] public void When_True() => AssertMatch("xWhenTrue",
        Params(("status", "active"), ("hasEmail", true), ("email", "test@example.com")));

    [Fact] public void When_False() => AssertMatch("xWhenFalse",
        Params(("status", "active"), ("hasEmail", false), ("email", "test@example.com")));

    [Fact] public void When_WithElse() => AssertMatch("xWhenWithElse",
        Params(("sortAsc", true)));

    // ─── pagination ───────────────────────────────────────────────────────────

    [Fact] public void Pagination_LimitOnly() => AssertMatch("xPaginationLimitOnly",
        Params(("limit", 10)));

    [Fact] public void Pagination_Both() => AssertMatch("xPaginationBoth",
        Params(
            ("filterBy", new object?[] { Obj(("status", "active")) }),
            ("orderBy", Obj(("createdAt", "DESC"))),
            ("limit", 25),
            ("offset", 50)
        ));

    // ─── combined ────────────────────────────────────────────────────────────

    [Fact] public void Combined_FilterAndOrder() => AssertMatch("xCombined",
        Params(
            ("filterBy", new object?[] { Obj(("status", "active")), Obj(("email", new object?[] { "like", "%@vip%" })) }),
            ("orderBy", Obj(("createdAt", "DESC"))),
            ("limit", 100)
        ));

    // ─── Helpers ─────────────────────────────────────────────────────────────

    private void AssertMatchMssql(string testName, Dictionary<string, object?> parameters)
    {
        if (!_expected.TryGetValue(testName, out var expected))
        {
            Assert.Fail($"No expected output for test case: {testName}");
            return;
        }

        var result = _mssqlRegistry.Build(expected.Hash!, parameters);
        Assert.Equal(expected.Text, result.Text);
        Assert.Equal(expected.Values!.Count, result.Values.Count);
        for (int i = 0; i < expected.Values.Count; i++)
        {
            Assert.Equal(expected.Values[i]?.ToString(), result.Values[i]?.ToString());
        }
    }

    // ─── upsert ──────────────────────────────────────────────────────────────

    [Fact] public void Upsert_Single() => AssertMatch("xUpsertSingle", Params(
        ("rows", new object?[] { Obj(("accountId", "uuid-1"), ("email", "a@test.com"), ("firstName", "A"), ("lastName", "B")) })
    ));

    [Fact] public void Upsert_Multi() => AssertMatch("xUpsertMulti", Params(
        ("rows", new object?[] { Obj(("accountId", "uuid-1"), ("email", "a@test.com"), ("firstName", "A"), ("lastName", "AA")), Obj(("accountId", "uuid-2"), ("email", "b@test.com"), ("firstName", "B"), ("lastName", "BB")) })
    ));

    [Fact] public void Upsert_Mssql() => AssertMatchMssql("xUpsertMssql", Params(
        ("rows", new object?[] { Obj(("accountId", "uuid-1"), ("email", "a@test.com"), ("firstName", "A"), ("lastName", "B")) })
    ));

    // ─── Static helpers ──────────────────────────────────────────────────────

    private static Dictionary<string, object?> Params(params (string key, object? value)[] entries) =>
        entries.ToDictionary(e => e.key, e => e.value);

    private static Dictionary<string, object?> Obj(params (string key, object? value)[] entries) =>
        entries.ToDictionary(e => e.key, e => e.value);

    private sealed class ExpectedResult
    {
        public string? Hash { get; set; }
        public string? Text { get; set; }
        public List<object?>? Values { get; set; }
        public string? Error { get; set; }
    }
}
