/* File generated by Valnor. Do not edit. */
import * as valnor from "valnor";

export const OrderItem = valnor.newSqlTable({
   name: "order_item",
   schema: "main",
   types: <{ Select: IOrderItemSelect, Insert: IOrderItemInsert, Update: IOrderItemUpdate }>{}, 
   pk: ["orderId"], 
},{

   /**
    * order_id TEXT
   */
   orderId: "order_id",

   /**
    * product_id TEXT
   */
   productId: "product_id",

   /**
    * created_at TEXT default datetime('now')
   */
   createdAt: "created_at",

   /**
    * modified_at TEXT default datetime('now')
   */
   modifiedAt: "modified_at",

   /**
    * product_price REAL
   */
   productPrice: "product_price",

   /**
    * discount_price REAL
   */
   discountPrice: "discount_price",

   /**
    * quantity INTEGER
   */
   quantity: "quantity",

   /**
    * metadata TEXT
   */
   metadata: "metadata",
});

export type IOrderItemInsert = {
   orderId: string;
   productId: string;
   createdAt?: string;
   modifiedAt?: string;
   productPrice: number;
   discountPrice?: number | null;
   quantity: number;
   metadata?: string | null;
}

export type IOrderItemUpdate = Partial<IOrderItemInsert>;

export type IOrderItemSelect = {
   readonly orderId: string
   readonly productId: string
   readonly createdAt: string
   readonly modifiedAt: string
   readonly productPrice: number
   readonly discountPrice: number | null
   readonly quantity: number
   readonly metadata: string | null
}

export type IOrderItemJson = valnor.JsonRow<IOrderItemSelect>;