/* File generated by Valnor. Do not edit. */
import * as valnor from "valnor";

export const MigrationValnor = valnor.newSqlTable({
   name: "migration_valnor",
   schema: "main",
   types: <{ Select: IMigrationValnorSelect, Insert: IMigrationValnorInsert, Update: IMigrationValnorUpdate }>{}, 
   pk: ["version"], 
},{

   /**
    * version INTEGER
   */
   version: "version",

   /**
    * name TEXT
   */
   name: "name",

   /**
    * md5 TEXT
   */
   md5: "md5",

   /**
    * run_at TIMESTAMP WITH TIME ZONE
   */
   runAt: "run_at",
});

export type IMigrationValnorInsert = {
   version?: number | null;
   name?: string | null;
   md5?: string | null;
   runAt?: Date | null;
}

export type IMigrationValnorUpdate = Partial<IMigrationValnorInsert>;

export type IMigrationValnorSelect = {
   readonly version: number | null
   readonly name: string | null
   readonly md5: string | null
   readonly runAt: Date | null
}

export type IMigrationValnorJson = valnor.JsonRow<IMigrationValnorSelect>;