/* File generated by Valnor. Do not edit. */
import * as valnor from "valnor";

export const Product = valnor.newSqlTable(
   {
      name: "product",
      schema: "main",
      types: <{ Select: IProductSelect; Insert: IProductInsert; Update: IProductUpdate }>{},
      pk: ["productId"],
   },
   {
      /**
       * product_id TEXT default lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))
       */
      productId: "product_id",

      /**
       * name TEXT
       */
      name: "name",

      /**
       * description TEXT
       */
      description: "description",

      /**
       * price REAL
       */
      price: "price",
   },
);

export type IProductInsert = {
   productId?: string | null;
   name: string;
   description?: string | null;
   price: number;
};

export type IProductUpdate = Partial<IProductInsert>;

export type IProductSelect = {
   readonly productId: string | null;
   readonly name: string;
   readonly description: string | null;
   readonly price: number;
};

export type IProductJson = valnor.JsonRow<IProductSelect>;
