/*
 File generated by Valnor. Do not edit! 
*/
import * as valnor from "valnor";
import * as udt from "./valnor_test-enums.js";


export const AccountOrderSummary = valnor.newSqlTable<{ Select: IAccountOrderSummarySelect }>({
   crud:
   {
      select: true, 
      insert: false, 
      update: false, 
      delete: false, 
   },
   tableInfo:
   {
      name: "account_order_summary",
      schema: "valnor_test",
   },
   pk: [], 
   dialect: "postgresql",
   columns:
   {

      /**
       * account_id uuid
      */
      accountId: "account_id",

      /**
       * email varchar
      */
      email: "email",

      /**
       * first_name varchar
      */
      firstName: "first_name",

      /**
       * last_name varchar
      */
      lastName: "last_name",

      /**
       * status account_status
      */
      status: "status",

      /**
       * order_count int8
      */
      orderCount: "order_count",

      /**
       * latest_order_at timestamptz
      */
      latestOrderAt: "latest_order_at",
   }
});

export type IAccountOrderSummarySelect = {
   accountId: string | null
   email: string | null
   firstName: string | null
   lastName: string | null
   status: udt.AccountStatusUdt | null
   orderCount: string | null
   latestOrderAt: Date | null
}

export type IAccountOrderSummaryJson = valnor.JsonRow<IAccountOrderSummarySelect>;