/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";

import type * as vexnorPostgres from "@vexnor/postgres";
export const TypeCoverage = vexnor.newSqlTable<{
   Select: ITypeCoverageSelect;
   Insert: ITypeCoverageInsert;
   Update: ITypeCoverageUpdate;
   Delete: true;
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "type_coverage",
      schema: "vexnor_dev",
   },
   pk: ["colUuid"],
   dialect: "postgresql",
   columns: {

      /**
       * col_uuid uuid default gen_random_uuid()
       */
      colUuid: "col_uuid",

      /**
       * col_text text
       */
      colText: "col_text",

      /**
       * col_varchar varchar
       */
      colVarchar: "col_varchar",

      /**
       * col_bpchar bpchar
       */
      colBpchar: "col_bpchar",

      /**
       * col_json json
       */
      colJson: "col_json",

      /**
       * col_jsonb jsonb
       */
      colJsonb: "col_jsonb",

      /**
       * col_xml xml
       */
      colXml: "col_xml",

      /**
       * col_inet inet
       */
      colInet: "col_inet",

      /**
       * col_cidr cidr
       */
      colCidr: "col_cidr",

      /**
       * col_macaddr macaddr
       */
      colMacaddr: "col_macaddr",

      /**
       * col_bit bit
       */
      colBit: "col_bit",

      /**
       * col_varbit varbit
       */
      colVarbit: "col_varbit",

      /**
       * col_interval interval
       */
      colInterval: "col_interval",

      /**
       * col_time time
       */
      colTime: "col_time",

      /**
       * col_timetz timetz
       */
      colTimetz: "col_timetz",

      /**
       * col_money money
       */
      colMoney: "col_money",

      /**
       * col_int2 int2
       */
      colInt2: "col_int2",

      /**
       * col_int4 int4
       */
      colInt4: "col_int4",

      /**
       * col_float4 float4
       */
      colFloat4: "col_float4",

      /**
       * col_float8 float8
       */
      colFloat8: "col_float8",

      /**
       * col_int8 int8
       */
      colInt8: "col_int8",

      /**
       * col_numeric numeric
       */
      colNumeric: "col_numeric",

      /**
       * col_bool bool
       */
      colBool: "col_bool",

      /**
       * col_date date
       */
      colDate: "col_date",

      /**
       * col_timestamp timestamp
       */
      colTimestamp: "col_timestamp",

      /**
       * col_timestamptz timestamptz default now()
       */
      colTimestamptz: "col_timestamptz",

      /**
       * col_bytea bytea
       */
      colBytea: "col_bytea",

      /**
       * col_oid oid
       */
      colOid: "col_oid",

      /**
       * col_xid xid
       */
      colXid: "col_xid",

      /**
       * col_name name
       */
      colName: "col_name",

      /**
       * col_pg_lsn pg_lsn
       */
      colPgLsn: "col_pg_lsn",

      /**
       * col_tsvector tsvector
       */
      colTsvector: "col_tsvector",

      /**
       * col_tsquery tsquery
       */
      colTsquery: "col_tsquery",

      /**
       * col_point point
       */
      colPoint: "col_point",

      /**
       * col_line line
       */
      colLine: "col_line",

      /**
       * col_lseg lseg
       */
      colLseg: "col_lseg",

      /**
       * col_box box
       */
      colBox: "col_box",

      /**
       * col_path path
       */
      colPath: "col_path",

      /**
       * col_polygon polygon
       */
      colPolygon: "col_polygon",

      /**
       * col_circle circle
       */
      colCircle: "col_circle",
   },
   jsonSchema: {
      colDate: "Date",
      colTimestamp: "Date",
      colTimestamptz: "Date",
   },
});
export type ITypeCoverageInsert = {
   colUuid?: string;
   colText: string;
   colVarchar: string;
   colBpchar: string;
   colJson?: unknown | null;
   colJsonb?: unknown | null;
   colXml?: string | null;
   colInet?: string | null;
   colCidr?: string | null;
   colMacaddr?: string | null;
   colBit?: string | null;
   colVarbit?: string | null;
   colInterval?: string | null;
   colTime?: string | null;
   colTimetz?: string | null;
   colMoney?: string | null;
   colInt2: number;
   colInt4: number;
   colFloat4: number;
   colFloat8: number;
   colInt8: string;
   colNumeric?: string | null;
   colBool: boolean;
   colDate: Date;
   colTimestamp: Date;
   colTimestamptz?: Date;
   colBytea?: Uint8Array | null;
   colOid?: number | null;
   colXid?: string | null;
   colName?: string | null;
   colPgLsn?: string | null;
   colTsvector?: string | null;
   colTsquery?: string | null;
   colPoint?: string | null;
   colLine?: string | null;
   colLseg?: string | null;
   colBox?: string | null;
   colPath?: string | null;
   colPolygon?: string | null;
   colCircle?: string | null;
};

export type ITypeCoverageUpdate = Partial<ITypeCoverageInsert>;

export type ITypeCoverageSelect = {
   colUuid: string;
   colText: string;
   colVarchar: string;
   colBpchar: string;
   colJson: unknown | null;
   colJsonb: unknown | null;
   colXml: string | null;
   colInet: string | null;
   colCidr: string | null;
   colMacaddr: string | null;
   colBit: string | null;
   colVarbit: string | null;
   colInterval: vexnorPostgres.Interval | null;
   colTime: string | null;
   colTimetz: string | null;
   colMoney: string | null;
   colInt2: number;
   colInt4: number;
   colFloat4: number;
   colFloat8: number;
   colInt8: string;
   colNumeric: string | null;
   colBool: boolean;
   colDate: Date;
   colTimestamp: Date;
   colTimestamptz: Date;
   colBytea: Uint8Array | null;
   colOid: number | null;
   colXid: string | null;
   colName: string | null;
   colPgLsn: string | null;
   colTsvector: string | null;
   colTsquery: string | null;
   colPoint: vexnorPostgres.Point | null;
   colLine: string | null;
   colLseg: string | null;
   colBox: string | null;
   colPath: string | null;
   colPolygon: string | null;
   colCircle: vexnorPostgres.Circle | null;
};

export type ITypeCoverageJson = vexnor.JsonRow<ITypeCoverageSelect>;