// File generated by sql-typecraft. Do not edit.
import * as lib from "sql-typecraft";

export const Product = lib.newTable({
   name: "product",
   schema: "one_sql",
   types: <{ Insert: IProductInsert, Update: IProductUpdate }>{}, 
   pk: "product_pk", 
},{

   /**
    * product_id uuid default gen_random_uuid()
   */
   productId: "product_id",

   /**
    * discount numeric
   */
   discount: "discount",

   /**
    * is_available bool default true
   */
   isAvailable: "is_available",

   /**
    * is_published bool default false
   */
   isPublished: "is_published",

   /**
    * label varchar
   */
   label: "label",

   /**
    * created_at timestamptz default now()
   */
   createdAt: "created_at",

   /**
    * modified_at timestamptz default now()
   */
   modifiedAt: "modified_at",

   /**
    * price numeric
   */
   price: "price",
});

export type IProductInsert = {
   productId?: string;
   discount?: string | null;
   isAvailable?: boolean;
   isPublished?: boolean;
   label: string;
   createdAt?: Date;
   modifiedAt?: Date;
   price: string;
}

export type IProductUpdate = Partial<IProductInsert>;

export type IProductSelect = {
   readonly productId: string
   readonly discount: string | null
   readonly isAvailable: boolean
   readonly isPublished: boolean
   readonly label: string
   readonly createdAt: Date
   readonly modifiedAt: Date
   readonly price: string
}

export type IProductJson = lib.JsonRow<IProductSelect>;