/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "vexnor";


export const Account = vexnor.newSqlTable<{ Select: IAccountSelect, Insert: IAccountInsert, Update: IAccountUpdate; Delete: true }>({
   crud:
   {
      select: true, 
      insert: true, 
      update: true, 
      delete: true, 
   },
   tableInfo:
   {
      name: "account",
      schema: "main",
   },
   pk: ["accountId"], 
   dialect: "sqlite",
   columns:
   {

      /**
       * account_id TEXT default lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))
      */
      accountId: "account_id",

      /**
       * status TEXT default 'created'
      */
      status: "status",

      /**
       * email TEXT
      */
      email: "email",

      /**
       * first_name TEXT
      */
      firstName: "first_name",

      /**
       * last_name TEXT
      */
      lastName: "last_name",

      /**
       * notes TEXT
      */
      notes: "notes",

      /**
       * created_at TEXT default datetime('now')
      */
      createdAt: "created_at",

      /**
       * modified_at TEXT default datetime('now')
      */
      modifiedAt: "modified_at",

      /**
       * parent_id TEXT
      */
      parentId: "parent_id",
   }
});

export type IAccountInsert = {
   accountId?: string;
   status?: string;
   email: string;
   firstName: string;
   lastName: string;
   notes?: string | null;
   createdAt?: string;
   modifiedAt?: string;
   parentId?: string | null;
}

export type IAccountUpdate = Partial<IAccountInsert>;

export type IAccountSelect = {
   accountId: string
   status: string
   email: string
   firstName: string
   lastName: string
   notes: string | null
   createdAt: string
   modifiedAt: string
   parentId: string | null
}

export type IAccountJson = vexnor.JsonRow<IAccountSelect>;