// noinspection SqlNoDataSourceInspection,SqlResolve
import {
   SqlTable,
   SqlSelectArgs,
   SqlUpdateArgs,
   SqlDeleteArgs,
   SqlInsertFromArgs,
   Sql,
   expand,
   sql,
   raw,
   row,
   info,
} from "@vexnor/core";
import { ok } from "@vexnor/core";
import { mssqlSelect, MssqlSelectResult } from "./mssql-select.js";
import { mssqlInsertRows, MssqlInsertRowsResult } from "./mssql-insert-rows.js";
import { mssqlInsertFrom, MssqlInsertFromResult } from "./mssql-insert-from.js";
import { mssqlUpdate, MssqlTableUpdateResult } from "./mssql-update.js";
import { mssqlDelete, MssqlDeleteResult } from "./mssql-delete.js";
import { mssqlUpsert, MssqlUpsertArgs, MssqlUpsertResult } from "./mssql-upsert.js";
import { MssqlQueryHandler } from "#/mssql-query-handler.js";
import { sql as mssqlSql } from "#/mssql-sql.js";

type PkFields<T extends { Select: Record<string, unknown> }> = Pick<
   T["Select"],
   Extract<keyof T["Select"], T extends { pk: ReadonlyArray<infer K> } ? K : never>
>;

/**
 * The set of typed query factories available on an MS SQL Server table handler.
 *
 * Generated by `newMssqlTableHandler()`. The available methods depend on
 * which CRUD operations are enabled in the table's `crud` config:
 *
 * - `findById()` — always available; returns a query parameterized by primary key fields
 * - `findBy()` — always available; returns a query parameterized by any subset of columns
 * - `select()` — available when `crud.select` is enabled
 * - `insertRows()` — available when `crud.insert` is enabled
 * - `insertFrom()` — available when `crud.insert` is enabled
 * - `update()` — available when `crud.update` is enabled
 * - `delete()` — available when `crud.delete` is enabled
 * - `upsert()` — available when `crud.insert` is enabled (uses MERGE)
 */
export type MssqlTableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
> = (T extends { Select: Record<string, unknown> }
   ? {
        findById: () => MssqlQueryHandler<{ Params: PkFields<T> & Partial<T["Select"]>; Row: T["Select"] }>;
        findBy: () => MssqlQueryHandler<{ Params: Partial<T["Select"]>; Row: T["Select"] }>;
        select: <Args extends SqlSelectArgs>(
           args: Args,
        ) => MssqlSelectResult<T & { Select: Record<string, unknown> }, Args>;
     }
   : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           insertRows: () => MssqlInsertRowsResult<
              T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }
           >;
           insertFrom: <
              Args extends SqlInsertFromArgs<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
           >(
              args: Args,
           ) => MssqlInsertFromResult<
              T & { Select: Record<string, unknown>; Insert: Record<string, unknown> },
              Args
           >;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Update: Record<string, unknown> }
      ? {
           update: <Args extends SqlUpdateArgs>(
              args: Args,
           ) => MssqlTableUpdateResult<
              T & { Select: Record<string, unknown>; Update: Record<string, unknown> },
              Args
           >;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Delete: true }
      ? {
           delete: <Args extends SqlDeleteArgs>(
              args: Args,
           ) => MssqlDeleteResult<T & { Select: Record<string, unknown>; Delete: true }, Args>;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           upsert: (
              args: MssqlUpsertArgs,
           ) => MssqlUpsertResult<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>;
        }
      : unknown);

function buildFindByExpand<T extends { Select: Record<string, unknown> }>(
   table: SqlTable<T>,
   fields: Partial<T["Select"]>,
) {
   const cols = table.cols;
   const pairs: Sql[] = [];
   for (const [key, value] of Object.entries(fields)) {
      if (value === undefined) continue;
      const col = cols[`$${key}` as `$${string}`];
      ok(col, `Column not found: ${key}`);
      pairs.push(sql`${col} = ${value}`.inline());
   }
   if (!pairs.length) return raw.BLANK;
   return pairs.slice(1).reduce((acc, pair) => sql`${acc} and ${pair}`.inline(), pairs[0]!);
}

function mssqlFind<T extends { Select: Record<string, unknown> }, Params extends Partial<T["Select"]>>(
   table: SqlTable<T>,
): MssqlQueryHandler<{ Params: Params; Row: T["Select"] }> {
   const whereExpand = expand<Params>(
      Object.fromEntries(Object.values(table.cols).map((col) => [col.key, null])) as Record<keyof Params, null>,
      (params) => {
         if (!params) return null;
         return buildFindByExpand(table, params as Partial<T["Select"]>) as ReturnType<typeof buildFindByExpand>;
      },
   );

   return mssqlSql`
      ${info({ driver: "transactsql" }) ?? raw.BLANK}
      select ${row(table.$$)}
      from ${table}
      ${sql`where ${whereExpand}`.inline("default")}
   ` as unknown as MssqlQueryHandler<{ Params: Params; Row: T["Select"] }>;
}

/**
 * Creates a `MssqlTableHandler` for the given table, providing typed query
 * factories for all CRUD operations enabled in the table's `crud` config.
 *
 * Used in generated files. Call the returned methods to get executable query
 * objects — each method returns a `MssqlQueryHandler` ready for `.getAll()`,
 * `.getOneRequired()`, or `.getOneOptional()`.
 *
 * @param table - The generated table constant to create a handler for.
 *
 * @example
 * const AccountHandler = newMssqlTableHandler(Account);
 *
 * const account = await AccountHandler.findById()
 *   .getOneRequired({ db: request, params: { accountId: "123" } });
 *
 * const accounts = await AccountHandler.select({ WHERE: sql`${Account.$active} = 1` })
 *   .getAll({ db: request });
 */
export function newMssqlTableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
>(table: SqlTable<T>): MssqlTableHandler<T> {
   const { select, insert, update, delete: delete$ } = table.crud;
   const handler: Record<string, unknown> = {};

   handler.findById = () => mssqlFind<T, PkFields<T> & Partial<T["Select"]>>(table);
   handler.findBy = () => mssqlFind<T, Partial<T["Select"]>>(table);

   if (select) {
      handler.select = <Args extends SqlSelectArgs>(args: Args) =>
         mssqlSelect(table as SqlTable<T & { Select: Record<string, unknown> }>, args);
   }
   if (insert) {
      handler.upsert = (args: MssqlUpsertArgs) =>
         mssqlUpsert(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         );
      handler.insertRows = () =>
         mssqlInsertRows(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
         );
      handler.insertFrom = <
         Args extends SqlInsertFromArgs<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
      >(
         args: Args,
      ) =>
         mssqlInsertFrom(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         );
   }
   if (update) {
      handler.update = <Args extends SqlUpdateArgs>(args: Args) =>
         mssqlUpdate(
            table as SqlTable<T & { Select: Record<string, unknown>; Update: Record<string, unknown> }>,
            args,
         );
   }
   if (delete$) {
      handler.delete = <Args extends SqlDeleteArgs>(args: Args) =>
         mssqlDelete(table as SqlTable<T & { Select: Record<string, unknown>; Delete: true }>, args);
   }

   return handler as MssqlTableHandler<T>;
}
