// noinspection SqlNoDataSourceInspection,SqlResolve
import {
   SqlTable,
   SqlSelectArgs,
   SqlUpdateArgs,
   SqlDeleteArgs,
   SqlInsertFromArgs,
} from "@vexnor/core";
import { mssqlSelect, MssqlSelectResult } from "./mssql-select.js";
import { mssqlInsertRows, MssqlInsertRowsResult } from "./mssql-insert-rows.js";
import { mssqlInsertFrom, MssqlInsertFromResult } from "./mssql-insert-from.js";
import { mssqlUpdate, MssqlTableUpdateResult } from "./mssql-update.js";
import { mssqlDelete, MssqlDeleteResult } from "./mssql-delete.js";
import { mssqlUpsert, MssqlUpsertArgs, MssqlUpsertResult } from "./mssql-upsert.js";

/**
 * The set of typed query factories available on an MS SQL Server table handler.
 *
 * Generated by `newMssqlTableHandler()`. The available methods depend on
 * which CRUD operations are enabled in the table's `crud` config:
 *
 * - `select()` — available when `crud.select` is enabled
 * - `insertRows()` — available when `crud.insert` is enabled
 * - `insertFrom()` — available when `crud.insert` is enabled
 * - `update()` — available when `crud.update` is enabled
 * - `delete()` — available when `crud.delete` is enabled
 * - `upsert()` — available when `crud.insert` is enabled (uses MERGE)
 */
export type MssqlTableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
> = (T extends { Select: Record<string, unknown> }
   ? {
        select: <Args extends SqlSelectArgs<T & { Select: Record<string, unknown> }>>(
           args: Args,
        ) => MssqlSelectResult<T & { Select: Record<string, unknown> }, Args>;
     }
   : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           insertRows: () => MssqlInsertRowsResult<
              T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }
           >;
           insertFrom: <
              Args extends SqlInsertFromArgs<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
           >(
              args: Args,
           ) => MssqlInsertFromResult<
              T & { Select: Record<string, unknown>; Insert: Record<string, unknown> },
              Args
           >;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Update: Record<string, unknown> }
      ? {
           update: <Args extends SqlUpdateArgs>(
              args: Args,
           ) => MssqlTableUpdateResult<
              T & { Select: Record<string, unknown>; Update: Record<string, unknown> },
              Args
           >;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Delete: true }
      ? {
           delete: <Args extends SqlDeleteArgs>(
              args: Args,
           ) => MssqlDeleteResult<T & { Select: Record<string, unknown>; Delete: true }, Args>;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           upsert: (
              args: MssqlUpsertArgs,
           ) => MssqlUpsertResult<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>;
        }
      : unknown);

/**
 * Creates a `MssqlTableHandler` for the given table, providing typed query
 * factories for all CRUD operations enabled in the table's `crud` config.
 *
 * Used in generated files. Call the returned methods to get executable query
 * objects — each method returns a `MssqlQueryHandler` ready for `.getAll()`,
 * `.getOneRequired()`, or `.getOneOptional()`.
 *
 * @param table - The generated table constant to create a handler for.
 *
 * @example
 * const AccountHandler = newMssqlTableHandler(Account);
 *
 * const accounts = await AccountHandler.select({ WHERE: sql`${Account.$active} = 1` })
 *   .getAll({ db: request });
 */
export function newMssqlTableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
>(table: SqlTable<T>): MssqlTableHandler<T> {
   const { select, insert, update, delete: delete$ } = table.crud;
   const handler: Record<string, unknown> = {};

   if (select) {
      handler.select = <Args extends SqlSelectArgs<T & { Select: Record<string, unknown> }>>(args: Args) =>
         mssqlSelect(table as SqlTable<T & { Select: Record<string, unknown> }>, args);
   }
   if (insert) {
      handler.upsert = (args: MssqlUpsertArgs) =>
         mssqlUpsert(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         );
      handler.insertRows = () =>
         mssqlInsertRows(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
         );
      handler.insertFrom = <
         Args extends SqlInsertFromArgs<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
      >(
         args: Args,
      ) =>
         mssqlInsertFrom(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         );
   }
   if (update) {
      handler.update = <Args extends SqlUpdateArgs>(args: Args) =>
         mssqlUpdate(
            table as SqlTable<T & { Select: Record<string, unknown>; Update: Record<string, unknown> }>,
            args,
         );
   }
   if (delete$) {
      handler.delete = <Args extends SqlDeleteArgs>(args: Args) =>
         mssqlDelete(table as SqlTable<T & { Select: Record<string, unknown>; Delete: true }>, args);
   }

   return handler as MssqlTableHandler<T>;
}
