// noinspection SqlNoDataSourceInspection,SqlResolve
import {
   SqlTable,
   SqlSelectArgs,
   SqlUpdateArgs,
   SqlDeleteArgs,
   SqlInsertFromArgs,
} from "@vexnor/core";
import { MssqlSelectCommand, MssqlSelectCommandResult } from "./mssql-select-command.js";
import { MssqlInsertRowsCommand, MssqlInsertRowsCommandResult } from "./mssql-insert-rows-command.js";
import { MssqlInsertFromCommand, MssqlInsertFromCommandResult } from "./mssql-insert-from-command.js";
import { MssqlUpdateCommand, MssqlUpdateCommandResult } from "./mssql-update-command.js";
import { MssqlDeleteCommand, MssqlDeleteCommandResult } from "./mssql-delete-command.js";
import { MssqlUpsertCommand, MssqlUpsertCommandArgs, MssqlUpsertCommandResult } from "./mssql-upsert-command.js";

/**
 * The set of typed query factories available on an MS SQL Server table handler.
 *
 * Generated by `newMssqlTableHandler()`. The available methods depend on
 * which CRUD operations are enabled in the table's `crud` config:
 *
 * - `select()` — available when `crud.select` is enabled
 * - `insertRows()` — available when `crud.insert` is enabled
 * - `insertFrom()` — available when `crud.insert` is enabled
 * - `update()` — available when `crud.update` is enabled
 * - `delete()` — available when `crud.delete` is enabled
 * - `upsert()` — available when `crud.insert` is enabled (uses MERGE)
 */
export type MssqlTableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
> = (T extends { Select: Record<string, unknown> }
   ? {
        select: <Args extends SqlSelectArgs<T & { Select: Record<string, unknown> }>>(
           args: Args,
        ) => MssqlSelectCommandResult<T & { Select: Record<string, unknown> }, Args>;
     }
   : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           insertRows: () => MssqlInsertRowsCommandResult<
              T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }
           >;
           insertFrom: <
              Args extends SqlInsertFromArgs<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
           >(
              args: Args,
           ) => MssqlInsertFromCommandResult<
              T & { Select: Record<string, unknown>; Insert: Record<string, unknown> },
              Args
           >;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Update: Record<string, unknown> }
      ? {
           update: <Args extends SqlUpdateArgs>(
              args: Args,
           ) => MssqlUpdateCommandResult<
              T & { Select: Record<string, unknown>; Update: Record<string, unknown> },
              Args
           >;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Delete: true }
      ? {
           delete: <Args extends SqlDeleteArgs>(
              args: Args,
           ) => MssqlDeleteCommandResult<T & { Select: Record<string, unknown>; Delete: true }, Args>;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           upsert: (
              args: MssqlUpsertCommandArgs,
           ) => MssqlUpsertCommandResult<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>;
        }
      : unknown);

/**
 * Creates a `MssqlTableHandler` for the given table, providing typed query
 * factories for all CRUD operations enabled in the table's `crud` config.
 *
 * Used in generated files. Call the returned methods to get executable query
 * objects — each method returns a `MssqlQueryHandler` ready for `.getAll()`,
 * `.getOneRequired()`, or `.getOneOptional()`.
 *
 * @param table - The generated table constant to create a handler for.
 *
 * @example
 * const AccountHandler = newMssqlTableHandler(Account);
 *
 * const accounts = await AccountHandler.select({ WHERE: sql`${Account.$active} = 1` })
 *   .getAll({ db: request });
 */
export function newMssqlTableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
>(table: SqlTable<T>): MssqlTableHandler<T> {
   const { select, insert, update, delete: delete$ } = table.crud;
   const handler: Record<string, unknown> = {};

   if (select) {
      handler.select = <Args extends SqlSelectArgs<T & { Select: Record<string, unknown> }>>(args: Args) =>
         new MssqlSelectCommand(table as SqlTable<T & { Select: Record<string, unknown> }>, args).execute();
   }
   if (insert) {
      handler.upsert = (args: MssqlUpsertCommandArgs) =>
         new MssqlUpsertCommand(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         ).execute();
      handler.insertRows = () =>
         new MssqlInsertRowsCommand(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
         ).execute();
      handler.insertFrom = <
         Args extends SqlInsertFromArgs<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
      >(
         args: Args,
      ) =>
         new MssqlInsertFromCommand(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         ).execute();
   }
   if (update) {
      handler.update = <Args extends SqlUpdateArgs>(args: Args) =>
         new MssqlUpdateCommand(
            table as SqlTable<T & { Select: Record<string, unknown>; Update: Record<string, unknown> }>,
            args,
         ).execute();
   }
   if (delete$) {
      handler.delete = <Args extends SqlDeleteArgs>(args: Args) =>
         new MssqlDeleteCommand(table as SqlTable<T & { Select: Record<string, unknown>; Delete: true }>, args).execute();
   }

   return handler as MssqlTableHandler<T>;
}
