using Vexnor.Core.Execution;
using Vexnor.Core.Manifest;
using Vexnor.Postgres;
using Xunit;

namespace Vexnor.Integration.Tests;

/// <summary>
/// End-to-end integration tests:
/// 1. Load manifest generated by `vexnor serialize` from TypeScript queries
/// 2. Build SQL using the .NET QueryRegistry
/// 3. Execute against a real PostgreSQL database
///
/// Prerequisites:
/// - Run `pnpm serialize:e2e` from the monorepo root to generate fixtures/manifests/
/// - PostgreSQL running on localhost:5432 with vexnor schema migrated
/// </summary>
public class EndToEndTests : IAsyncLifetime
{
    private readonly QueryRegistry _registry = new("postgresql");
    private PostgresExecutor? _executor;

    private const string ConnectionString =
        "Host=localhost;Port=5432;Database=postgres;Username=postgres;Password=postgres";

    public Task InitializeAsync()
    {
        // Load manifests from the shared fixtures package (relative to solution root)
        var solutionDir = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
        var manifestDir = Path.Combine(solutionDir, "..", "fixtures", "manifests", "postgres");
        if (Directory.Exists(manifestDir))
        {
            _registry.LoadDirectory(manifestDir);
        }

        _executor = new PostgresExecutor(ConnectionString);
        return Task.CompletedTask;
    }

    public Task DisposeAsync() => Task.CompletedTask;

    [Fact]
    public void Registry_LoadsQueriesFromManifest()
    {
        var queries = _registry.GetRegisteredQueries().ToList();
        Assert.True(queries.Count > 0, "Expected at least one query to be registered");
    }

    [Fact]
    public void Build_SelectByStatus_ProducesValidSql()
    {
        // Find the selectByStatus query by name
        var (hash, _) = _registry.GetRegisteredQueries().First(q => q.Name == "selectByStatus");

        var result = _registry.Build(hash, new() { ["status"] = "created" });

        Assert.Contains("SELECT", result.Text, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("WHERE", result.Text, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("$1", result.Text);
        Assert.Single(result.Values);
        Assert.Equal("created", result.Values[0]);
    }

    [Fact]
    public void Build_InsertAccounts_ProducesValidSql()
    {
        var (hash, _) = _registry.GetRegisteredQueries().First(q => q.Name == "insertAccounts");

        var rows = new List<Dictionary<string, object?>>
        {
            new() { ["email"] = "e2e@test.com", ["firstName"] = "E2E", ["lastName"] = "Test" }
        };
        var result = _registry.Build(hash, new() { ["rows"] = rows });

        Assert.Contains("INSERT INTO", result.Text, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("VALUES", result.Text, StringComparison.OrdinalIgnoreCase);
        Assert.Equal(3, result.Values.Count);
    }

    [Fact]
    public void Build_UpdateAccount_ProducesValidSql()
    {
        var (hash, _) = _registry.GetRegisteredQueries().First(q => q.Name == "updateAccount");

        var setValues = new Dictionary<string, object?> { ["email"] = "updated@test.com" };
        var result = _registry.Build(hash, new() { ["set"] = setValues, ["accountId"] = "test-id" });

        Assert.Contains("UPDATE", result.Text, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("SET", result.Text, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("$1", result.Text);
        Assert.Contains("$2", result.Text);
    }

    [Fact]
    public void Build_SelectWithFilter_ProducesValidSql()
    {
        var (hash, _) = _registry.GetRegisteredQueries().First(q => q.Name == "selectWithFilter");

        var filter = new Dictionary<string, object?> { ["email"] = "jane@test.com", ["status"] = "created" };
        var result = _registry.Build(hash, new() { ["filter"] = filter });

        Assert.Contains("$1", result.Text);
        Assert.Contains("$2", result.Text);
        Assert.Equal(2, result.Values.Count);
    }

    [Fact]
    public void Build_SelectOrdered_ProducesValidSql()
    {
        var (hash, _) = _registry.GetRegisteredQueries().First(q => q.Name == "selectOrdered");

        var orderBy = new Dictionary<string, object?> { ["email"] = "DESC" };
        var result = _registry.Build(hash, new() { ["orderBy"] = orderBy });

        Assert.Contains("ORDER BY", result.Text, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("DESC", result.Text);
    }

    [Fact]
    public void Build_SelectConditional_WhenTrue_IncludesEmailFilter()
    {
        var (hash, _) = _registry.GetRegisteredQueries().First(q => q.Name == "selectConditional");

        var result = _registry.Build(hash, new()
        {
            ["status"] = "created",
            ["hasEmail"] = true,
            ["email"] = "test@test.com"
        });

        Assert.Contains("$1", result.Text);
        Assert.Contains("$2", result.Text);
        Assert.Equal(2, result.Values.Count);
    }

    [Fact]
    public void Build_SelectConditional_WhenFalse_ExcludesEmailFilter()
    {
        var (hash, _) = _registry.GetRegisteredQueries().First(q => q.Name == "selectConditional");

        var result = _registry.Build(hash, new()
        {
            ["status"] = "created",
            ["hasEmail"] = false,
            ["email"] = ""
        });

        Assert.Single(result.Values);
        Assert.Equal("created", result.Values[0]);
    }

    [Fact]
    public async Task Execute_SelectByStatus_ReturnsResults()
    {
        if (_executor == null) return;

        // Use selectWithFilter with email (text type) to avoid enum casting issues
        var (hash, _) = _registry.GetRegisteredQueries().First(q => q.Name == "selectWithFilter");
        var filterValues = new Dictionary<string, object?> { ["email"] = "nonexistent@test.com" };
        var sql = _registry.Build(hash, new() { ["filter"] = filterValues });

        var results = await _executor.QueryAsync(sql);
        Assert.NotNull(results);
        // May be empty (no matching rows), but query executed successfully against real DB
    }
}
