/* File generated by Valnor. Do not edit. */
import * as valnor from "valnor";
import * as udt from "./one_sql-enums.js";

export const Product = valnor.newSqlTable(
   {
      name: "product",
      schema: "valnor_test",
      types: <{ Select: IProductSelect; Insert: IProductInsert; Update: IProductUpdate }>{},
      pk: "product_pk",
   },
   {
      /**
       * metadata jsonb
       */
      metadata: "metadata",

      /**
       * product_id uuid default gen_random_uuid()
       */
      productId: "product_id",

      /**
       * created_at timestamptz default now()
       */
      createdAt: "created_at",

      /**
       * modified_at timestamptz default now()
       */
      modifiedAt: "modified_at",

      /**
       * label varchar
       */
      label: "label",

      /**
       * tags _text
       */
      tags: "tags",

      /**
       * price numeric
       */
      price: "price",

      /**
       * discount numeric
       */
      discount: "discount",

      /**
       * is_available bool default true
       */
      isAvailable: "is_available",

      /**
       * is_published bool default false
       */
      isPublished: "is_published",
   },
);

export type IProductInsert = {
   metadata?: string | null;
   productId?: string;
   createdAt?: Date;
   modifiedAt?: Date;
   label: string;
   tags?: udt.TextUdt | null;
   price: string;
   discount?: string | null;
   isAvailable?: boolean;
   isPublished?: boolean;
};

export type IProductUpdate = Partial<IProductInsert>;

export type IProductSelect = {
   readonly metadata: string | null;
   readonly productId: string;
   readonly createdAt: Date;
   readonly modifiedAt: Date;
   readonly label: string;
   readonly tags: udt.TextUdt | null;
   readonly price: string;
   readonly discount: string | null;
   readonly isAvailable: boolean;
   readonly isPublished: boolean;
};

export type IProductJson = valnor.JsonRow<IProductSelect>;
