/* File generated by Valnor. Do not edit. */
import * as valnor from "valnor";

export const OrderItem = valnor.newSqlTable(
   {
      name: "order_item",
      schema: "valnor_test",
      types: <{ Select: IOrderItemSelect; Insert: IOrderItemInsert; Update: IOrderItemUpdate }>{},
      pk: "order_item_pk",
   },
   {
      /**
       * product_id uuid
       */
      productId: "product_id",

      /**
       * order_id uuid
       */
      orderId: "order_id",

      /**
       * modified_at timestamptz
       */
      modifiedAt: "modified_at",

      /**
       * created_at timestamptz
       */
      createdAt: "created_at",

      /**
       * order_item_id uuid default gen_random_uuid()
       */
      orderItemId: "order_item_id",

      /**
       * quantity int4
       */
      quantity: "quantity",

      /**
       * discount_price numeric
       */
      discountPrice: "discount_price",

      /**
       * product_price numeric
       */
      productPrice: "product_price",

      /**
       * metadata jsonb
       */
      metadata: "metadata",
   },
);

export type IOrderItemInsert = {
   productId: string;
   orderId: string;
   modifiedAt: Date;
   createdAt: Date;
   orderItemId?: string;
   quantity: number;
   discountPrice?: string | null;
   productPrice: string;
   metadata?: string | null;
};

export type IOrderItemUpdate = Partial<IOrderItemInsert>;

export type IOrderItemSelect = {
   readonly productId: string;
   readonly orderId: string;
   readonly modifiedAt: Date;
   readonly createdAt: Date;
   readonly orderItemId: string;
   readonly quantity: number;
   readonly discountPrice: string | null;
   readonly productPrice: string;
   readonly metadata: string | null;
};

export type IOrderItemJson = valnor.JsonRow<IOrderItemSelect>;
