/* File generated by Valnor. Do not edit. */
import * as valnor from "valnor";
import * as udt from "./one_sql-enums.js";

export const Account = valnor.newSqlTable(
   {
      name: "account",
      schema: "valnor_test",
      types: <{ Select: IAccountSelect; Insert: IAccountInsert; Update: IAccountUpdate }>{},
      pk: "account_pk",
   },
   {
      /**
       * modified_at timestamptz default now()
       */
      modifiedAt: "modified_at",

      /**
       * first_name varchar
       */
      firstName: "first_name",

      /**
       * email varchar
       */
      email: "email",

      /**
       * notes text
       */
      notes: "notes",

      /**
       * last_name varchar
       */
      lastName: "last_name",

      /**
       * created_at timestamptz default now()
       */
      createdAt: "created_at",

      /**
       * status account_status default 'created'::one_sql.account_status
       */
      status: "status",

      /**
       * account_id uuid default gen_random_uuid()
       */
      accountId: "account_id",
   },
);

export type IAccountInsert = {
   modifiedAt?: Date;
   firstName: string;
   email: string;
   notes?: string | null;
   lastName: string;
   createdAt?: Date;
   status?: udt.AccountStatusUdt;
   accountId?: string;
};

export type IAccountUpdate = Partial<IAccountInsert>;

export type IAccountSelect = {
   readonly modifiedAt: Date;
   readonly firstName: string;
   readonly email: string;
   readonly notes: string | null;
   readonly lastName: string;
   readonly createdAt: Date;
   readonly status: udt.AccountStatusUdt;
   readonly accountId: string;
};

export type IAccountJson = valnor.JsonRow<IAccountSelect>;
