/* File generated by Valnor. Do not edit. */
import * as udt from "./one_sql-enums.js";
import { newSqlTable } from "../../schema/index.js";
import { JsonRow } from "../../sql-types.js";

export const Account = newSqlTable(
   {
      name: "account",
      schema: "valnor_test",
      types: <{ Select: IAccountSelect; Insert: IAccountInsert; Update: IAccountUpdate }>{},
      pk: ["accountId"],
   },
   {
      /**
       * first_name varchar
       */
      firstName: "first_name",

      /**
       * account_id uuid default gen_random_uuid()
       */
      accountId: "account_id",

      /**
       * status account_status default 'created'::one_sql.account_status
       */
      status: "status",

      /**
       * created_at timestamptz default now()
       */
      createdAt: "created_at",

      /**
       * modified_at timestamptz default now()
       */
      modifiedAt: "modified_at",

      /**
       * last_name varchar
       */
      lastName: "last_name",

      /**
       * notes text
       */
      notes: "notes",

      /**
       * email varchar
       */
      email: "email",

      /**
       * parent_id uuid
       */
      parentId: "parent_id",
   },
);

export type IAccountInsert = {
   firstName: string;
   accountId?: string;
   status?: udt.AccountStatusUdt;
   createdAt?: Date;
   modifiedAt?: Date;
   lastName: string;
   notes?: string | null;
   email: string;
};

export type IAccountUpdate = Partial<IAccountInsert>;

export type IAccountSelect = {
   readonly firstName: string;
   readonly accountId: string;
   readonly status: udt.AccountStatusUdt;
   readonly createdAt: Date;
   readonly modifiedAt: Date;
   readonly lastName: string;
   readonly notes: string | null;
   readonly email: string;
};

export type IAccountJson = JsonRow<IAccountSelect>;
