/* File generated by Valnor. Do not edit. */
import { newSqlTable } from "../../schema/index.js";
import * as udt from "./one_sql-enums.js";
import { JsonRow } from "../../sql-types.js";

export const Order = newSqlTable(
   {
      name: "order",
      schema: "valnor_test",
      types: <{ Select: IOrderSelect; Insert: IOrderInsert; Update: IOrderUpdate }>{},
      pk: ["orderId"],
   },
   {
      /**
       * order_id uuid default gen_random_uuid()
       */
      orderId: "order_id",

      /**
       * status order_status default 'created'::one_sql.order_status
       */
      status: "status",

      /**
       * created_at timestamptz
       */
      createdAt: "created_at",

      /**
       * modified_at timestamptz
       */
      modifiedAt: "modified_at",

      /**
       * account_id uuid
       */
      accountId: "account_id",
   },
);

export type IOrderInsert = {
   orderId?: string;
   status?: udt.OrderStatusUdt;
   createdAt: Date;
   modifiedAt: Date;
   accountId: string;
};

export type IOrderUpdate = Partial<IOrderInsert>;

export type IOrderSelect = {
   readonly orderId: string;
   readonly status: udt.OrderStatusUdt;
   readonly createdAt: Date;
   readonly modifiedAt: Date;
   readonly accountId: string;
};

export type IOrderJson = JsonRow<IOrderSelect>;
