/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";

export const OrderItem = vexnor.newSqlTable<{
   Select: IOrderItemSelect;
   Insert: IOrderItemInsert;
   Update: IOrderItemUpdate;
   Delete: true;
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "order_item",
      schema: "main",
   },
   pk: ["orderId"],
   dialect: "sqlite",
   columns: {

      /**
       * order_id TEXT
       */
      orderId: "order_id",

      /**
       * product_id TEXT
       */
      productId: "product_id",

      /**
       * created_at TEXT default datetime('now')
       */
      createdAt: "created_at",

      /**
       * modified_at TEXT default datetime('now')
       */
      modifiedAt: "modified_at",

      /**
       * product_price REAL
       */
      productPrice: "product_price",

      /**
       * discount_price REAL
       */
      discountPrice: "discount_price",

      /**
       * quantity INTEGER
       */
      quantity: "quantity",

      /**
       * metadata TEXT
       */
      metadata: "metadata",
   },
});
export type IOrderItemInsert = {
   orderId: string;
   productId: string;
   createdAt?: string;
   modifiedAt?: string;
   productPrice: number;
   discountPrice?: number | null;
   quantity: number;
   metadata?: string | null;
};

export type IOrderItemUpdate = Partial<IOrderItemInsert>;

export type IOrderItemSelect = {
   orderId: string;
   productId: string;
   createdAt: string;
   modifiedAt: string;
   productPrice: number;
   discountPrice: number | null;
   quantity: number;
   metadata: string | null;
};

export type IOrderItemJson = vexnor.JsonRow<IOrderItemSelect>;