// noinspection SqlNoDataSourceInspection,SqlResolve
import {
   SqlTable,
   SqlSelectArgs,
   SqlUpdateArgs,
   SqlDeleteArgs,
   SqlInsertFromArgs,
} from "@vexnor/core";
import { postgresSelect, PostgresSelectResult } from "./postgres-select.js";
import { postgresInsertRows, PostgresInsertRowsResult } from "./postgres-insert-rows.js";
import { postgresInsertFrom, PostgresInsertFromResult } from "./postgres-insert-from.js";
import { postgresUpdate, PostgresTableUpdateResult } from "./postgres-update.js";
import { postgresDelete, PostgresDeleteResult } from "./postgres-delete.js";
import { postgresUpsert, PostgresUpsertArgs, PostgresUpsertResult } from "./postgres-upsert.js";

type SelectInsertTable<T> = Extract<T, { Select: Record<string, unknown>; Insert: Record<string, unknown> }>;
type SelectUpdateTable<T> = Extract<T, { Select: Record<string, unknown>; Update: Record<string, unknown> }>;
type SelectDeleteTable<T> = Extract<T, { Select: Record<string, unknown>; Delete: true }>;

/**
 * The set of typed query factories available on a PostgreSQL table handler.
 *
 * Generated by `newPostgresTableHandler()`. The available methods depend on
 * which CRUD operations are enabled in the table's `crud` config:
 *
 * - `select()` — available when `crud.select` is enabled
 * - `insertRows()` — available when `crud.insert` is enabled
 * - `insertFrom()` — available when `crud.insert` is enabled
 * - `update()` — available when `crud.update` is enabled
 * - `delete()` — available when `crud.delete` is enabled
 * - `upsert()` — available when `crud.insert` is enabled
 */
export type PostgresTableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
> = (T extends { Select: Record<string, unknown> }
   ? {
        select: <Args extends SqlSelectArgs<T & { Select: Record<string, unknown> }>>(
           args: Args,
        ) => PostgresSelectResult<T & { Select: Record<string, unknown> }, Args>;
     }
   : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           insertRows: () => PostgresInsertRowsResult<SelectInsertTable<T>>;
           insertFrom: <Args extends SqlInsertFromArgs<SelectInsertTable<T>>>(
              args: Args,
           ) => PostgresInsertFromResult<SelectInsertTable<T>, Args>;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Update: Record<string, unknown> }
      ? {
           update: <Args extends SqlUpdateArgs>(args: Args) => PostgresTableUpdateResult<SelectUpdateTable<T>, Args>;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Delete: true }
      ? {
           delete: <Args extends SqlDeleteArgs>(args: Args) => PostgresDeleteResult<SelectDeleteTable<T>, Args>;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           upsert: (args: PostgresUpsertArgs) => PostgresUpsertResult<SelectInsertTable<T>>;
        }
      : unknown);

/**
 * Creates a `PostgresTableHandler` for the given table, providing typed query
 * factories for all CRUD operations enabled in the table's `crud` config.
 *
 * Used in generated files. Call the returned methods to get executable query
 * objects — each method returns a `PostgresQueryHandler` ready for `.getAll()`,
 * `.getOneRequired()`, or `.getOneOptional()`.
 *
 * @param table - The generated table constant to create a handler for.
 *
 * @example
 * const AccountHandler = newPostgresTableHandler(Account);
 *
 * const accounts = await AccountHandler.select({ WHERE: sql`${Account.$active} = true` })
 *   .getAll({ db: pool });
 */
export function newPostgresTableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
>(table: SqlTable<T>): PostgresTableHandler<T> {
   const { select, insert, update, delete: delete$ } = table.crud;
   const handler: Record<string, unknown> = {};

   if (select) {
      handler.select = <Args extends SqlSelectArgs<T & { Select: Record<string, unknown> }>>(args: Args) =>
         postgresSelect(table as SqlTable<T & { Select: Record<string, unknown> }>, args);
   }
   if (insert) {
      handler.upsert = (args: PostgresUpsertArgs) =>
         postgresUpsert(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         );
      handler.insertRows = () =>
         postgresInsertRows(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
         );
      handler.insertFrom = <
         Args extends SqlInsertFromArgs<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
      >(
         args: Args,
      ) =>
         postgresInsertFrom(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         );
   }
   if (update) {
      handler.update = <Args extends SqlUpdateArgs>(args: Args) =>
         postgresUpdate(
            table as SqlTable<T & { Select: Record<string, unknown>; Update: Record<string, unknown> }>,
            args,
         );
   }
   if (delete$) {
      handler.delete = <Args extends SqlDeleteArgs>(args: Args) =>
         postgresDelete(table as SqlTable<T & { Select: Record<string, unknown>; Delete: true }>, args);
   }

   return handler as PostgresTableHandler<T>;
}
