// noinspection SqlNoDataSourceInspection,SqlResolve
import {
   SqlTable,
   SqlSelectArgs,
   SqlUpdateArgs,
   SqlDeleteArgs,
   SqlInsertFromArgs,
} from "@vexnor/core";
import { PostgresSelectCommand, PostgresSelectCommandResult } from "./postgres-select-command.js";
import { PostgresInsertRowsCommand, PostgresInsertRowsCommandResult } from "./postgres-insert-rows-command.js";
import { PostgresInsertFromCommand, PostgresInsertFromCommandResult } from "./postgres-insert-from-command.js";
import { PostgresUpdateCommand, PostgresUpdateCommandResult } from "./postgres-update-command.js";
import { PostgresDeleteCommand, PostgresDeleteCommandResult } from "./postgres-delete-command.js";
import { PostgresUpsertCommand, PostgresUpsertCommandArgs, PostgresUpsertCommandResult } from "./postgres-upsert-command.js";

type SelectInsertTable<T> = Extract<T, { Select: Record<string, unknown>; Insert: Record<string, unknown> }>;
type SelectUpdateTable<T> = Extract<T, { Select: Record<string, unknown>; Update: Record<string, unknown> }>;
type SelectDeleteTable<T> = Extract<T, { Select: Record<string, unknown>; Delete: true }>;

/**
 * The set of typed query factories available on a PostgreSQL table handler.
 *
 * Generated by `newPostgresTableHandler()`. The available methods depend on
 * which CRUD operations are enabled in the table's `crud` config:
 *
 * - `select()` — available when `crud.select` is enabled
 * - `insertRows()` — available when `crud.insert` is enabled
 * - `insertFrom()` — available when `crud.insert` is enabled
 * - `update()` — available when `crud.update` is enabled
 * - `delete()` — available when `crud.delete` is enabled
 * - `upsert()` — available when `crud.insert` is enabled
 */
export type PostgresTableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
> = (T extends { Select: Record<string, unknown> }
   ? {
        select: <Args extends SqlSelectArgs<T & { Select: Record<string, unknown> }>>(
           args: Args,
        ) => PostgresSelectCommandResult<T & { Select: Record<string, unknown> }, Args>;
     }
   : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           insertRows: () => PostgresInsertRowsCommandResult<SelectInsertTable<T>>;
           insertFrom: <Args extends SqlInsertFromArgs<SelectInsertTable<T>>>(
              args: Args,
           ) => PostgresInsertFromCommandResult<SelectInsertTable<T>, Args>;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Update: Record<string, unknown> }
      ? {
           update: <Args extends SqlUpdateArgs>(args: Args) => PostgresUpdateCommandResult<SelectUpdateTable<T>, Args>;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Delete: true }
      ? {
           delete: <Args extends SqlDeleteArgs>(args: Args) => PostgresDeleteCommandResult<SelectDeleteTable<T>, Args>;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           upsert: (args: PostgresUpsertCommandArgs) => PostgresUpsertCommandResult<SelectInsertTable<T>>;
        }
      : unknown);

/**
 * Creates a `PostgresTableHandler` for the given table, providing typed query
 * factories for all CRUD operations enabled in the table's `crud` config.
 *
 * Used in generated files. Call the returned methods to get executable query
 * objects — each method returns a `PostgresQueryHandler` ready for `.getAll()`,
 * `.getOneRequired()`, or `.getOneOptional()`.
 *
 * @param table - The generated table constant to create a handler for.
 *
 * @example
 * const AccountHandler = newPostgresTableHandler(Account);
 *
 * const accounts = await AccountHandler.select({ WHERE: sql`${Account.$active} = true` })
 *   .getAll({ db: pool });
 */
export function newPostgresTableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
>(table: SqlTable<T>): PostgresTableHandler<T> {
   const { select, insert, update, delete: delete$ } = table.crud;
   const handler: Record<string, unknown> = {};

   if (select) {
      handler.select = <Args extends SqlSelectArgs<T & { Select: Record<string, unknown> }>>(args: Args) =>
         new PostgresSelectCommand(table as SqlTable<T & { Select: Record<string, unknown> }>, args).execute();
   }
   if (insert) {
      handler.upsert = (args: PostgresUpsertCommandArgs) =>
         new PostgresUpsertCommand(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         ).execute();
      handler.insertRows = () =>
         new PostgresInsertRowsCommand(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
         ).execute();
      handler.insertFrom = <
         Args extends SqlInsertFromArgs<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
      >(
         args: Args,
      ) =>
         new PostgresInsertFromCommand(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         ).execute();
   }
   if (update) {
      handler.update = <Args extends SqlUpdateArgs>(args: Args) =>
         new PostgresUpdateCommand(
            table as SqlTable<T & { Select: Record<string, unknown>; Update: Record<string, unknown> }>,
            args,
         ).execute();
   }
   if (delete$) {
      handler.delete = <Args extends SqlDeleteArgs>(args: Args) =>
         new PostgresDeleteCommand(table as SqlTable<T & { Select: Record<string, unknown>; Delete: true }>, args).execute();
   }

   return handler as PostgresTableHandler<T>;
}
