/* File generated by Valnor. Do not edit. */
import * as valnor from "valnor";

export const Product = valnor.newSqlTable(
   {
      name: "product",
      schema: "valnor_test",
      types: <{ Select: IProductSelect; Insert: IProductInsert; Update: IProductUpdate }>{},
   },
   {
      /**
       * product_id uuid default gen_random_uuid()
       */
      productId: "product_id",

      /**
       * created_at timestamptz default now()
       */
      createdAt: "created_at",

      /**
       * modified_at timestamptz default now()
       */
      modifiedAt: "modified_at",

      /**
       * label varchar
       */
      label: "label",

      /**
       * price numeric
       */
      price: "price",

      /**
       * discount numeric
       */
      discount: "discount",

      /**
       * is_available bool default true
       */
      isAvailable: "is_available",

      /**
       * is_published bool default false
       */
      isPublished: "is_published",

      /**
       * metadata jsonb
       */
      metadata: "metadata",

      /**
       * tags _text
       */
      tags: "tags",
   },
);

export type IProductInsert = {
   productId?: string;
   createdAt?: Date;
   modifiedAt?: Date;
   label: string;
   price: number;
   discount?: number | null;
   isAvailable?: boolean;
   isPublished?: boolean;
   metadata?: string | null;
   tags?: unknown | null;
};

export type IProductUpdate = Partial<IProductInsert>;

export type IProductSelect = {
   readonly productId: string;
   readonly createdAt: Date;
   readonly modifiedAt: Date;
   readonly label: string;
   readonly price: number;
   readonly discount: number | null;
   readonly isAvailable: boolean;
   readonly isPublished: boolean;
   readonly metadata: string | null;
   readonly tags: unknown | null;
};

export type IProductJson = valnor.JsonRow<IProductSelect>;
