/* File generated by Valnor. Do not edit. */
import * as valnor from "valnor";
import * as udt from "./valnor_test-enums.js";

export const OrderItem = valnor.newSqlTable({
   name: "order_item",
   schema: "valnor_test",
   types: <{ Select: IOrderItemSelect, Insert: IOrderItemInsert, Update: IOrderItemUpdate }>{}, 
},{

   /**
    * order_id uuid
   */
   orderId: "order_id",

   /**
    * product_id uuid
   */
   productId: "product_id",

   /**
    * created_at timestamptz default now()
   */
   createdAt: "created_at",

   /**
    * modified_at timestamptz default now()
   */
   modifiedAt: "modified_at",

   /**
    * product_price numeric
   */
   productPrice: "product_price",

   /**
    * discount_price numeric
   */
   discountPrice: "discount_price",

   /**
    * quantity int4
   */
   quantity: "quantity",

   /**
    * metadata jsonb
   */
   metadata: "metadata",
});

export type IOrderItemInsert = {
   orderId: string;
   productId: string;
   createdAt?: Date;
   modifiedAt?: Date;
   productPrice: number;
   discountPrice?: number | null;
   quantity: number;
   metadata?: string | null;
}

export type IOrderItemUpdate = Partial<IOrderItemInsert>;

export type IOrderItemSelect = {
   readonly orderId: string
   readonly productId: string
   readonly createdAt: Date
   readonly modifiedAt: Date
   readonly productPrice: number
   readonly discountPrice: number | null
   readonly quantity: number
   readonly metadata: string | null
}

export type IOrderItemJson = valnor.JsonRow<IOrderItemSelect>;