/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";

export const OrderItem = vexnor.newSqlTable<{
   Select: IOrderItemSelect;
   Insert: IOrderItemInsert;
   Update: IOrderItemUpdate;
   Delete: true;
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "order_item",
      schema: "vexnor_dev",
   },
   pk: ["productId"],
   dialect: "tsql",
   source: "@vexnor/test-mssql:src/codegen",
   columns: {

      /**
       * order_id uniqueidentifier
       */
      orderId: "order_id",

      /**
       * product_id uniqueidentifier
       */
      productId: "product_id",

      /**
       * created_at datetimeoffset default (sysdatetimeoffset())
       */
      createdAt: "created_at",

      /**
       * modified_at datetimeoffset default (sysdatetimeoffset())
       */
      modifiedAt: "modified_at",

      /**
       * product_price decimal
       */
      productPrice: "product_price",

      /**
       * discount_price decimal
       */
      discountPrice: "discount_price",

      /**
       * quantity int
       */
      quantity: "quantity",

      /**
       * metadata nvarchar
       */
      metadata: "metadata",
   },
   jsonSchema: {
      createdAt: "Date",
      modifiedAt: "Date",
   },
   fk: [
      { from: ["orderId"], to: { schema: "vexnor_dev", table: "order", columns: ["orderId"] } },
      { from: ["productId"], to: { schema: "vexnor_dev", table: "product", columns: ["productId"] } },
   ],
   dbSchema: {
      orderId: { dbType: "uniqueidentifier", type: vexnor.SqlLiteralType.String },
      productId: { dbType: "uniqueidentifier", type: vexnor.SqlLiteralType.String },
      createdAt: { dbType: "datetimeoffset", type: vexnor.SqlLiteralType.Date, default: "(sysdatetimeoffset())" },
      modifiedAt: { dbType: "datetimeoffset", type: vexnor.SqlLiteralType.Date, default: "(sysdatetimeoffset())" },
      productPrice: { dbType: "decimal", type: vexnor.SqlLiteralType.Number },
      discountPrice: { dbType: "decimal", type: vexnor.SqlLiteralType.Number, nullable: true },
      quantity: { dbType: "int", type: vexnor.SqlLiteralType.Number },
      metadata: { dbType: "nvarchar", type: vexnor.SqlLiteralType.String, nullable: true },
   },
});
export type IOrderItemInsert = {
   orderId: string;
   productId: string;
   createdAt?: Date;
   modifiedAt?: Date;
   productPrice: number;
   discountPrice?: number | null;
   quantity: number;
   metadata?: string | null;
};

export type IOrderItemUpdate = Partial<IOrderItemInsert>;

export type IOrderItemSelect = {
   orderId: string;
   productId: string;
   createdAt: Date;
   modifiedAt: Date;
   productPrice: number;
   discountPrice: number | null;
   quantity: number;
   metadata: string | null;
};

export type IOrderItemJson = vexnor.JsonRow<IOrderItemSelect>;