/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";

export const Order = vexnor.newSqlTable<{
   Select: IOrderSelect;
   Insert: IOrderInsert;
   Update: IOrderUpdate;
   Delete: true;
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "order",
      schema: "vexnor_dev",
   },
   pk: ["orderId"],
   dialect: "tsql",
   source: "@vexnor/test-mssql:src/codegen",
   columns: {

      /**
       * order_id uniqueidentifier default (newid())
       */
      orderId: "order_id",

      /**
       * status varchar default ('created')
       */
      status: "status",

      /**
       * created_at datetimeoffset default (sysdatetimeoffset())
       */
      createdAt: "created_at",

      /**
       * modified_at datetimeoffset default (sysdatetimeoffset())
       */
      modifiedAt: "modified_at",

      /**
       * account_id uniqueidentifier
       */
      accountId: "account_id",
   },
   jsonSchema: {
      createdAt: "Date",
      modifiedAt: "Date",
   },
   fk: [
      { from: ["accountId"], to: { schema: "vexnor_dev", table: "account", columns: ["accountId"] } },
   ],
   dbSchema: {
      orderId: { dbType: "uniqueidentifier", type: vexnor.SqlLiteralType.String, default: "(newid())" },
      status: { dbType: "varchar", type: vexnor.SqlLiteralType.String, default: "('created')" },
      createdAt: { dbType: "datetimeoffset", type: vexnor.SqlLiteralType.Date, default: "(sysdatetimeoffset())" },
      modifiedAt: { dbType: "datetimeoffset", type: vexnor.SqlLiteralType.Date, default: "(sysdatetimeoffset())" },
      accountId: { dbType: "uniqueidentifier", type: vexnor.SqlLiteralType.String },
   },
});
export type IOrderInsert = {
   orderId?: string;
   status?: string;
   createdAt?: Date;
   modifiedAt?: Date;
   accountId: string;
};

export type IOrderUpdate = Partial<IOrderInsert>;

export type IOrderSelect = {
   orderId: string;
   status: string;
   createdAt: Date;
   modifiedAt: Date;
   accountId: string;
};

export type IOrderJson = vexnor.JsonRow<IOrderSelect>;