/*
 File generated by Vexnor. Do not edit!
*/
import * as vexnor from "@vexnor/core";


export const OrderItem = vexnor.newSqlTable<{
   Select: IOrderItemSelect;
   Insert: IOrderItemInsert;
   Update: IOrderItemUpdate;
   Delete: true;
   Source: "@vexnor/test-duckdb:src/codegen";
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "order_item",
      schema: "main",
   },
   pk: ["orderId","productId"],
   dialect: "duckdb",
   source: "@vexnor/test-duckdb:src/codegen",
   columns: {

      /**
       * order_id undefined
       */
      orderId: "order_id",

      /**
       * product_id undefined
       */
      productId: "product_id",

      /**
       * created_at undefined default current_timestamp
       */
      createdAt: "created_at",

      /**
       * modified_at undefined default current_timestamp
       */
      modifiedAt: "modified_at",

      /**
       * product_price undefined
       */
      productPrice: "product_price",

      /**
       * discount_price undefined
       */
      discountPrice: "discount_price",

      /**
       * quantity undefined
       */
      quantity: "quantity",

      /**
       * metadata undefined
       */
      metadata: "metadata",
   },
   jsonSchema: {
      createdAt: "Date",
      modifiedAt: "Date",
   },
   fk: [
      { from: ["orderId"], to: { schema: "main", table: "order", columns: ["orderId"] } },
      { from: ["productId"], to: { schema: "main", table: "product", columns: ["productId"] } },
   ],
   dbSchema: {
      orderId: { dbType: "UUID", type: vexnor.SqlLiteralType.String },
      productId: { dbType: "UUID", type: vexnor.SqlLiteralType.String },
      createdAt: { dbType: "TIMESTAMP WITH TIME ZONE", type: vexnor.SqlLiteralType.Date, default: "current_timestamp" },
      modifiedAt: { dbType: "TIMESTAMP WITH TIME ZONE", type: vexnor.SqlLiteralType.Date, default: "current_timestamp" },
      productPrice: { dbType: "DECIMAL(18,2)", type: vexnor.SqlLiteralType.String },
      discountPrice: { dbType: "DECIMAL(18,2)", type: vexnor.SqlLiteralType.String, nullable: true },
      quantity: { dbType: "INTEGER", type: vexnor.SqlLiteralType.Number },
      metadata: { dbType: "JSON", type: vexnor.SqlLiteralType.Json, nullable: true },
   },
});
export type IOrderItemInsert = {
   orderId: string;
   productId: string;
   createdAt?: Date;
   modifiedAt?: Date;
   productPrice: string;
   discountPrice?: string | null;
   quantity: number;
   metadata?: unknown | null;
};

export type IOrderItemUpdate = Partial<IOrderItemInsert>;

export type IOrderItemSelect = {
   orderId: string;
   productId: string;
   createdAt: Date;
   modifiedAt: Date;
   productPrice: string;
   discountPrice: string | null;
   quantity: number;
   metadata: unknown | null;
};

export type IOrderItemJson = vexnor.JsonRow<IOrderItemSelect>;