/*
 File generated by Vexnor. Do not edit!
*/
import * as vexnor from "@vexnor/core";


export const Product = vexnor.newSqlTable<{
   Select: IProductSelect;
   Insert: IProductInsert;
   Update: IProductUpdate;
   Delete: true;
   Source: "@vexnor/test-duckdb:src/codegen";
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "product",
      schema: "main",
   },
   pk: ["productId"],
   dialect: "duckdb",
   source: "@vexnor/test-duckdb:src/codegen",
   columns: {

      /**
       * product_id UUID default uuid()
       */
      productId: "product_id",

      /**
       * created_at TIMESTAMP WITH TIME ZONE default current_timestamp
       */
      createdAt: "created_at",

      /**
       * modified_at TIMESTAMP WITH TIME ZONE default current_timestamp
       */
      modifiedAt: "modified_at",

      /**
       * label VARCHAR
       */
      label: "label",

      /**
       * price DECIMAL(18,2)
       */
      price: "price",

      /**
       * discount DECIMAL(18,2)
       */
      discount: "discount",

      /**
       * is_available BOOLEAN default CAST('t' AS BOOLEAN)
       */
      isAvailable: "is_available",

      /**
       * is_published BOOLEAN default CAST('f' AS BOOLEAN)
       */
      isPublished: "is_published",

      /**
       * metadata JSON
       */
      metadata: "metadata",

      /**
       * tags VARCHAR[]
       */
      tags: "tags",
   },
   jsonSchema: {
      createdAt: "Date",
      modifiedAt: "Date",
   },
   dbSchema: {
      productId: { dbType: "UUID", type: vexnor.SqlLiteralType.String, default: "uuid()" },
      createdAt: { dbType: "TIMESTAMP WITH TIME ZONE", type: vexnor.SqlLiteralType.Date, default: "current_timestamp" },
      modifiedAt: { dbType: "TIMESTAMP WITH TIME ZONE", type: vexnor.SqlLiteralType.Date, default: "current_timestamp" },
      label: { dbType: "VARCHAR", type: vexnor.SqlLiteralType.String },
      price: { dbType: "DECIMAL(18,2)", type: vexnor.SqlLiteralType.String },
      discount: { dbType: "DECIMAL(18,2)", type: vexnor.SqlLiteralType.String, nullable: true },
      isAvailable: { dbType: "BOOLEAN", type: vexnor.SqlLiteralType.Boolean, default: "CAST('t' AS BOOLEAN)" },
      isPublished: { dbType: "BOOLEAN", type: vexnor.SqlLiteralType.Boolean, default: "CAST('f' AS BOOLEAN)" },
      metadata: { dbType: "JSON", type: vexnor.SqlLiteralType.Json, nullable: true },
      tags: {
         dbType: "VARCHAR[]",
         type: vexnor.SqlLiteralType.Json,
         nullable: true,
         structure: {
            kind: "list",
            value: null,
         },
      },
   },
});
export type IProductInsert = {
   productId?: string;
   createdAt?: Date;
   modifiedAt?: Date;
   label: string;
   price: string;
   discount?: string | null;
   isAvailable?: boolean;
   isPublished?: boolean;
   metadata?: unknown | null;
   tags?: Array<string | null> | null;
};

export type IProductUpdate = Partial<IProductInsert>;

export type IProductSelect = {
   productId: string;
   createdAt: Date;
   modifiedAt: Date;
   label: string;
   price: string;
   discount: string | null;
   isAvailable: boolean;
   isPublished: boolean;
   metadata: unknown | null;
   tags: Array<string | null> | null;
};

export type IProductJson = vexnor.JsonRow<IProductSelect>;