/*
 File generated by Vexnor. Do not edit!
*/
import * as vexnor from "@vexnor/core";
import * as udt from "./main-enums.js";

export const AccountOrderSummary = vexnor.newSqlTable<{
   Select: IAccountOrderSummarySelect;
   Source: "@vexnor/test-duckdb:src/codegen";
}>( {
   crud: {
      select: true,
      insert: false,
      update: false,
      delete: false,
   },
   tableInfo: {
      name: "account_order_summary",
      schema: "main",
   },
   pk: [],
   dialect: "duckdb",
   source: "@vexnor/test-duckdb:src/codegen",
   columns: {

      /**
       * account_id UUID
       */
      accountId: "account_id",

      /**
       * email VARCHAR
       */
      email: "email",

      /**
       * first_name VARCHAR
       */
      firstName: "first_name",

      /**
       * last_name VARCHAR
       */
      lastName: "last_name",

      /**
       * status account_status
       */
      status: "status",

      /**
       * order_count BIGINT
       */
      orderCount: "order_count",

      /**
       * latest_order_at TIMESTAMP WITH TIME ZONE
       */
      latestOrderAt: "latest_order_at",
   },
   jsonSchema: {
      latestOrderAt: "Date",
   },
   dbSchema: {
      accountId: { dbType: "UUID", type: vexnor.SqlLiteralType.String, nullable: true },
      email: { dbType: "VARCHAR", type: vexnor.SqlLiteralType.String, nullable: true },
      firstName: { dbType: "VARCHAR", type: vexnor.SqlLiteralType.String, nullable: true },
      lastName: { dbType: "VARCHAR", type: vexnor.SqlLiteralType.String, nullable: true },
      status: { dbType: "account_status", type: vexnor.SqlLiteralType.Udt, nullable: true, values: ["created", "confirmed", "deleted"] },
      orderCount: { dbType: "BIGINT", type: vexnor.SqlLiteralType.BigInt, nullable: true },
      latestOrderAt: { dbType: "TIMESTAMP WITH TIME ZONE", type: vexnor.SqlLiteralType.Date, nullable: true },
   },
});
export type IAccountOrderSummarySelect = {
   accountId: string | null;
   email: string | null;
   firstName: string | null;
   lastName: string | null;
   status: udt.AccountStatusUdt | null;
   orderCount: BigInt | null;
   latestOrderAt: Date | null;
};

export type IAccountOrderSummaryJson = vexnor.JsonRow<IAccountOrderSummarySelect>;