/* File generated by Valnor. Do not edit. */
import * as lib from "valnor";

export const OrderItem = lib.newTable({
   name: "order_item",
   schema: "one_sql",
   types: <{ Insert: IOrderItemInsert, Update: IOrderItemUpdate }>{}, 
   pk: "order_item_pk", 
},{

   /**
    * product_price numeric
   */
   productPrice: "product_price",

   /**
    * order_item_id uuid default gen_random_uuid()
   */
   orderItemId: "order_item_id",

   /**
    * quantity int4
   */
   quantity: "quantity",

   /**
    * discount_price numeric
   */
   discountPrice: "discount_price",

   /**
    * modified_at timestamptz
   */
   modifiedAt: "modified_at",

   /**
    * created_at timestamptz
   */
   createdAt: "created_at",

   /**
    * order_id uuid
   */
   orderId: "order_id",

   /**
    * product_id uuid
   */
   productId: "product_id",
});

export type IOrderItemInsert = {
   productPrice: string;
   orderItemId?: string;
   quantity: number;
   discountPrice?: string | null;
   modifiedAt: Date;
   createdAt: Date;
   orderId: string;
   productId: string;
}

export type IOrderItemUpdate = Partial<IOrderItemInsert>;

export type IOrderItemSelect = {
   readonly productPrice: string
   readonly orderItemId: string
   readonly quantity: number
   readonly discountPrice: string | null
   readonly modifiedAt: Date
   readonly createdAt: Date
   readonly orderId: string
   readonly productId: string
}

export type IOrderItemJson = lib.JsonRow<IOrderItemSelect>;