/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";

export const OrderItem = vexnor.newSqlTable<{
   Select: IOrderItemSelect;
   Insert: IOrderItemInsert;
   Update: IOrderItemUpdate;
   Delete: true;
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "order_item",
      schema: "main",
   },
   pk: ["orderId"],
   dialect: "sqlite",
   source: "@vexnor/stack-fixtures:codegen/sqlite3",
   columns: {

      /**
       * order_id TEXT
       */
      orderId: "order_id",

      /**
       * product_id TEXT
       */
      productId: "product_id",

      /**
       * created_at TEXT default datetime('now')
       */
      createdAt: "created_at",

      /**
       * modified_at TEXT default datetime('now')
       */
      modifiedAt: "modified_at",

      /**
       * product_price REAL
       */
      productPrice: "product_price",

      /**
       * discount_price REAL
       */
      discountPrice: "discount_price",

      /**
       * quantity INTEGER
       */
      quantity: "quantity",

      /**
       * metadata TEXT
       */
      metadata: "metadata",
   },
   fk: [
      { from: ["productId"], to: { schema: "main", table: "product", columns: ["productId"] } },
      { from: ["orderId"], to: { schema: "main", table: "order", columns: ["orderId"] } },
   ],
   dbSchema: {
      orderId: { dbType: "TEXT", type: vexnor.SqlLiteralType.String },
      productId: { dbType: "TEXT", type: vexnor.SqlLiteralType.String },
      createdAt: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, default: "datetime('now')" },
      modifiedAt: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, default: "datetime('now')" },
      productPrice: { dbType: "REAL", type: vexnor.SqlLiteralType.Number },
      discountPrice: { dbType: "REAL", type: vexnor.SqlLiteralType.Number, nullable: true },
      quantity: { dbType: "INTEGER", type: vexnor.SqlLiteralType.Number },
      metadata: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, nullable: true },
   },
});
export type IOrderItemInsert = {
   orderId: string;
   productId: string;
   createdAt?: string;
   modifiedAt?: string;
   productPrice: number;
   discountPrice?: number | null;
   quantity: number;
   metadata?: string | null;
};

export type IOrderItemUpdate = Partial<IOrderItemInsert>;

export type IOrderItemSelect = {
   orderId: string;
   productId: string;
   createdAt: string;
   modifiedAt: string;
   productPrice: number;
   discountPrice: number | null;
   quantity: number;
   metadata: string | null;
};

export type IOrderItemJson = vexnor.JsonRow<IOrderItemSelect>;