/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";

export const Order = vexnor.newSqlTable<{
   Select: IOrderSelect;
   Insert: IOrderInsert;
   Update: IOrderUpdate;
   Delete: true;
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "order",
      schema: "main",
   },
   pk: ["orderId"],
   dialect: "sqlite",
   source: "@vexnor/stack-fixtures:codegen/sqlite3",
   columns: {

      /**
       * order_id TEXT default lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))
       */
      orderId: "order_id",

      /**
       * status TEXT default 'created'
       */
      status: "status",

      /**
       * created_at TEXT default datetime('now')
       */
      createdAt: "created_at",

      /**
       * modified_at TEXT default datetime('now')
       */
      modifiedAt: "modified_at",

      /**
       * account_id TEXT
       */
      accountId: "account_id",
   },
   fk: [
      { from: ["accountId"], to: { schema: "main", table: "account", columns: ["accountId"] } },
   ],
   dbSchema: {
      orderId: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, nullable: true, default: "lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))" },
      status: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, default: "'created'" },
      createdAt: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, default: "datetime('now')" },
      modifiedAt: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, default: "datetime('now')" },
      accountId: { dbType: "TEXT", type: vexnor.SqlLiteralType.String },
   },
});
export type IOrderInsert = {
   orderId?: string | null;
   status?: string;
   createdAt?: string;
   modifiedAt?: string;
   accountId: string;
};

export type IOrderUpdate = Partial<IOrderInsert>;

export type IOrderSelect = {
   orderId: string | null;
   status: string;
   createdAt: string;
   modifiedAt: string;
   accountId: string;
};

export type IOrderJson = vexnor.JsonRow<IOrderSelect>;