/* File generated by Valnor. Do not edit. */
import * as valnor from "valnor";

export const Product = valnor.newSqlTable({
   name: "product",
   schema: "main",
   types: <{ Select: IProductSelect, Insert: IProductInsert, Update: IProductUpdate }>{}, 
   pk: "product_id", 
},{

   /**
    * product_id TEXT default lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))
   */
   productId: "product_id",

   /**
    * created_at TEXT default datetime('now')
   */
   createdAt: "created_at",

   /**
    * modified_at TEXT default datetime('now')
   */
   modifiedAt: "modified_at",

   /**
    * label TEXT
   */
   label: "label",

   /**
    * price REAL
   */
   price: "price",

   /**
    * discount REAL
   */
   discount: "discount",

   /**
    * is_available INTEGER default 1
   */
   isAvailable: "is_available",

   /**
    * is_published INTEGER default 0
   */
   isPublished: "is_published",
});

export type IProductInsert = {
   productId?: string | null;
   createdAt?: string;
   modifiedAt?: string;
   label: string;
   price: number;
   discount?: number | null;
   isAvailable?: number;
   isPublished?: number;
}

export type IProductUpdate = Partial<IProductInsert>;

export type IProductSelect = {
   readonly productId: string | null
   readonly createdAt: string
   readonly modifiedAt: string
   readonly label: string
   readonly price: number
   readonly discount: number | null
   readonly isAvailable: number
   readonly isPublished: number
}

export type IProductJson = valnor.JsonRow<IProductSelect>;