/* File generated by Valnor. Do not edit. */
import * as lib from "valnor";

export const MigrationOneSql = lib.newSqlTable(
   {
      name: "migration_one_sql",
      schema: "main",
      types: <{ Insert: IMigrationOneSqlInsert; Update: IMigrationOneSqlUpdate }>{},
      pk: "version",
   },
   {
      /**
       * version INTEGER
       */
      version: "version",

      /**
       * name TEXT
       */
      name: "name",

      /**
       * md5 TEXT
       */
      md5: "md5",

      /**
       * run_at TIMESTAMP WITH TIME ZONE
       */
      runAt: "run_at",
   },
);

export type IMigrationOneSqlInsert = {
   version?: number | null;
   name?: string | null;
   md5?: string | null;
   runAt?: Date | null;
};

export type IMigrationOneSqlUpdate = Partial<IMigrationOneSqlInsert>;

export type IMigrationOneSqlSelect = {
   readonly version: number | null;
   readonly name: string | null;
   readonly md5: string | null;
   readonly runAt: Date | null;
};

export type IMigrationOneSqlJson = lib.JsonRow<IMigrationOneSqlSelect>;
