/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";

export const Product = vexnor.newSqlTable<{
   Select: IProductSelect;
   Insert: IProductInsert;
   Update: IProductUpdate;
   Delete: true;
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "product",
      schema: "vexnor_dev",
   },
   pk: ["productId"],
   dialect: "tsql",
   source: "@vexnor/example-react-next-app:shared/codegen/mssql",
   columns: {

      /**
       * product_id uniqueidentifier default (newid())
       */
      productId: "product_id",

      /**
       * created_at datetimeoffset default (sysdatetimeoffset())
       */
      createdAt: "created_at",

      /**
       * modified_at datetimeoffset default (sysdatetimeoffset())
       */
      modifiedAt: "modified_at",

      /**
       * label varchar
       */
      label: "label",

      /**
       * price decimal
       */
      price: "price",

      /**
       * discount decimal
       */
      discount: "discount",

      /**
       * is_available bit default ((1))
       */
      isAvailable: "is_available",

      /**
       * is_published bit default ((0))
       */
      isPublished: "is_published",

      /**
       * metadata nvarchar
       */
      metadata: "metadata",
   },
   jsonSchema: {
      createdAt: "Date",
      modifiedAt: "Date",
   },
   dbSchema: {
      productId: { dbType: "uniqueidentifier", type: vexnor.SqlLiteralType.String, default: "(newid())" },
      createdAt: { dbType: "datetimeoffset", type: vexnor.SqlLiteralType.Date, default: "(sysdatetimeoffset())" },
      modifiedAt: { dbType: "datetimeoffset", type: vexnor.SqlLiteralType.Date, default: "(sysdatetimeoffset())" },
      label: { dbType: "varchar", type: vexnor.SqlLiteralType.String },
      price: { dbType: "decimal", type: vexnor.SqlLiteralType.Number },
      discount: { dbType: "decimal", type: vexnor.SqlLiteralType.Number, nullable: true },
      isAvailable: { dbType: "bit", type: vexnor.SqlLiteralType.Boolean, default: "((1))" },
      isPublished: { dbType: "bit", type: vexnor.SqlLiteralType.Boolean, default: "((0))" },
      metadata: { dbType: "nvarchar", type: vexnor.SqlLiteralType.String, nullable: true },
   },
});
export type IProductInsert = {
   productId?: string;
   createdAt?: Date;
   modifiedAt?: Date;
   label: string;
   price: number;
   discount?: number | null;
   isAvailable?: boolean;
   isPublished?: boolean;
   metadata?: string | null;
};

export type IProductUpdate = Partial<IProductInsert>;

export type IProductSelect = {
   productId: string;
   createdAt: Date;
   modifiedAt: Date;
   label: string;
   price: number;
   discount: number | null;
   isAvailable: boolean;
   isPublished: boolean;
   metadata: string | null;
};

export type IProductJson = vexnor.JsonRow<IProductSelect>;