/* File generated by Vexnor. Do not edit. */
import { JsonRow } from "#/core/schema/schema-types.js";
import { newSqlTable } from "#/core/schema/sql-table.js";
import * as udt from "#/test/models/vexnor_dev-enums.js";

export const Order = newSqlTable<{ Select: IOrderSelect; Insert: IOrderInsert; Update: IOrderUpdate; Delete: true }>({
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: { name: "order", schema: "main", out: false, alias: null },
   pk: ["orderId"],
   columns: {
      /**
       * order_id uuid default gen_random_uuid()
       */
      orderId: "order_id",

      /**
       * status order_status default 'created'::one_sql.order_status
       */
      status: "status",

      /**
       * created_at timestamptz
       */
      createdAt: "created_at",

      /**
       * modified_at timestamptz
       */
      modifiedAt: "modified_at",

      /**
       * account_id uuid
       */
      accountId: "account_id",
   },
});

export type IOrderInsert = {
   orderId?: string;
   status?: udt.OrderStatusUdt;
   createdAt: Date;
   modifiedAt: Date;
   accountId: string;
};

export type IOrderUpdate = Partial<IOrderInsert>;

export type IOrderSelect = {
   orderId: string;
   status: udt.OrderStatusUdt;
   createdAt: Date;
   modifiedAt: Date;
   accountId: string;
};

export type IOrderJson = JsonRow<IOrderSelect>;
