/* File generated by Valnor. Do not edit. */
import * as valnor from "valnor";

export const Product = valnor.newSqlTable(
   {
      name: "product",
      schema: "valnor_test",
      types: <{ Select: IProductSelect; Insert: IProductInsert; Update: IProductUpdate }>{},
      pk: "product_id",
   },
   {
      /**
       * product_id uniqueidentifier default (newid())
       */
      productId: "product_id",

      /**
       * created_at datetimeoffset default (sysdatetimeoffset())
       */
      createdAt: "created_at",

      /**
       * modified_at datetimeoffset default (sysdatetimeoffset())
       */
      modifiedAt: "modified_at",

      /**
       * label varchar
       */
      label: "label",

      /**
       * price decimal
       */
      price: "price",

      /**
       * discount decimal
       */
      discount: "discount",

      /**
       * is_available bit default ((1))
       */
      isAvailable: "is_available",

      /**
       * is_published bit default ((0))
       */
      isPublished: "is_published",
   },
);

export type IProductInsert = {
   productId?: string;
   createdAt?: Date;
   modifiedAt?: Date;
   label: string;
   price: number;
   discount?: number | null;
   isAvailable?: boolean;
   isPublished?: boolean;
};

export type IProductUpdate = Partial<IProductInsert>;

export type IProductSelect = {
   readonly productId: string;
   readonly createdAt: Date;
   readonly modifiedAt: Date;
   readonly label: string;
   readonly price: number;
   readonly discount: number | null;
   readonly isAvailable: boolean;
   readonly isPublished: boolean;
};

export type IProductJson = valnor.JsonRow<IProductSelect>;
