/* File generated by Valnor. Do not edit. */
import * as valnor from "valnor";

export const Account = valnor.newSqlTable(
   {
      name: "account",
      schema: "valnor_test",
      types: <{ Select: IAccountSelect; Insert: IAccountInsert; Update: IAccountUpdate }>{},
      pk: "account_id",
   },
   {
      /**
       * account_id uniqueidentifier default (newid())
       */
      accountId: "account_id",

      /**
       * status varchar default ('created')
       */
      status: "status",

      /**
       * email varchar
       */
      email: "email",

      /**
       * first_name varchar
       */
      firstName: "first_name",

      /**
       * last_name varchar
       */
      lastName: "last_name",

      /**
       * notes varchar
       */
      notes: "notes",

      /**
       * created_at datetimeoffset default (sysdatetimeoffset())
       */
      createdAt: "created_at",

      /**
       * modified_at datetimeoffset default (sysdatetimeoffset())
       */
      modifiedAt: "modified_at",
   },
);

export type IAccountInsert = {
   accountId?: string;
   status?: string;
   email: string;
   firstName: string;
   lastName: string;
   notes?: string | null;
   createdAt?: Date;
   modifiedAt?: Date;
};

export type IAccountUpdate = Partial<IAccountInsert>;

export type IAccountSelect = {
   readonly accountId: string;
   readonly status: string;
   readonly email: string;
   readonly firstName: string;
   readonly lastName: string;
   readonly notes: string | null;
   readonly createdAt: Date;
   readonly modifiedAt: Date;
};

export type IAccountJson = valnor.JsonRow<IAccountSelect>;
