/* File generated by Valnor. Do not edit. */
import * as valnor from "valnor";

export const Order = valnor.newSqlTable(
   {
      name: "order",
      schema: "valnor_test",
      types: <{ Select: IOrderSelect; Insert: IOrderInsert; Update: IOrderUpdate }>{},
      pk: "order_id",
   },
   {
      /**
       * order_id uniqueidentifier default (newid())
       */
      orderId: "order_id",

      /**
       * status varchar default ('created')
       */
      status: "status",

      /**
       * created_at datetimeoffset default (sysdatetimeoffset())
       */
      createdAt: "created_at",

      /**
       * modified_at datetimeoffset default (sysdatetimeoffset())
       */
      modifiedAt: "modified_at",

      /**
       * account_id uniqueidentifier
       */
      accountId: "account_id",
   },
);

export type IOrderInsert = {
   orderId?: string;
   status?: string;
   createdAt?: Date;
   modifiedAt?: Date;
   accountId: string;
};

export type IOrderUpdate = Partial<IOrderInsert>;

export type IOrderSelect = {
   readonly orderId: string;
   readonly status: string;
   readonly createdAt: Date;
   readonly modifiedAt: Date;
   readonly accountId: string;
};

export type IOrderJson = valnor.JsonRow<IOrderSelect>;
