/*
 File generated by Valnor at: 2/25/2026, 11:18:35 AM
 Do not edit. 
*/
import * as valnor from "valnor";

export const Account = valnor.newSqlTable<{ Select: IAccountSelect, Insert: IAccountInsert, Update: IAccountUpdate }>({
   tableInfo:
   {
      name: "account",
      schema: "valnor_test",
   },
   pk: ["accountId"], 
   columns:
   {

      /**
       * account_id uniqueidentifier default (newid())
      */
      accountId: "account_id",

      /**
       * parent_id uniqueidentifier
      */
      parentId: "parent_id",

      /**
       * status varchar default ('created')
      */
      status: "status",

      /**
       * email varchar
      */
      email: "email",

      /**
       * first_name varchar
      */
      firstName: "first_name",

      /**
       * last_name varchar
      */
      lastName: "last_name",

      /**
       * notes varchar
      */
      notes: "notes",

      /**
       * created_at datetimeoffset default (sysdatetimeoffset())
      */
      createdAt: "created_at",

      /**
       * modified_at datetimeoffset default (sysdatetimeoffset())
      */
      modifiedAt: "modified_at",
   }
});

export type IAccountInsert = {
   accountId?: string;
   parentId?: string | null;
   status?: string;
   email: string;
   firstName: string;
   lastName: string;
   notes?: string | null;
   createdAt?: Date;
   modifiedAt?: Date;
}

export type IAccountUpdate = Partial<IAccountInsert>;

export type IAccountSelect = {
   accountId: string
   parentId: string | null
   status: string
   email: string
   firstName: string
   lastName: string
   notes: string | null
   createdAt: Date
   modifiedAt: Date
}

export type IAccountJson = valnor.JsonRow<IAccountSelect>;