/*
 File generated by Valnor at: 2/25/2026, 11:18:35 AM
 Do not edit. 
*/
import * as valnor from "valnor";

export const OrderItem = valnor.newSqlTable<{ Select: IOrderItemSelect, Insert: IOrderItemInsert, Update: IOrderItemUpdate }>({
   tableInfo:
   {
      name: "order_item",
      schema: "valnor_test",
   },
   pk: ["productId"], 
   columns:
   {

      /**
       * order_id uniqueidentifier
      */
      orderId: "order_id",

      /**
       * product_id uniqueidentifier
      */
      productId: "product_id",

      /**
       * created_at datetimeoffset default (sysdatetimeoffset())
      */
      createdAt: "created_at",

      /**
       * modified_at datetimeoffset default (sysdatetimeoffset())
      */
      modifiedAt: "modified_at",

      /**
       * product_price decimal
      */
      productPrice: "product_price",

      /**
       * discount_price decimal
      */
      discountPrice: "discount_price",

      /**
       * quantity int
      */
      quantity: "quantity",

      /**
       * metadata nvarchar
      */
      metadata: "metadata",
   }
});

export type IOrderItemInsert = {
   orderId: string;
   productId: string;
   createdAt?: Date;
   modifiedAt?: Date;
   productPrice: number;
   discountPrice?: number | null;
   quantity: number;
   metadata?: string | null;
}

export type IOrderItemUpdate = Partial<IOrderItemInsert>;

export type IOrderItemSelect = {
   orderId: string
   productId: string
   createdAt: Date
   modifiedAt: Date
   productPrice: number
   discountPrice: number | null
   quantity: number
   metadata: string | null
}

export type IOrderItemJson = valnor.JsonRow<IOrderItemSelect>;