/*
 File generated by Valnor at: 2/25/2026, 11:18:35 AM
 Do not edit. 
*/
import * as valnor from "valnor";

export const Order = valnor.newSqlTable<{ Select: IOrderSelect, Insert: IOrderInsert, Update: IOrderUpdate }>({
   tableInfo:
   {
      name: "order",
      schema: "valnor_test",
   },
   pk: ["orderId"], 
   columns:
   {

      /**
       * order_id uniqueidentifier default (newid())
      */
      orderId: "order_id",

      /**
       * status varchar default ('created')
      */
      status: "status",

      /**
       * created_at datetimeoffset default (sysdatetimeoffset())
      */
      createdAt: "created_at",

      /**
       * modified_at datetimeoffset default (sysdatetimeoffset())
      */
      modifiedAt: "modified_at",

      /**
       * account_id uniqueidentifier
      */
      accountId: "account_id",
   }
});

export type IOrderInsert = {
   orderId?: string;
   status?: string;
   createdAt?: Date;
   modifiedAt?: Date;
   accountId: string;
}

export type IOrderUpdate = Partial<IOrderInsert>;

export type IOrderSelect = {
   orderId: string
   status: string
   createdAt: Date
   modifiedAt: Date
   accountId: string
}

export type IOrderJson = valnor.JsonRow<IOrderSelect>;