/*
 File generated by Valnor. Do not edit! 
*/
import * as valnor from "valnor";

export const Product = valnor.newSqlTable<{ Select: IProductSelect, Insert: IProductInsert, Update: IProductUpdate }>({
   tableInfo:
   {
      name: "product",
      schema: "valnor_test",
   },
   pk: ["productId"], 
   columns:
   {

      /**
       * product_id uniqueidentifier default (newid())
      */
      productId: "product_id",

      /**
       * created_at datetimeoffset default (sysdatetimeoffset())
      */
      createdAt: "created_at",

      /**
       * modified_at datetimeoffset default (sysdatetimeoffset())
      */
      modifiedAt: "modified_at",

      /**
       * label varchar
      */
      label: "label",

      /**
       * price decimal
      */
      price: "price",

      /**
       * discount decimal
      */
      discount: "discount",

      /**
       * is_available bit default ((1))
      */
      isAvailable: "is_available",

      /**
       * is_published bit default ((0))
      */
      isPublished: "is_published",

      /**
       * metadata nvarchar
      */
      metadata: "metadata",
   }
});

export type IProductInsert = {
   productId?: string;
   createdAt?: Date;
   modifiedAt?: Date;
   label: string;
   price: number;
   discount?: number | null;
   isAvailable?: boolean;
   isPublished?: boolean;
   metadata?: string | null;
}

export type IProductUpdate = Partial<IProductInsert>;

export type IProductSelect = {
   productId: string
   createdAt: Date
   modifiedAt: Date
   label: string
   price: number
   discount: number | null
   isAvailable: boolean
   isPublished: boolean
   metadata: string | null
}

export type IProductJson = valnor.JsonRow<IProductSelect>;