// noinspection SqlNoDataSourceInspection,SqlResolve
import {
   SqlTable,
   SqlSelectArgs,
   SqlUpdateArgs,
   SqlDeleteArgs,
   SqlInsertFromArgs,
   Sql,
   expand,
   sql,
   raw,
   row,
   info,
} from "@vexnor/core";
import { ok } from "@vexnor/core";
import { sqlite3Select, Sqlite3SelectResult } from "./sqlite3-select.js";
import { sqlite3InsertRows, Sqlite3InsertRowsResult } from "./sqlite3-insert-rows.js";
import { sqlite3InsertFrom, Sqlite3InsertFromResult } from "./sqlite3-insert-from.js";
import { sqlite3Update, Sqlite3TableUpdateResult } from "./sqlite3-update.js";
import { sqlite3Delete, Sqlite3DeleteResult } from "./sqlite3-delete.js";
import { sqlite3Upsert, Sqlite3UpsertArgs, Sqlite3UpsertResult } from "./sqlite3-upsert.js";
import { BetterSqlite3QueryHandler } from "#/better-sqlite3-query-handler.js";

type PkFields<T extends { Select: Record<string, unknown> }> = Pick<
   T["Select"],
   Extract<keyof T["Select"], T extends { pk: ReadonlyArray<infer K> } ? K : never>
>;

/**
 * The set of typed query factories available on a SQLite table handler.
 *
 * Generated by `newSqlite3TableHandler()`. The available methods depend on
 * which CRUD operations are enabled in the table's `crud` config:
 *
 * - `findById()` — always available; returns a query parameterized by primary key fields
 * - `findBy()` — always available; returns a query parameterized by any subset of columns
 * - `select()` — available when `crud.select` is enabled
 * - `insertRows()` — available when `crud.insert` is enabled
 * - `insertFrom()` — available when `crud.insert` is enabled
 * - `update()` — available when `crud.update` is enabled
 * - `delete()` — available when `crud.delete` is enabled
 * - `upsert()` — available when `crud.insert` is enabled
 */
export type Sqlite3TableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
> = (T extends { Select: Record<string, unknown> }
   ? {
        findById: () => BetterSqlite3QueryHandler<{ Params: PkFields<T> & Partial<T["Select"]>; Row: T["Select"] }>;
        findBy: () => BetterSqlite3QueryHandler<{ Params: Partial<T["Select"]>; Row: T["Select"] }>;
        select: <Args extends SqlSelectArgs>(
           args: Args,
        ) => Sqlite3SelectResult<T & { Select: Record<string, unknown> }, Args>;
     }
   : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           insertRows: () => Sqlite3InsertRowsResult<
              T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }
           >;
           insertFrom: <
              Args extends SqlInsertFromArgs<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
           >(
              args: Args,
           ) => Sqlite3InsertFromResult<
              T & { Select: Record<string, unknown>; Insert: Record<string, unknown> },
              Args
           >;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Update: Record<string, unknown> }
      ? {
           update: <Args extends SqlUpdateArgs>(
              args: Args,
           ) => Sqlite3TableUpdateResult<
              T & { Select: Record<string, unknown>; Update: Record<string, unknown> },
              Args
           >;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Delete: true }
      ? {
           delete: <Args extends SqlDeleteArgs>(
              args: Args,
           ) => Sqlite3DeleteResult<T & { Select: Record<string, unknown>; Delete: true }, Args>;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           upsert: (
              args: Sqlite3UpsertArgs,
           ) => Sqlite3UpsertResult<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>;
        }
      : unknown);

function buildFindByExpand<T extends { Select: Record<string, unknown> }>(
   table: SqlTable<T>,
   fields: Partial<T["Select"]>,
) {
   const cols = table.cols;
   const pairs: Sql[] = [];
   for (const [key, value] of Object.entries(fields)) {
      if (value === undefined) continue;
      const col = cols[`$${key}` as `$${string}`];
      ok(col, `Column not found: ${key}`);
      pairs.push(sql`${col} = ${value}`.inline());
   }
   if (!pairs.length) return raw.BLANK;
   return pairs.slice(1).reduce((acc, pair) => sql`${acc} and ${pair}`.inline(), pairs[0]!);
}

function sqlite3Find<T extends { Select: Record<string, unknown> }, Params extends Partial<T["Select"]>>(
   table: SqlTable<T>,
): BetterSqlite3QueryHandler<{ Params: Params; Row: T["Select"] }> {
   const whereExpand = expand<Params>(
      Object.fromEntries(Object.values(table.cols).map((col) => [col.key, null])) as Record<keyof Params, null>,
      (params) => {
         if (!params) return null;
         return buildFindByExpand(table, params as Partial<T["Select"]>) as ReturnType<typeof buildFindByExpand>;
      },
   );

   return sql`
      ${info({ driver: "sqlite" }) ?? raw.BLANK}
      select ${row(table.$$)}
      from ${table}
      ${sql`where ${whereExpand}`.inline("default")}
   `.sqlite as unknown as BetterSqlite3QueryHandler<{ Params: Params; Row: T["Select"] }>;
}

/**
 * Creates a `Sqlite3TableHandler` for the given table, providing typed query
 * factories for all CRUD operations enabled in the table's `crud` config.
 *
 * Used in generated files. Call the returned methods to get executable query
 * objects — each method returns a `BetterSqlite3QueryHandler` ready for `.getAll()`,
 * `.getOneRequired()`, or `.getOneOptional()`.
 *
 * @param table - The generated table constant to create a handler for.
 *
 * @example
 * const AccountHandler = newSqlite3TableHandler(Account);
 *
 * const account = await AccountHandler.findById()
 *   .getOneRequired({ db: database, params: { accountId: "123" } });
 *
 * const accounts = await AccountHandler.select({ WHERE: sql`${Account.$active} = 1` })
 *   .getAll({ db: database });
 */
export function newSqlite3TableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
>(table: SqlTable<T>): Sqlite3TableHandler<T> {
   const { select, insert, update, delete: delete$ } = table.crud;
   const handler: Record<string, unknown> = {};

   handler.findById = () => sqlite3Find<T, PkFields<T> & Partial<T["Select"]>>(table);
   handler.findBy = () => sqlite3Find<T, Partial<T["Select"]>>(table);

   if (select) {
      handler.select = <Args extends SqlSelectArgs>(args: Args) =>
         sqlite3Select(table as SqlTable<T & { Select: Record<string, unknown> }>, args);
   }
   if (insert) {
      handler.upsert = (args: Sqlite3UpsertArgs) =>
         sqlite3Upsert(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         );
      handler.insertRows = () =>
         sqlite3InsertRows(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
         );
      handler.insertFrom = <
         Args extends SqlInsertFromArgs<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
      >(
         args: Args,
      ) =>
         sqlite3InsertFrom(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         );
   }
   if (update) {
      handler.update = <Args extends SqlUpdateArgs>(args: Args) =>
         sqlite3Update(
            table as SqlTable<T & { Select: Record<string, unknown>; Update: Record<string, unknown> }>,
            args,
         );
   }
   if (delete$) {
      handler.delete = <Args extends SqlDeleteArgs>(args: Args) =>
         sqlite3Delete(table as SqlTable<T & { Select: Record<string, unknown>; Delete: true }>, args);
   }

   return handler as Sqlite3TableHandler<T>;
}
