import { writeTableType } from "./write-table-type.js";
import { writeTableInsert } from "./write-table-insert.js";
import { writeTableSelect } from "./write-table-select.js";
import { PrintTableArgs } from "../../../plugin/index.js";
import { getCodegenContext } from "../codegen-context.js";

export function writeTable({ table }: PrintTableArgs): string {
   const writer = getCodegenContext().newWriter();
   const { includeEnums } = getCodegenContext();
   const { table_schema } = table;
   writer.writeLine(`/*\n File generated by Valnor at: ${new Date().toLocaleString()}\n Do not edit. \n*/`);
   writer.writeLine(`import * as valnor from "valnor";`);
   if (includeEnums) {
      // writer.writeLine(`// eslint-disable-next-line @typescript-eslint/no-unused-vars`);
      writer.writeLine(`import * as udt from "./${table_schema}-enums.js";`);
   }

   writer.blankLine();

   writeTableType(writer, { table });
   writeTableInsert(writer, { table });
   writeTableSelect(writer, { table });
   return writer.toString();
}
