import { beforeEach, describe, expect, test, vi } from "vitest";
import { mkdir, readFile, rm } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { codegenCommand } from "#/cli/codegen/codegen-command.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
import { loadPlugin } from "#/load-plugin.js";
import { MockPlugin } from "#/test/mock-plugin.js";
import { SqlColumnInfo, SqlColumnType } from "#/plugin/plugin.js";
import { SqlLiteralType } from "#/plugin/sql-literal.js";
import { groupForeignKeys } from "#/cli/codegen/tables/write-table-type.js";

vi.mock("../../../../load-plugin.js", () => ({
   loadPlugin: vi.fn(),
}));

const COLUMN_TYPES: Record<string, SqlColumnType> = {
   order_id: { type: SqlLiteralType.String },
   account_id: { type: SqlLiteralType.String },
   product_id: { type: SqlLiteralType.String },
   quantity: { type: SqlLiteralType.Number },
   created_at: { type: SqlLiteralType.Date },
};

class FkTestPlugin extends MockPlugin {
   override dialect = "postgres";

   constructor() {
      super({ name: "vexnor-fk-test" });
   }

   override getColumnType(col: SqlColumnInfo): SqlColumnType {
      return COLUMN_TYPES[col.column_name] ?? { type: SqlLiteralType.String };
   }

   override getSchema() {
      return Promise.resolve({
         enums: [],
         tables: [
            {
               table_schema: "public",
               table_name: "order_item",
               table_type: "table" as const,
               primary_keys: [
                  { constraint_name: "pk_order_item", column_name: "order_id", table_schema: "public", table_name: "order_item" },
                  { constraint_name: "pk_order_item", column_name: "product_id", table_schema: "public", table_name: "order_item" },
               ],
               columns: [
                  { table_schema: "public", table_name: "order_item", column_name: "order_id", udt_name: "uuid", data_type: "uuid", is_nullable: "NO" as const, is_updatable: "YES" as const, column_default: null },
                  { table_schema: "public", table_name: "order_item", column_name: "product_id", udt_name: "uuid", data_type: "uuid", is_nullable: "NO" as const, is_updatable: "YES" as const, column_default: null },
                  { table_schema: "public", table_name: "order_item", column_name: "quantity", udt_name: "int4", data_type: "integer", is_nullable: "NO" as const, is_updatable: "YES" as const, column_default: "1" },
                  { table_schema: "public", table_name: "order_item", column_name: "created_at", udt_name: "timestamptz", data_type: "timestamp with time zone", is_nullable: "YES" as const, is_updatable: "YES" as const, column_default: "now()" },
               ],
               foreign_keys: [
                  { constraint_name: "fk_order_item_order", column_name: "order_id", table_schema: "public", table_name: "order_item", referenced_table_schema: "public", referenced_table_name: "order", referenced_column_name: "order_id" },
                  { constraint_name: "fk_order_item_product", column_name: "product_id", table_schema: "public", table_name: "order_item", referenced_table_schema: "inventory", referenced_table_name: "product", referenced_column_name: "product_id" },
               ],
            },
         ],
      });
   }
}

const testPlugin = new FkTestPlugin();

vi.mock("vexnor-fk-test", () => ({ default: testPlugin }));

describe("writeTableType fk and dbSchema", () => {
   beforeEach(() => {
      vi.mocked(loadPlugin).mockResolvedValue({ plugin: testPlugin, path: "vexnor-fk-test" });
   });

   test("emits fk and dbSchema in codegen output", async () => {
      const outDir = join(__dirname, ".tmp-fk-test");
      try {
         await mkdir(outDir, { recursive: true });
         await codegenCommand({
            plugin: "vexnor-fk-test",
            schema: ["public"],
            uri: "test://localhost",
            outDir,
            camelCaseColumns: true,
         });

         const content = await readFile(join(outDir, "public.order_item-table.ts"), "utf8");
         expect(content).toMatchInlineSnapshot(`
           "/*
            File generated by Vexnor. Do not edit! 
           */
           import * as vexnor from "@vexnor/core";

           export const OrderItem = vexnor.newSqlTable<{
              Select: IOrderItemSelect;
              Insert: IOrderItemInsert;
              Update: IOrderItemUpdate;
              Delete: true;
           }>( {
              crud: {
                 select: true,
                 insert: true,
                 update: true,
                 delete: true,
              },
              tableInfo: {
                 name: "order_item",
                 schema: "public",
              },
              pk: ["orderId","productId"],
              dialect: "postgres",
              source: "@vexnor/core:src/cli/codegen/tables/__tests__/.tmp-fk-test",
              columns: {

                 /**
                  * order_id uuid
                  */
                 orderId: "order_id",

                 /**
                  * product_id uuid
                  */
                 productId: "product_id",

                 /**
                  * quantity int4 default 1
                  */
                 quantity: "quantity",

                 /**
                  * created_at timestamptz default now()
                  */
                 createdAt: "created_at",
              },
              jsonSchema: {
                 createdAt: "Date",
              },
              fk: [
                 { from: ["orderId"], to: { schema: "public", table: "order", columns: ["orderId"] } },
                 { from: ["productId"], to: { schema: "inventory", table: "product", columns: ["productId"] } },
              ],
              dbSchema: {
                 orderId: { dbType: "uuid", type: vexnor.SqlLiteralType.String },
                 productId: { dbType: "uuid", type: vexnor.SqlLiteralType.String },
                 quantity: { dbType: "int4", type: vexnor.SqlLiteralType.Number, default: "1" },
                 createdAt: { dbType: "timestamptz", type: vexnor.SqlLiteralType.Date, nullable: true, default: "now()" },
              },
           });
           export type IOrderItemInsert = {
              orderId: string;
              productId: string;
              quantity?: number;
              createdAt?: Date | null;
           };

           export type IOrderItemUpdate = Partial<IOrderItemInsert>;

           export type IOrderItemSelect = {
              orderId: string;
              productId: string;
              quantity: number;
              createdAt: Date | null;
           };

           export type IOrderItemJson = vexnor.JsonRow<IOrderItemSelect>;"
         `);
      } finally {
         await rm(outDir, { recursive: true, force: true });
      }
   });
});

describe("groupForeignKeys", () => {
   test("groups multiple columns on the same constraint into one entry", () => {
      const result = groupForeignKeys(
         [
            { constraint_name: "fk_composite", column_name: "order_id", table_schema: "public", table_name: "audit", referenced_table_schema: "public", referenced_table_name: "order_item", referenced_column_name: "order_id" },
            { constraint_name: "fk_composite", column_name: "product_id", table_schema: "public", table_name: "audit", referenced_table_schema: "public", referenced_table_name: "order_item", referenced_column_name: "product_id" },
            { constraint_name: "fk_account", column_name: "account_id", table_schema: "public", table_name: "audit", referenced_table_schema: "public", referenced_table_name: "account", referenced_column_name: "account_id" },
         ],
         (name) => name.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase()),
      );

      expect(result).toMatchInlineSnapshot(`
        [
          {
            "from": [
              "orderId",
              "productId",
            ],
            "toColumns": [
              "orderId",
              "productId",
            ],
            "toSchema": "public",
            "toTable": "order_item",
          },
          {
            "from": [
              "accountId",
            ],
            "toColumns": [
              "accountId",
            ],
            "toSchema": "public",
            "toTable": "account",
          },
        ]
      `);
   });

   test("returns empty array when no foreign keys", () => {
      const result = groupForeignKeys([], (name) => name);
      expect(result).toMatchInlineSnapshot(`[]`);
   });
});

describe("writeTableType branch coverage", () => {
   beforeEach(() => {
      vi.mocked(loadPlugin).mockResolvedValue({ plugin: testPlugin, path: "vexnor-fk-test" });
   });

   test("does not emit fk for table with no foreign keys", async () => {
      const NoFkPlugin = class extends MockPlugin {
         override dialect = "postgres";
         constructor() { super({ name: "vexnor-fk-test" }); }
         override getColumnType() { return { type: SqlLiteralType.String } as SqlColumnType; }
         override getSchema() {
            return Promise.resolve({
               enums: [],
               tables: [
                  {
                     table_schema: "public",
                     table_name: "simple",
                     table_type: "table" as const,
                     primary_keys: [{ constraint_name: "pk", column_name: "id", table_schema: "public", table_name: "simple" }],
                     columns: [
                        { table_schema: "public", table_name: "simple", column_name: "id", udt_name: "uuid", data_type: "uuid", is_nullable: "NO" as const, is_updatable: "YES" as const, column_default: "gen_random_uuid()" },
                     ],
                     foreign_keys: [],
                  },
               ],
            });
         }
      };
      const noFkPlugin = new NoFkPlugin();
      vi.mocked(loadPlugin).mockResolvedValue({ plugin: noFkPlugin, path: "vexnor-fk-test" });

      const outDir = join(__dirname, ".tmp-no-fk-test");
      try {
         await mkdir(outDir, { recursive: true });
         await codegenCommand({ plugin: "vexnor-fk-test", schema: ["public"], uri: "test://localhost", outDir, camelCaseColumns: true });
         const content = await readFile(join(outDir, "public.simple-table.ts"), "utf8");
         expect(content).not.toContain("fk:");
         expect(content).toContain("dbSchema:");
      } finally {
         await rm(outDir, { recursive: true, force: true });
      }
   });

   test("does not emit fk for views but emits dbSchema", async () => {
      const ViewPlugin = class extends MockPlugin {
         override dialect = "postgres";
         constructor() { super({ name: "vexnor-fk-test" }); }
         override getColumnType() { return { type: SqlLiteralType.Number } as SqlColumnType; }
         override getSchema() {
            return Promise.resolve({
               enums: [],
               tables: [
                  {
                     table_schema: "public",
                     table_name: "summary",
                     table_type: "view" as const,
                     primary_keys: [],
                     columns: [
                        { table_schema: "public", table_name: "summary", column_name: "total", udt_name: "int4", data_type: "integer", is_nullable: "NO" as const, is_updatable: "NO" as const, column_default: null },
                     ],
                     foreign_keys: [],
                  },
               ],
            });
         }
      };
      const viewPlugin = new ViewPlugin();
      vi.mocked(loadPlugin).mockResolvedValue({ plugin: viewPlugin, path: "vexnor-fk-test" });

      const outDir = join(__dirname, ".tmp-view-test");
      try {
         await mkdir(outDir, { recursive: true });
         await codegenCommand({ plugin: "vexnor-fk-test", schema: ["public"], uri: "test://localhost", outDir, camelCaseColumns: true });
         const content = await readFile(join(outDir, "public.summary-view.ts"), "utf8");
         expect(content).not.toContain("fk:");
         expect(content).toContain("dbSchema:");
      } finally {
         await rm(outDir, { recursive: true, force: true });
      }
   });
});

describe("writeTableType — branch coverage for dbSchema", () => {
   beforeEach(() => {
      vi.mocked(loadPlugin).mockResolvedValue({ plugin: testPlugin, path: "vexnor-fk-test" });
   });

   test("emits Udt type without values when enum not found in enums list", async () => {
      const UdtPlugin = class extends MockPlugin {
         override dialect = "postgres";
         constructor() { super({ name: "vexnor-fk-test" }); }
         override getColumnType() { return { type: SqlLiteralType.Udt, udt: "nonexistent_enum" } as SqlColumnType; }
         override getSchema() {
            return Promise.resolve({
               enums: [],
               tables: [{
                  table_schema: "public", table_name: "t", table_type: "table" as const,
                  primary_keys: [{ constraint_name: "pk", column_name: "id", table_schema: "public", table_name: "t" }],
                  columns: [{ table_schema: "public", table_name: "t", column_name: "id", udt_name: "nonexistent_enum", data_type: "USER-DEFINED", is_nullable: "NO" as const, is_updatable: "YES" as const, column_default: null }],
                  foreign_keys: [],
               }],
            });
         }
      };
      vi.mocked(loadPlugin).mockResolvedValue({ plugin: new UdtPlugin(), path: "vexnor-fk-test" });

      const outDir = join(__dirname, ".tmp-udt-no-enum");
      try {
         await mkdir(outDir, { recursive: true });
         await codegenCommand({ plugin: "vexnor-fk-test", schema: ["public"], uri: "test://localhost", outDir, camelCaseColumns: true });
         const content = await readFile(join(outDir, "public.t-table.ts"), "utf8");
         expect(content).toContain("type: vexnor.SqlLiteralType.Udt");
         expect(content).not.toContain("values:");
      } finally {
         await rm(outDir, { recursive: true, force: true });
      }
   });

   test("emits nullable and default when column has both", async () => {
      const NullDefaultPlugin = class extends MockPlugin {
         override dialect = "postgres";
         constructor() { super({ name: "vexnor-fk-test" }); }
         override getColumnType() { return { type: SqlLiteralType.String } as SqlColumnType; }
         override getSchema() {
            return Promise.resolve({
               enums: [],
               tables: [{
                  table_schema: "public", table_name: "t", table_type: "table" as const,
                  primary_keys: [],
                  columns: [
                     { table_schema: "public", table_name: "t", column_name: "name", udt_name: "text", data_type: "text", is_nullable: "YES" as const, is_updatable: "YES" as const, column_default: "'unnamed'" },
                  ],
                  foreign_keys: [],
               }],
            });
         }
      };
      vi.mocked(loadPlugin).mockResolvedValue({ plugin: new NullDefaultPlugin(), path: "vexnor-fk-test" });

      const outDir = join(__dirname, ".tmp-nullable-default");
      try {
         await mkdir(outDir, { recursive: true });
         await codegenCommand({ plugin: "vexnor-fk-test", schema: ["public"], uri: "test://localhost", outDir, camelCaseColumns: true });
         const content = await readFile(join(outDir, "public.t-table.ts"), "utf8");
         expect(content).toContain("nullable: true");
         expect(content).toContain('default: "\'unnamed\'"');
      } finally {
         await rm(outDir, { recursive: true, force: true });
      }
   });
});
