/*
 File generated by Vexnor. Do not edit!
*/
import * as vexnor from "@vexnor/core";
import * as udt from "./main-enums.js";

export const Account = vexnor.newSqlTable<{
   Select: IAccountSelect;
   Insert: IAccountInsert;
   Update: IAccountUpdate;
   Delete: true;
   Source: "@vexnor/example-react-vite-api:shared/codegen/duckdb";
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "account",
      schema: "main",
   },
   pk: ["accountId"],
   dialect: "duckdb",
   source: "@vexnor/example-react-vite-api:shared/codegen/duckdb",
   columns: {

      /**
       * account_id UUID default uuid()
       */
      accountId: "account_id",

      /**
       * status account_status default 'created'
       */
      status: "status",

      /**
       * email VARCHAR
       */
      email: "email",

      /**
       * first_name VARCHAR
       */
      firstName: "first_name",

      /**
       * last_name VARCHAR
       */
      lastName: "last_name",

      /**
       * notes VARCHAR
       */
      notes: "notes",

      /**
       * created_at TIMESTAMP WITH TIME ZONE default current_timestamp
       */
      createdAt: "created_at",

      /**
       * modified_at TIMESTAMP WITH TIME ZONE default current_timestamp
       */
      modifiedAt: "modified_at",

      /**
       * parent_id UUID
       */
      parentId: "parent_id",
   },
   jsonSchema: {
      createdAt: "Date",
      modifiedAt: "Date",
   },
   fk: [
      { from: ["parentId"], to: { schema: "main", table: "account", columns: ["accountId"] } },
   ],
   dbSchema: {
      accountId: { dbType: "UUID", type: vexnor.SqlLiteralType.String, default: "uuid()" },
      status: { dbType: "account_status", type: vexnor.SqlLiteralType.Udt, default: "'created'", values: ["created", "confirmed", "deleted"] },
      email: { dbType: "VARCHAR", type: vexnor.SqlLiteralType.String },
      firstName: { dbType: "VARCHAR", type: vexnor.SqlLiteralType.String },
      lastName: { dbType: "VARCHAR", type: vexnor.SqlLiteralType.String },
      notes: { dbType: "VARCHAR", type: vexnor.SqlLiteralType.String, nullable: true },
      createdAt: { dbType: "TIMESTAMP WITH TIME ZONE", type: vexnor.SqlLiteralType.Date, default: "current_timestamp" },
      modifiedAt: { dbType: "TIMESTAMP WITH TIME ZONE", type: vexnor.SqlLiteralType.Date, default: "current_timestamp" },
      parentId: { dbType: "UUID", type: vexnor.SqlLiteralType.String, nullable: true },
   },
});
export type IAccountInsert = {
   accountId?: string;
   status?: udt.AccountStatusUdt;
   email: string;
   firstName: string;
   lastName: string;
   notes?: string | null;
   createdAt?: Date;
   modifiedAt?: Date;
   parentId?: string | null;
};

export type IAccountUpdate = Partial<IAccountInsert>;

export type IAccountSelect = {
   accountId: string;
   status: udt.AccountStatusUdt;
   email: string;
   firstName: string;
   lastName: string;
   notes: string | null;
   createdAt: Date;
   modifiedAt: Date;
   parentId: string | null;
};

export type IAccountJson = vexnor.JsonRow<IAccountSelect>;