/*
 File generated by Vexnor. Do not edit!
*/
import * as vexnor from "@vexnor/core";


export const TypeCoverage = vexnor.newSqlTable<{
   Select: ITypeCoverageSelect;
   Insert: ITypeCoverageInsert;
   Update: ITypeCoverageUpdate;
   Delete: true;
   Source: "@vexnor/example-react-vite-api:shared/codegen/duckdb";
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "type_coverage",
      schema: "main",
   },
   pk: ["colUuid"],
   dialect: "duckdb",
   source: "@vexnor/example-react-vite-api:shared/codegen/duckdb",
   columns: {

      /**
       * col_uuid UUID default uuid()
       */
      colUuid: "col_uuid",

      /**
       * col_boolean BOOLEAN
       */
      colBoolean: "col_boolean",

      /**
       * col_tinyint TINYINT
       */
      colTinyint: "col_tinyint",

      /**
       * col_smallint SMALLINT
       */
      colSmallint: "col_smallint",

      /**
       * col_integer INTEGER
       */
      colInteger: "col_integer",

      /**
       * col_bigint BIGINT
       */
      colBigint: "col_bigint",

      /**
       * col_hugeint HUGEINT
       */
      colHugeint: "col_hugeint",

      /**
       * col_utinyint UTINYINT
       */
      colUtinyint: "col_utinyint",

      /**
       * col_usmallint USMALLINT
       */
      colUsmallint: "col_usmallint",

      /**
       * col_uinteger UINTEGER
       */
      colUinteger: "col_uinteger",

      /**
       * col_ubigint UBIGINT
       */
      colUbigint: "col_ubigint",

      /**
       * col_uhugeint UHUGEINT
       */
      colUhugeint: "col_uhugeint",

      /**
       * col_real FLOAT
       */
      colReal: "col_real",

      /**
       * col_double DOUBLE
       */
      colDouble: "col_double",

      /**
       * col_decimal DECIMAL(18,4)
       */
      colDecimal: "col_decimal",

      /**
       * col_varchar VARCHAR
       */
      colVarchar: "col_varchar",

      /**
       * col_char VARCHAR
       */
      colChar: "col_char",

      /**
       * col_blob BLOB
       */
      colBlob: "col_blob",

      /**
       * col_bit BIT
       */
      colBit: "col_bit",

      /**
       * col_date DATE
       */
      colDate: "col_date",

      /**
       * col_time TIME
       */
      colTime: "col_time",

      /**
       * col_timestamp_s TIMESTAMP_S
       */
      colTimestampS: "col_timestamp_s",

      /**
       * col_timestamp_ms TIMESTAMP_MS
       */
      colTimestampMs: "col_timestamp_ms",

      /**
       * col_timestamp TIMESTAMP
       */
      colTimestamp: "col_timestamp",

      /**
       * col_timestamp_ns TIMESTAMP_NS
       */
      colTimestampNs: "col_timestamp_ns",

      /**
       * col_timestamptz TIMESTAMP WITH TIME ZONE
       */
      colTimestamptz: "col_timestamptz",

      /**
       * col_interval INTERVAL
       */
      colInterval: "col_interval",

      /**
       * col_json JSON
       */
      colJson: "col_json",

      /**
       * col_list INTEGER[]
       */
      colList: "col_list",

      /**
       * col_struct STRUCT("name" VARCHAR, score INTEGER)
       */
      colStruct: "col_struct",

      /**
       * col_map MAP(VARCHAR, INTEGER)
       */
      colMap: "col_map",
   },
   jsonSchema: {
      colDate: "Date",
      colTimestampS: "Date",
      colTimestampMs: "Date",
      colTimestamp: "Date",
      colTimestampNs: "Date",
      colTimestamptz: "Date",
   },
   dbSchema: {
      colUuid: { dbType: "UUID", type: vexnor.SqlLiteralType.String, default: "uuid()" },
      colBoolean: { dbType: "BOOLEAN", type: vexnor.SqlLiteralType.Boolean },
      colTinyint: { dbType: "TINYINT", type: vexnor.SqlLiteralType.Number },
      colSmallint: { dbType: "SMALLINT", type: vexnor.SqlLiteralType.Number },
      colInteger: { dbType: "INTEGER", type: vexnor.SqlLiteralType.Number },
      colBigint: { dbType: "BIGINT", type: vexnor.SqlLiteralType.BigInt },
      colHugeint: { dbType: "HUGEINT", type: vexnor.SqlLiteralType.BigInt },
      colUtinyint: { dbType: "UTINYINT", type: vexnor.SqlLiteralType.Number },
      colUsmallint: { dbType: "USMALLINT", type: vexnor.SqlLiteralType.Number },
      colUinteger: { dbType: "UINTEGER", type: vexnor.SqlLiteralType.Number },
      colUbigint: { dbType: "UBIGINT", type: vexnor.SqlLiteralType.BigInt },
      colUhugeint: { dbType: "UHUGEINT", type: vexnor.SqlLiteralType.BigInt },
      colReal: { dbType: "FLOAT", type: vexnor.SqlLiteralType.Number },
      colDouble: { dbType: "DOUBLE", type: vexnor.SqlLiteralType.Number },
      colDecimal: { dbType: "DECIMAL(18,4)", type: vexnor.SqlLiteralType.String },
      colVarchar: { dbType: "VARCHAR", type: vexnor.SqlLiteralType.String },
      colChar: { dbType: "VARCHAR", type: vexnor.SqlLiteralType.String },
      colBlob: { dbType: "BLOB", type: vexnor.SqlLiteralType.Buffer },
      colBit: { dbType: "BIT", type: vexnor.SqlLiteralType.String },
      colDate: { dbType: "DATE", type: vexnor.SqlLiteralType.Date },
      colTime: { dbType: "TIME", type: vexnor.SqlLiteralType.String },
      colTimestampS: { dbType: "TIMESTAMP_S", type: vexnor.SqlLiteralType.Date },
      colTimestampMs: { dbType: "TIMESTAMP_MS", type: vexnor.SqlLiteralType.Date },
      colTimestamp: { dbType: "TIMESTAMP", type: vexnor.SqlLiteralType.Date },
      colTimestampNs: { dbType: "TIMESTAMP_NS", type: vexnor.SqlLiteralType.Date },
      colTimestamptz: { dbType: "TIMESTAMP WITH TIME ZONE", type: vexnor.SqlLiteralType.Date },
      colInterval: { dbType: "INTERVAL", type: vexnor.SqlLiteralType.String },
      colJson: { dbType: "JSON", type: vexnor.SqlLiteralType.Json },
      colList: {
         dbType: "INTEGER[]",
         type: vexnor.SqlLiteralType.Json,
         structure: {
            kind: "list",
            value: null,
         },
      },
      colStruct: {
         dbType: "STRUCT(\"name\" VARCHAR, score INTEGER)",
         type: vexnor.SqlLiteralType.Json,
         structure: {
            kind: "struct",
            fields: {
               name: {
                  fieldName: "name",
               },
               score: {
                  fieldName: "score",
               },
            },
         },
      },
      colMap: { dbType: "MAP(VARCHAR, INTEGER)", type: vexnor.SqlLiteralType.Json },
   },
});
export type ITypeCoverageInsert = {
   colUuid?: string;
   colBoolean: boolean;
   colTinyint: number;
   colSmallint: number;
   colInteger: number;
   colBigint: BigInt;
   colHugeint: BigInt;
   colUtinyint: number;
   colUsmallint: number;
   colUinteger: number;
   colUbigint: BigInt;
   colUhugeint: BigInt;
   colReal: number;
   colDouble: number;
   colDecimal: string;
   colVarchar: string;
   colChar: string;
   colBlob: Uint8Array;
   colBit: string;
   colDate: Date;
   colTime: string;
   colTimestampS: Date;
   colTimestampMs: Date;
   colTimestamp: Date;
   colTimestampNs: Date;
   colTimestamptz: Date;
   colInterval: string;
   colJson: unknown;
   colList: Array<number | null>;
   colStruct:  {
      name: string | null;
      score: number | null;
   };
   colMap: Map<string, number>;
};

export type ITypeCoverageUpdate = Partial<ITypeCoverageInsert>;

export type ITypeCoverageSelect = {
   colUuid: string;
   colBoolean: boolean;
   colTinyint: number;
   colSmallint: number;
   colInteger: number;
   colBigint: BigInt;
   colHugeint: BigInt;
   colUtinyint: number;
   colUsmallint: number;
   colUinteger: number;
   colUbigint: BigInt;
   colUhugeint: BigInt;
   colReal: number;
   colDouble: number;
   colDecimal: string;
   colVarchar: string;
   colChar: string;
   colBlob: Uint8Array;
   colBit: string;
   colDate: Date;
   colTime: string;
   colTimestampS: Date;
   colTimestampMs: Date;
   colTimestamp: Date;
   colTimestampNs: Date;
   colTimestamptz: Date;
   colInterval: string;
   colJson: unknown;
   colList: Array<number | null>;
   colStruct:  {
      name: string | null;
      score: number | null;
   };
   colMap: Array< {
      key: string;
      value: number | null;
   }>;
};

export type ITypeCoverageJson = vexnor.JsonRow<ITypeCoverageSelect>;