/*
 File generated by Vexnor. Do not edit!
*/
import * as vexnor from "@vexnor/core";


export const DocumentOrder = vexnor.newSqlTable<{
   Select: IDocumentOrderSelect;
   Insert: IDocumentOrderInsert;
   Update: IDocumentOrderUpdate;
   Delete: true;
   Source: "@vexnor/example-react-vite-api:shared/codegen/duckdb";
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "document_order",
      schema: "main",
   },
   pk: ["documentId"],
   dialect: "duckdb",
   source: "@vexnor/example-react-vite-api:shared/codegen/duckdb",
   columns: {

      /**
       * document_id undefined
       */
      documentId: "document_id",

      /**
       * account undefined
       */
      account: "account",

      /**
       * status undefined
       */
      status: "status",

      /**
       * shipping undefined
       */
      shipping: "shipping",

      /**
       * items undefined
       */
      items: "items",

      /**
       * tags undefined
       */
      tags: "tags",

      /**
       * created_at undefined
       */
      createdAt: "created_at",
   },
   columnStructures: {
      account: {
         kind: "struct",
         fields: {
            accountId: {
               fieldName: "account_id",
            },
            email: {
               fieldName: "email",
            },
            status: {
               fieldName: "status",
            },
         },
      },
      shipping: {
         kind: "struct",
         fields: {
            address: {
               fieldName: "address",
               structure: {
                  kind: "struct",
                  fields: {
                     street: {
                        fieldName: "street",
                     },
                     city: {
                        fieldName: "city",
                     },
                     country: {
                        fieldName: "country",
                     },
                     geo: {
                        fieldName: "geo",
                        structure: {
                           kind: "struct",
                           fields: {
                              latitude: {
                                 fieldName: "latitude",
                              },
                              longitude: {
                                 fieldName: "longitude",
                              },
                           },
                        },
                     },
                  },
               },
            },
            carrier: {
               fieldName: "carrier",
               structure: {
                  kind: "struct",
                  fields: {
                     name: {
                        fieldName: "name",
                     },
                     trackingId: {
                        fieldName: "tracking_id",
                     },
                  },
               },
            },
         },
      },
      items: {
         kind: "list",
         value: {
            kind: "struct",
            fields: {
               product: {
                  fieldName: "product",
                  structure: {
                     kind: "struct",
                     fields: {
                        productId: {
                           fieldName: "product_id",
                        },
                        label: {
                           fieldName: "label",
                        },
                        category: {
                           fieldName: "category",
                        },
                     },
                  },
               },
               quantity: {
                  fieldName: "quantity",
               },
               unitPrice: {
                  fieldName: "unit_price",
               },
               discounts: {
                  fieldName: "discounts",
                  structure: {
                     kind: "list",
                     value: {
                        kind: "struct",
                        fields: {
                           code: {
                              fieldName: "code",
                           },
                           amount: {
                              fieldName: "amount",
                           },
                        },
                     },
                  },
               },
            },
         },
      },
      tags: {
         kind: "list",
         value: null,
      },
   },
   jsonSchema: {
      createdAt: "Date",
   },
   dbSchema: {
      documentId: { dbType: "VARCHAR", type: vexnor.SqlLiteralType.String },
      account: { dbType: "STRUCT(account_id VARCHAR, email VARCHAR, status VARCHAR)", type: vexnor.SqlLiteralType.Json },
      status: { dbType: "VARCHAR", type: vexnor.SqlLiteralType.String },
      shipping: { dbType: "STRUCT(address STRUCT(street VARCHAR, city VARCHAR, country VARCHAR, geo STRUCT(latitude DOUBLE, longitude DOUBLE)), carrier STRUCT(\"name\" VARCHAR, tracking_id VARCHAR))", type: vexnor.SqlLiteralType.Json, nullable: true },
      items: { dbType: "STRUCT(product STRUCT(product_id VARCHAR, \"label\" VARCHAR, category VARCHAR), quantity INTEGER, unit_price DOUBLE, discounts STRUCT(code VARCHAR, amount DOUBLE)[])[]", type: vexnor.SqlLiteralType.Json },
      tags: { dbType: "VARCHAR[]", type: vexnor.SqlLiteralType.Json },
      createdAt: { dbType: "TIMESTAMP", type: vexnor.SqlLiteralType.Date },
   },
});
export type IDocumentOrderInsert = {
   documentId: string;
   account:  {
      account_id: string | null;
      email: string | null;
      status: string | null;
   };
   status: string;
   shipping?:  {
      address:  {
         street: string | null;
         city: string | null;
         country: string | null;
         geo:  {
            latitude: number | null;
            longitude: number | null;
         } | null;
      } | null;
      carrier:  {
         name: string | null;
         tracking_id: string | null;
      } | null;
   } | null;
   items: Array< {
      product:  {
         product_id: string | null;
         label: string | null;
         category: string | null;
      } | null;
      quantity: number | null;
      unit_price: number | null;
      discounts: Array< {
         code: string | null;
         amount: number | null;
      } | null> | null;
   } | null>;
   tags: Array<string | null>;
   createdAt: Date;
};

export type IDocumentOrderUpdate = Partial<IDocumentOrderInsert>;

export type IDocumentOrderSelect = {
   documentId: string;
   account:  {
      accountId: string | null;
      email: string | null;
      status: string | null;
   };
   status: string;
   shipping:  {
      address:  {
         street: string | null;
         city: string | null;
         country: string | null;
         geo:  {
            latitude: number | null;
            longitude: number | null;
         } | null;
      } | null;
      carrier:  {
         name: string | null;
         trackingId: string | null;
      } | null;
   } | null;
   items: Array< {
      product:  {
         productId: string | null;
         label: string | null;
         category: string | null;
      } | null;
      quantity: number | null;
      unitPrice: number | null;
      discounts: Array< {
         code: string | null;
         amount: number | null;
      } | null> | null;
   } | null>;
   tags: Array<string | null>;
   createdAt: Date;
};

export type IDocumentOrderJson = vexnor.JsonRow<IDocumentOrderSelect>;