/*
 File generated by Vexnor. Do not edit!
*/
import * as vexnor from "@vexnor/core";
import * as udt from "./main-enums.js";

export const Order = vexnor.newSqlTable<{
   Select: IOrderSelect;
   Insert: IOrderInsert;
   Update: IOrderUpdate;
   Delete: true;
   Source: "@vexnor/example-react-vite-api:shared/codegen/duckdb";
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "order",
      schema: "main",
   },
   pk: ["orderId"],
   dialect: "duckdb",
   source: "@vexnor/example-react-vite-api:shared/codegen/duckdb",
   columns: {

      /**
       * order_id UUID default uuid()
       */
      orderId: "order_id",

      /**
       * status order_status default 'created'
       */
      status: "status",

      /**
       * created_at TIMESTAMP WITH TIME ZONE default current_timestamp
       */
      createdAt: "created_at",

      /**
       * modified_at TIMESTAMP WITH TIME ZONE default current_timestamp
       */
      modifiedAt: "modified_at",

      /**
       * account_id UUID
       */
      accountId: "account_id",

      /**
       * shipping STRUCT(address STRUCT(street VARCHAR, city VARCHAR, country VARCHAR, geo STRUCT(latitude DOUBLE, longitude DOUBLE)), carrier STRUCT("name" VARCHAR, tracking_id VARCHAR))
       */
      shipping: "shipping",

      /**
       * items STRUCT(product STRUCT(product_id VARCHAR, "label" VARCHAR, category VARCHAR), quantity INTEGER, unit_price DOUBLE, discounts STRUCT(code VARCHAR, amount DOUBLE)[])[]
       */
      items: "items",

      /**
       * tags VARCHAR[]
       */
      tags: "tags",
   },
   jsonSchema: {
      createdAt: "Date",
      modifiedAt: "Date",
   },
   fk: [
      { from: ["accountId"], to: { schema: "main", table: "account", columns: ["accountId"] } },
   ],
   dbSchema: {
      orderId: { dbType: "UUID", type: vexnor.SqlLiteralType.String, default: "uuid()" },
      status: { dbType: "order_status", type: vexnor.SqlLiteralType.Udt, default: "'created'", values: ["created", "paid", "delivered", "received"] },
      createdAt: { dbType: "TIMESTAMP WITH TIME ZONE", type: vexnor.SqlLiteralType.Date, default: "current_timestamp" },
      modifiedAt: { dbType: "TIMESTAMP WITH TIME ZONE", type: vexnor.SqlLiteralType.Date, default: "current_timestamp" },
      accountId: { dbType: "UUID", type: vexnor.SqlLiteralType.String },
      shipping: {
         dbType: "STRUCT(address STRUCT(street VARCHAR, city VARCHAR, country VARCHAR, geo STRUCT(latitude DOUBLE, longitude DOUBLE)), carrier STRUCT(\"name\" VARCHAR, tracking_id VARCHAR))",
         type: vexnor.SqlLiteralType.Json,
         nullable: true,
         structure: {
            kind: "struct",
            fields: {
               address: {
                  fieldName: "address",
                  structure: {
                     kind: "struct",
                     fields: {
                        street: {
                           fieldName: "street",
                        },
                        city: {
                           fieldName: "city",
                        },
                        country: {
                           fieldName: "country",
                        },
                        geo: {
                           fieldName: "geo",
                           structure: {
                              kind: "struct",
                              fields: {
                                 latitude: {
                                    fieldName: "latitude",
                                 },
                                 longitude: {
                                    fieldName: "longitude",
                                 },
                              },
                           },
                        },
                     },
                  },
               },
               carrier: {
                  fieldName: "carrier",
                  structure: {
                     kind: "struct",
                     fields: {
                        name: {
                           fieldName: "name",
                        },
                        trackingId: {
                           fieldName: "tracking_id",
                        },
                     },
                  },
               },
            },
         },
      },
      items: {
         dbType: "STRUCT(product STRUCT(product_id VARCHAR, \"label\" VARCHAR, category VARCHAR), quantity INTEGER, unit_price DOUBLE, discounts STRUCT(code VARCHAR, amount DOUBLE)[])[]",
         type: vexnor.SqlLiteralType.Json,
         nullable: true,
         structure: {
            kind: "list",
            value: {
               kind: "struct",
               fields: {
                  product: {
                     fieldName: "product",
                     structure: {
                        kind: "struct",
                        fields: {
                           productId: {
                              fieldName: "product_id",
                           },
                           label: {
                              fieldName: "label",
                           },
                           category: {
                              fieldName: "category",
                           },
                        },
                     },
                  },
                  quantity: {
                     fieldName: "quantity",
                  },
                  unitPrice: {
                     fieldName: "unit_price",
                  },
                  discounts: {
                     fieldName: "discounts",
                     structure: {
                        kind: "list",
                        value: {
                           kind: "struct",
                           fields: {
                              code: {
                                 fieldName: "code",
                              },
                              amount: {
                                 fieldName: "amount",
                              },
                           },
                        },
                     },
                  },
               },
            },
         },
      },
      tags: {
         dbType: "VARCHAR[]",
         type: vexnor.SqlLiteralType.Json,
         nullable: true,
         structure: {
            kind: "list",
            value: null,
         },
      },
   },
});
export type IOrderInsert = {
   orderId?: string;
   status?: udt.OrderStatusUdt;
   createdAt?: Date;
   modifiedAt?: Date;
   accountId: string;
   shipping?:  {
      address:  {
         street: string | null;
         city: string | null;
         country: string | null;
         geo:  {
            latitude: number | null;
            longitude: number | null;
         } | null;
      } | null;
      carrier:  {
         name: string | null;
         tracking_id: string | null;
      } | null;
   } | null;
   items?: Array< {
      product:  {
         product_id: string | null;
         label: string | null;
         category: string | null;
      } | null;
      quantity: number | null;
      unit_price: number | null;
      discounts: Array< {
         code: string | null;
         amount: number | null;
      } | null> | null;
   } | null> | null;
   tags?: Array<string | null> | null;
};

export type IOrderUpdate = Partial<IOrderInsert>;

export type IOrderSelect = {
   orderId: string;
   status: udt.OrderStatusUdt;
   createdAt: Date;
   modifiedAt: Date;
   accountId: string;
   shipping:  {
      address:  {
         street: string | null;
         city: string | null;
         country: string | null;
         geo:  {
            latitude: number | null;
            longitude: number | null;
         } | null;
      } | null;
      carrier:  {
         name: string | null;
         trackingId: string | null;
      } | null;
   } | null;
   items: Array< {
      product:  {
         productId: string | null;
         label: string | null;
         category: string | null;
      } | null;
      quantity: number | null;
      unitPrice: number | null;
      discounts: Array< {
         code: string | null;
         amount: number | null;
      } | null> | null;
   } | null> | null;
   tags: Array<string | null> | null;
};

export type IOrderJson = vexnor.JsonRow<IOrderSelect>;