/*
 File generated by Vexnor. Do not edit!
*/
import * as vexnor from "@vexnor/core";
import * as udt from "./main-enums.js";

export const Order = vexnor.newSqlTable<{
   Select: IOrderSelect;
   Insert: IOrderInsert;
   Update: IOrderUpdate;
   Delete: true;
   Source: "@vexnor/example-react-vite-api:shared/codegen/duckdb";
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "order",
      schema: "main",
   },
   pk: ["orderId"],
   dialect: "duckdb",
   source: "@vexnor/example-react-vite-api:shared/codegen/duckdb",
   columns: {

      /**
       * order_id undefined default uuid()
       */
      orderId: "order_id",

      /**
       * status order_status default 'created'
       */
      status: "status",

      /**
       * created_at undefined default current_timestamp
       */
      createdAt: "created_at",

      /**
       * modified_at undefined default current_timestamp
       */
      modifiedAt: "modified_at",

      /**
       * account_id undefined
       */
      accountId: "account_id",
   },
   jsonSchema: {
      createdAt: "Date",
      modifiedAt: "Date",
   },
   fk: [
      { from: ["accountId"], to: { schema: "main", table: "account", columns: ["accountId"] } },
   ],
   dbSchema: {
      orderId: { dbType: "UUID", type: vexnor.SqlLiteralType.String, default: "uuid()" },
      status: { dbType: "order_status", type: vexnor.SqlLiteralType.Udt, default: "'created'", values: ["created", "paid", "delivered", "received"] },
      createdAt: { dbType: "TIMESTAMP WITH TIME ZONE", type: vexnor.SqlLiteralType.Date, default: "current_timestamp" },
      modifiedAt: { dbType: "TIMESTAMP WITH TIME ZONE", type: vexnor.SqlLiteralType.Date, default: "current_timestamp" },
      accountId: { dbType: "UUID", type: vexnor.SqlLiteralType.String },
   },
});
export type IOrderInsert = {
   orderId?: string;
   status?: udt.OrderStatusUdt;
   createdAt?: Date;
   modifiedAt?: Date;
   accountId: string;
};

export type IOrderUpdate = Partial<IOrderInsert>;

export type IOrderSelect = {
   orderId: string;
   status: udt.OrderStatusUdt;
   createdAt: Date;
   modifiedAt: Date;
   accountId: string;
};

export type IOrderJson = vexnor.JsonRow<IOrderSelect>;