import { writeTableType } from "./write-table-type.js";
import { writeTableInsert } from "./write-table-insert.js";
import { writeTableSelect } from "./write-table-select.js";
import { PrintTableArgs } from "#/plugin/plugin.js";
import { getCodegenContext } from "#/cli/codegen/codegen-context.js";

export function writeTable({ table }: PrintTableArgs): string {
   const writer = getCodegenContext().newWriter();
   const { includeEnums, plugin } = getCodegenContext();
   const { table_schema } = table;
   writer.writeLine(`/*\n File generated by Vexnor. Do not edit! \n*/`);
   writer.writeLine(`import * as vexnor from "vexnor";`);
   if (includeEnums) {
      writer.writeLine("##import-enums##");
   }
   writer.writeLine("##import-plugin##");

   writeTableType(writer, { table });
   writeTableInsert(writer, { table });
   writeTableSelect(writer, { table });
   let result = writer.toString();
   if (result.includes(": udt.")) {
      result = result.replace("##import-enums##", `import * as udt from "./${table_schema}-enums.js";`);
   } else {
      result = result.replace("##import-enums##", "");
   }

   const pluginImports = [...new Set(
      table.columns
         .map((col) => plugin.getColumnType(col).tsImport)
         .filter((i): i is string => !!i)
   )].join("\n");
   result = result.replace("##import-plugin##", pluginImports);

   return result;
}
