/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";

import type * as vexnorPostgres from "@vexnor/postgres";
export const TypeCoverage = vexnor.newSqlTable<{
   Select: ITypeCoverageSelect;
   Insert: ITypeCoverageInsert;
   Update: ITypeCoverageUpdate;
   Delete: true;
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "type_coverage",
      schema: "vexnor_dev",
   },
   pk: ["colUuid"],
   dialect: "postgresql",
   source: "@vexnor/stack-fixtures:codegen/postgres",
   columns: {

      /**
       * col_uuid uuid default gen_random_uuid()
       */
      colUuid: "col_uuid",

      /**
       * col_text text
       */
      colText: "col_text",

      /**
       * col_varchar varchar
       */
      colVarchar: "col_varchar",

      /**
       * col_bpchar bpchar
       */
      colBpchar: "col_bpchar",

      /**
       * col_json json
       */
      colJson: "col_json",

      /**
       * col_jsonb jsonb
       */
      colJsonb: "col_jsonb",

      /**
       * col_xml xml
       */
      colXml: "col_xml",

      /**
       * col_inet inet
       */
      colInet: "col_inet",

      /**
       * col_cidr cidr
       */
      colCidr: "col_cidr",

      /**
       * col_macaddr macaddr
       */
      colMacaddr: "col_macaddr",

      /**
       * col_bit bit
       */
      colBit: "col_bit",

      /**
       * col_varbit varbit
       */
      colVarbit: "col_varbit",

      /**
       * col_interval interval
       */
      colInterval: "col_interval",

      /**
       * col_time time
       */
      colTime: "col_time",

      /**
       * col_timetz timetz
       */
      colTimetz: "col_timetz",

      /**
       * col_money money
       */
      colMoney: "col_money",

      /**
       * col_int2 int2
       */
      colInt2: "col_int2",

      /**
       * col_int4 int4
       */
      colInt4: "col_int4",

      /**
       * col_float4 float4
       */
      colFloat4: "col_float4",

      /**
       * col_float8 float8
       */
      colFloat8: "col_float8",

      /**
       * col_int8 int8
       */
      colInt8: "col_int8",

      /**
       * col_numeric numeric
       */
      colNumeric: "col_numeric",

      /**
       * col_bool bool
       */
      colBool: "col_bool",

      /**
       * col_date date
       */
      colDate: "col_date",

      /**
       * col_timestamp timestamp
       */
      colTimestamp: "col_timestamp",

      /**
       * col_timestamptz timestamptz default now()
       */
      colTimestamptz: "col_timestamptz",

      /**
       * col_bytea bytea
       */
      colBytea: "col_bytea",

      /**
       * col_oid oid
       */
      colOid: "col_oid",

      /**
       * col_xid xid
       */
      colXid: "col_xid",

      /**
       * col_name name
       */
      colName: "col_name",

      /**
       * col_pg_lsn pg_lsn
       */
      colPgLsn: "col_pg_lsn",

      /**
       * col_tsvector tsvector
       */
      colTsvector: "col_tsvector",

      /**
       * col_tsquery tsquery
       */
      colTsquery: "col_tsquery",

      /**
       * col_point point
       */
      colPoint: "col_point",

      /**
       * col_line line
       */
      colLine: "col_line",

      /**
       * col_lseg lseg
       */
      colLseg: "col_lseg",

      /**
       * col_box box
       */
      colBox: "col_box",

      /**
       * col_path path
       */
      colPath: "col_path",

      /**
       * col_polygon polygon
       */
      colPolygon: "col_polygon",

      /**
       * col_circle circle
       */
      colCircle: "col_circle",
   },
   jsonSchema: {
      colDate: "Date",
      colTimestamp: "Date",
      colTimestamptz: "Date",
   },
   dbSchema: {
      colUuid: { dbType: "uuid", type: vexnor.SqlLiteralType.String, default: "gen_random_uuid()" },
      colText: { dbType: "text", type: vexnor.SqlLiteralType.String },
      colVarchar: { dbType: "varchar", type: vexnor.SqlLiteralType.String },
      colBpchar: { dbType: "bpchar", type: vexnor.SqlLiteralType.String },
      colJson: { dbType: "json", type: vexnor.SqlLiteralType.Json, nullable: true },
      colJsonb: { dbType: "jsonb", type: vexnor.SqlLiteralType.Json, nullable: true },
      colXml: { dbType: "xml", type: vexnor.SqlLiteralType.String, nullable: true },
      colInet: { dbType: "inet", type: vexnor.SqlLiteralType.String, nullable: true },
      colCidr: { dbType: "cidr", type: vexnor.SqlLiteralType.String, nullable: true },
      colMacaddr: { dbType: "macaddr", type: vexnor.SqlLiteralType.String, nullable: true },
      colBit: { dbType: "bit", type: vexnor.SqlLiteralType.String, nullable: true },
      colVarbit: { dbType: "varbit", type: vexnor.SqlLiteralType.String, nullable: true },
      colInterval: { dbType: "interval", type: vexnor.SqlLiteralType.Custom, nullable: true },
      colTime: { dbType: "time", type: vexnor.SqlLiteralType.String, nullable: true },
      colTimetz: { dbType: "timetz", type: vexnor.SqlLiteralType.String, nullable: true },
      colMoney: { dbType: "money", type: vexnor.SqlLiteralType.String, nullable: true },
      colInt2: { dbType: "int2", type: vexnor.SqlLiteralType.Number },
      colInt4: { dbType: "int4", type: vexnor.SqlLiteralType.Number },
      colFloat4: { dbType: "float4", type: vexnor.SqlLiteralType.Number },
      colFloat8: { dbType: "float8", type: vexnor.SqlLiteralType.Number },
      colInt8: { dbType: "int8", type: vexnor.SqlLiteralType.String },
      colNumeric: { dbType: "numeric", type: vexnor.SqlLiteralType.String, nullable: true },
      colBool: { dbType: "bool", type: vexnor.SqlLiteralType.Boolean },
      colDate: { dbType: "date", type: vexnor.SqlLiteralType.Date },
      colTimestamp: { dbType: "timestamp", type: vexnor.SqlLiteralType.Date },
      colTimestamptz: { dbType: "timestamptz", type: vexnor.SqlLiteralType.Date, default: "now()" },
      colBytea: { dbType: "bytea", type: vexnor.SqlLiteralType.Buffer, nullable: true },
      colOid: { dbType: "oid", type: vexnor.SqlLiteralType.Number, nullable: true },
      colXid: { dbType: "xid", type: vexnor.SqlLiteralType.String, nullable: true },
      colName: { dbType: "name", type: vexnor.SqlLiteralType.String, nullable: true },
      colPgLsn: { dbType: "pg_lsn", type: vexnor.SqlLiteralType.String, nullable: true },
      colTsvector: { dbType: "tsvector", type: vexnor.SqlLiteralType.String, nullable: true },
      colTsquery: { dbType: "tsquery", type: vexnor.SqlLiteralType.String, nullable: true },
      colPoint: { dbType: "point", type: vexnor.SqlLiteralType.Custom, nullable: true },
      colLine: { dbType: "line", type: vexnor.SqlLiteralType.String, nullable: true },
      colLseg: { dbType: "lseg", type: vexnor.SqlLiteralType.String, nullable: true },
      colBox: { dbType: "box", type: vexnor.SqlLiteralType.String, nullable: true },
      colPath: { dbType: "path", type: vexnor.SqlLiteralType.String, nullable: true },
      colPolygon: { dbType: "polygon", type: vexnor.SqlLiteralType.String, nullable: true },
      colCircle: { dbType: "circle", type: vexnor.SqlLiteralType.Custom, nullable: true },
   },
});
export type ITypeCoverageInsert = {
   colUuid?: string;
   colText: string;
   colVarchar: string;
   colBpchar: string;
   colJson?: unknown | null;
   colJsonb?: unknown | null;
   colXml?: string | null;
   colInet?: string | null;
   colCidr?: string | null;
   colMacaddr?: string | null;
   colBit?: string | null;
   colVarbit?: string | null;
   colInterval?: string | null;
   colTime?: string | null;
   colTimetz?: string | null;
   colMoney?: string | null;
   colInt2: number;
   colInt4: number;
   colFloat4: number;
   colFloat8: number;
   colInt8: string;
   colNumeric?: string | null;
   colBool: boolean;
   colDate: Date;
   colTimestamp: Date;
   colTimestamptz?: Date;
   colBytea?: Uint8Array | null;
   colOid?: number | null;
   colXid?: string | null;
   colName?: string | null;
   colPgLsn?: string | null;
   colTsvector?: string | null;
   colTsquery?: string | null;
   colPoint?: string | null;
   colLine?: string | null;
   colLseg?: string | null;
   colBox?: string | null;
   colPath?: string | null;
   colPolygon?: string | null;
   colCircle?: string | null;
};

export type ITypeCoverageUpdate = Partial<ITypeCoverageInsert>;

export type ITypeCoverageSelect = {
   colUuid: string;
   colText: string;
   colVarchar: string;
   colBpchar: string;
   colJson: unknown | null;
   colJsonb: unknown | null;
   colXml: string | null;
   colInet: string | null;
   colCidr: string | null;
   colMacaddr: string | null;
   colBit: string | null;
   colVarbit: string | null;
   colInterval: vexnorPostgres.Interval | null;
   colTime: string | null;
   colTimetz: string | null;
   colMoney: string | null;
   colInt2: number;
   colInt4: number;
   colFloat4: number;
   colFloat8: number;
   colInt8: string;
   colNumeric: string | null;
   colBool: boolean;
   colDate: Date;
   colTimestamp: Date;
   colTimestamptz: Date;
   colBytea: Uint8Array | null;
   colOid: number | null;
   colXid: string | null;
   colName: string | null;
   colPgLsn: string | null;
   colTsvector: string | null;
   colTsquery: string | null;
   colPoint: vexnorPostgres.Point | null;
   colLine: string | null;
   colLseg: string | null;
   colBox: string | null;
   colPath: string | null;
   colPolygon: string | null;
   colCircle: vexnorPostgres.Circle | null;
};

export type ITypeCoverageJson = vexnor.JsonRow<ITypeCoverageSelect>;