/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "vexnor";

export const TypeCoverage = vexnor.newSqlTable<{
   Select: ITypeCoverageSelect;
   Insert: ITypeCoverageInsert;
   Update: ITypeCoverageUpdate;
   Delete: true;
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "type_coverage",
      schema: "main",
   },
   pk: ["colText"],
   dialect: "sqlite",
   columns: {

      /**
       * col_text TEXT
       */
      colText: "col_text",

      /**
       * col_varchar VARCHAR(255)
       */
      colVarchar: "col_varchar",

      /**
       * col_char CHAR(10)
       */
      colChar: "col_char",

      /**
       * col_integer INTEGER
       */
      colInteger: "col_integer",

      /**
       * col_int INT
       */
      colInt: "col_int",

      /**
       * col_tinyint TINYINT
       */
      colTinyint: "col_tinyint",

      /**
       * col_smallint SMALLINT
       */
      colSmallint: "col_smallint",

      /**
       * col_bigint BIGINT
       */
      colBigint: "col_bigint",

      /**
       * col_real REAL
       */
      colReal: "col_real",

      /**
       * col_float FLOAT
       */
      colFloat: "col_float",

      /**
       * col_double DOUBLE
       */
      colDouble: "col_double",

      /**
       * col_numeric NUMERIC(10, 2)
       */
      colNumeric: "col_numeric",

      /**
       * col_decimal DECIMAL(10, 2)
       */
      colDecimal: "col_decimal",

      /**
       * col_boolean BOOLEAN
       */
      colBoolean: "col_boolean",

      /**
       * col_date DATE
       */
      colDate: "col_date",

      /**
       * col_datetime DATETIME
       */
      colDatetime: "col_datetime",

      /**
       * col_timestamp TIMESTAMP
       */
      colTimestamp: "col_timestamp",

      /**
       * col_blob BLOB
       */
      colBlob: "col_blob",
   },
});
export type ITypeCoverageInsert = {
   colText: string;
   colVarchar: string;
   colChar: string;
   colInteger: number;
   colInt: number;
   colTinyint: number;
   colSmallint: number;
   colBigint: number;
   colReal: number;
   colFloat: number;
   colDouble: number;
   colNumeric?: number | null;
   colDecimal?: number | null;
   colBoolean: vexnor.Bit;
   colDate?: string | null;
   colDatetime?: string | null;
   colTimestamp?: string | null;
   colBlob?: Uint8Array | null;
};

export type ITypeCoverageUpdate = Partial<ITypeCoverageInsert>;

export type ITypeCoverageSelect = {
   colText: string;
   colVarchar: string;
   colChar: string;
   colInteger: number;
   colInt: number;
   colTinyint: number;
   colSmallint: number;
   colBigint: number;
   colReal: number;
   colFloat: number;
   colDouble: number;
   colNumeric: number | null;
   colDecimal: number | null;
   colBoolean: vexnor.Bit;
   colDate: string | null;
   colDatetime: string | null;
   colTimestamp: string | null;
   colBlob: Uint8Array | null;
};

export type ITypeCoverageJson = vexnor.JsonRow<ITypeCoverageSelect>;