/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";

export const Account = vexnor.newSqlTable<{
   Select: IAccountSelect;
   Insert: IAccountInsert;
   Update: IAccountUpdate;
   Delete: true;
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "account",
      schema: "main",
   },
   pk: ["accountId"],
   dialect: "sqlite",
   source: "@vexnor/test-sqlite3:src/codegen",
   columns: {

      /**
       * account_id TEXT default lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))
       */
      accountId: "account_id",

      /**
       * status TEXT default 'created'
       */
      status: "status",

      /**
       * email TEXT
       */
      email: "email",

      /**
       * first_name TEXT
       */
      firstName: "first_name",

      /**
       * last_name TEXT
       */
      lastName: "last_name",

      /**
       * notes TEXT
       */
      notes: "notes",

      /**
       * created_at TEXT default datetime('now')
       */
      createdAt: "created_at",

      /**
       * modified_at TEXT default datetime('now')
       */
      modifiedAt: "modified_at",

      /**
       * parent_id TEXT
       */
      parentId: "parent_id",
   },
   fk: [
      { from: ["parentId"], to: { schema: "main", table: "account", columns: ["accountId"] } },
   ],
   dbSchema: {
      accountId: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, default: "lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))" },
      status: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, default: "'created'" },
      email: { dbType: "TEXT", type: vexnor.SqlLiteralType.String },
      firstName: { dbType: "TEXT", type: vexnor.SqlLiteralType.String },
      lastName: { dbType: "TEXT", type: vexnor.SqlLiteralType.String },
      notes: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, nullable: true },
      createdAt: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, default: "datetime('now')" },
      modifiedAt: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, default: "datetime('now')" },
      parentId: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, nullable: true },
   },
});
export type IAccountInsert = {
   accountId?: string;
   status?: string;
   email: string;
   firstName: string;
   lastName: string;
   notes?: string | null;
   createdAt?: string;
   modifiedAt?: string;
   parentId?: string | null;
};

export type IAccountUpdate = Partial<IAccountInsert>;

export type IAccountSelect = {
   accountId: string;
   status: string;
   email: string;
   firstName: string;
   lastName: string;
   notes: string | null;
   createdAt: string;
   modifiedAt: string;
   parentId: string | null;
};

export type IAccountJson = vexnor.JsonRow<IAccountSelect>;