/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";

export const MigrationValnor = vexnor.newSqlTable<{
   Select: IMigrationValnorSelect;
   Insert: IMigrationValnorInsert;
   Update: IMigrationValnorUpdate;
   Delete: true;
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "migration_valnor",
      schema: "main",
   },
   pk: ["version"],
   dialect: "sqlite",
   source: "@vexnor/test-sqlite3:src/codegen",
   columns: {

      /**
       * version INTEGER
       */
      version: "version",

      /**
       * name TEXT
       */
      name: "name",

      /**
       * md5 TEXT
       */
      md5: "md5",

      /**
       * run_at TIMESTAMP WITH TIME ZONE
       */
      runAt: "run_at",
   },
   dbSchema: {
      version: { dbType: "INTEGER", type: vexnor.SqlLiteralType.Number, nullable: true },
      name: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, nullable: true },
      md5: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, nullable: true },
      runAt: { dbType: "TIMESTAMP WITH TIME ZONE", type: vexnor.SqlLiteralType.String, nullable: true },
   },
});
export type IMigrationValnorInsert = {
   version?: number | null;
   name?: string | null;
   md5?: string | null;
   runAt?: string | null;
};

export type IMigrationValnorUpdate = Partial<IMigrationValnorInsert>;

export type IMigrationValnorSelect = {
   version: number | null;
   name: string | null;
   md5: string | null;
   runAt: string | null;
};

export type IMigrationValnorJson = vexnor.JsonRow<IMigrationValnorSelect>;