import { writeTableType } from "./write-table-type.js";
import { writeTableInsert } from "./write-table-insert.js";
import { writeTableSelect } from "./write-table-select.js";
import { getCodegenContext } from "#src/cli/codegen/codegen-context.js";
import type { SchemaCatalogObject } from "#src/schema/schema-catalog.js";

export function writeTable({ table }: { table: SchemaCatalogObject }): string {
   const writer = getCodegenContext().newWriter();
   const { includeEnums } = getCodegenContext();
   const { schema } = table;
   writer.writeLine(`/*\n File generated by Vexnor. Do not edit! \n*/`);
   writer.writeLine(`import * as vexnor from "@vexnor/core";`);
   if (includeEnums) {
      writer.writeLine("##import-enums##");
   }
   writer.writeLine("##import-plugin##");

   writeTableType(writer, { table });
   writeTableInsert(writer, { table });
   writeTableSelect(writer, { table });
   let result = writer.toString();
   if (result.includes(": udt.")) {
      result = result.replace("##import-enums##", `import * as udt from "./${schema}-enums.js";`);
   } else {
      result = result.replace("##import-enums##", "");
   }

   const pluginImports = [...new Set(
      table.columns
         .map((column) => column.customType?.import)
         .filter((i): i is string => !!i)
   )].join("\n");
   result = result.replace("##import-plugin##", pluginImports);

   return result;
}
