/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "vexnor";

export const AccountOrderSummary = vexnor.newSqlTable<{
   Select: IAccountOrderSummarySelect;
}>( {
   crud: {
      select: true,
      insert: false,
      update: false,
      delete: false,
   },
   tableInfo: {
      name: "account_order_summary",
      schema: "vexnor_dev",
   },
   pk: [],
   dialect: "tsql",
   columns: {

      /**
       * account_id uniqueidentifier
       */
      accountId: "account_id",

      /**
       * email varchar
       */
      email: "email",

      /**
       * first_name varchar
       */
      firstName: "first_name",

      /**
       * last_name varchar
       */
      lastName: "last_name",

      /**
       * status varchar
       */
      status: "status",

      /**
       * order_count int
       */
      orderCount: "order_count",

      /**
       * latest_order_at datetimeoffset
       */
      latestOrderAt: "latest_order_at",
   },
   jsonSchema: {
      latestOrderAt: "Date",
   },
});
export type IAccountOrderSummarySelect = {
   accountId: string;
   email: string;
   firstName: string;
   lastName: string;
   status: string;
   orderCount: number | null;
   latestOrderAt: Date | null;
};

export type IAccountOrderSummaryJson = vexnor.JsonRow<IAccountOrderSummarySelect>;