/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";


export const OrderItem = vexnor.newSqlTable<{
   Select: IOrderItemSelect;
   Insert: IOrderItemInsert;
   Update: IOrderItemUpdate;
   Delete: true;
}>( {
   crud: {
      select: true,
      insert: true,
      update: true,
      delete: true,
   },
   tableInfo: {
      name: "order_item",
      schema: "vexnor_dev",
   },
   pk: ["orderId","productId"],
   dialect: "postgresql",
   source: "vexnor-root:examples/react-vite-ui/shared/codegen/postgres",
   columns: {

      /**
       * order_id uuid
       */
      orderId: "order_id",

      /**
       * product_id uuid
       */
      productId: "product_id",

      /**
       * created_at timestamptz default now()
       */
      createdAt: "created_at",

      /**
       * modified_at timestamptz default now()
       */
      modifiedAt: "modified_at",

      /**
       * product_price numeric
       */
      productPrice: "product_price",

      /**
       * discount_price numeric
       */
      discountPrice: "discount_price",

      /**
       * quantity int4
       */
      quantity: "quantity",

      /**
       * metadata jsonb
       */
      metadata: "metadata",
   },
   jsonSchema: {
      createdAt: "Date",
      modifiedAt: "Date",
   },
   fk: [
      { from: ["orderId"], to: { schema: "vexnor_dev", table: "order", columns: ["orderId"] } },
      { from: ["productId"], to: { schema: "vexnor_dev", table: "product", columns: ["productId"] } },
   ],
   dbSchema: {
      orderId: { dbType: "uuid", type: vexnor.SqlLiteralType.String },
      productId: { dbType: "uuid", type: vexnor.SqlLiteralType.String },
      createdAt: { dbType: "timestamptz", type: vexnor.SqlLiteralType.Date, default: "now()" },
      modifiedAt: { dbType: "timestamptz", type: vexnor.SqlLiteralType.Date, default: "now()" },
      productPrice: { dbType: "numeric", type: vexnor.SqlLiteralType.String },
      discountPrice: { dbType: "numeric", type: vexnor.SqlLiteralType.String, nullable: true },
      quantity: { dbType: "int4", type: vexnor.SqlLiteralType.Number },
      metadata: { dbType: "jsonb", type: vexnor.SqlLiteralType.Json, nullable: true },
   },
});
export type IOrderItemInsert = {
   orderId: string;
   productId: string;
   createdAt?: Date;
   modifiedAt?: Date;
   productPrice: string;
   discountPrice?: string | null;
   quantity: number;
   metadata?: unknown | null;
};

export type IOrderItemUpdate = Partial<IOrderItemInsert>;

export type IOrderItemSelect = {
   orderId: string;
   productId: string;
   createdAt: Date;
   modifiedAt: Date;
   productPrice: string;
   discountPrice: string | null;
   quantity: number;
   metadata: unknown | null;
};

export type IOrderItemJson = vexnor.JsonRow<IOrderItemSelect>;