/*
 File generated by Vexnor. Do not edit! 
*/
import * as vexnor from "@vexnor/core";

export const AccountOrderSummary = vexnor.newSqlTable<{
   Select: IAccountOrderSummarySelect;
}>( {
   crud: {
      select: true,
      insert: false,
      update: false,
      delete: false,
   },
   tableInfo: {
      name: "account_order_summary",
      schema: "main",
   },
   pk: [],
   dialect: "sqlite",
   source: "vexnor-root:examples/react-vite-ui/shared/codegen/sqlite3",
   columns: {

      /**
       * account_id TEXT
       */
      accountId: "account_id",

      /**
       * email TEXT
       */
      email: "email",

      /**
       * first_name TEXT
       */
      firstName: "first_name",

      /**
       * last_name TEXT
       */
      lastName: "last_name",

      /**
       * status TEXT
       */
      status: "status",

      /**
       * order_count 
       */
      orderCount: "order_count",

      /**
       * latest_order_at 
       */
      latestOrderAt: "latest_order_at",
   },
   dbSchema: {
      accountId: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, nullable: true },
      email: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, nullable: true },
      firstName: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, nullable: true },
      lastName: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, nullable: true },
      status: { dbType: "TEXT", type: vexnor.SqlLiteralType.String, nullable: true },
      orderCount: { dbType: "", type: vexnor.SqlLiteralType.String, nullable: true },
      latestOrderAt: { dbType: "", type: vexnor.SqlLiteralType.String, nullable: true },
   },
});
export type IAccountOrderSummarySelect = {
   accountId: string | null;
   email: string | null;
   firstName: string | null;
   lastName: string | null;
   status: string | null;
   orderCount: string | null;
   latestOrderAt: string | null;
};

export type IAccountOrderSummaryJson = vexnor.JsonRow<IAccountOrderSummarySelect>;