import {
   SqlTable,
   SqlSelectArgs,
   SqlUpdateArgs,
   SqlDeleteArgs,
   SqlInsertFromArgs,
   Sql,
   expand,
   sql,
   raw,
   row,
   info,
} from "vexnor";
import { ok } from "vexnor";
import { postgresSelect, PostgresSelectResult } from "./postgres-select.js";
import { postgresInsertRows, PostgresInsertRowsResult } from "./postgres-insert-rows.js";
import { postgresInsertFrom, PostgresInsertFromResult } from "./postgres-insert-from.js";
import { postgresUpdate, PostgresTableUpdateResult } from "./postgres-update.js";
import { postgresDelete, PostgresDeleteResult } from "./postgres-delete.js";
import { postgresUpsert, PostgresUpsertArgs, PostgresUpsertResult } from "./postgres-upsert.js";
import { PostgresQueryHandler } from "#/postgres-query-handler.js";
import { sql as postgresSql } from "#/postgres-sql.js";

type PkFields<T extends { Select: Record<string, unknown> }> = Pick<
   T["Select"],
   Extract<keyof T["Select"], T extends { pk: ReadonlyArray<infer K> } ? K : never>
>;
type SelectInsertTable<T> = Extract<T, { Select: Record<string, unknown>; Insert: Record<string, unknown> }>;
type SelectUpdateTable<T> = Extract<T, { Select: Record<string, unknown>; Update: Record<string, unknown> }>;
type SelectDeleteTable<T> = Extract<T, { Select: Record<string, unknown>; Delete: true }>;

/**
 * The set of typed query factories available on a PostgreSQL table handler.
 *
 * Generated by `newPostgresTableHandler()`. The available methods depend on
 * which CRUD operations are enabled in the table's `crud` config:
 *
 * - `findById()` — always available; returns a query parameterized by primary key fields
 * - `findBy()` — always available; returns a query parameterized by any subset of columns
 * - `select()` — available when `crud.select` is enabled
 * - `insertRows()` — available when `crud.insert` is enabled
 * - `insertFrom()` — available when `crud.insert` is enabled
 * - `update()` — available when `crud.update` is enabled
 * - `delete()` — available when `crud.delete` is enabled
 * - `upsert()` — available when `crud.insert` is enabled
 */
export type PostgresTableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
> = (T extends { Select: Record<string, unknown> }
   ? {
        findById: () => PostgresQueryHandler<{ Params: PkFields<T> & Partial<T["Select"]>; Row: T["Select"] }>;
        findBy: () => PostgresQueryHandler<{ Params: Partial<T["Select"]>; Row: T["Select"] }>;
        select: <Args extends SqlSelectArgs>(
           args: Args,
        ) => PostgresSelectResult<T & { Select: Record<string, unknown> }, Args>;
     }
   : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           insertRows: () => PostgresInsertRowsResult<SelectInsertTable<T>>;
           insertFrom: <Args extends SqlInsertFromArgs<SelectInsertTable<T>>>(
              args: Args,
           ) => PostgresInsertFromResult<SelectInsertTable<T>, Args>;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Update: Record<string, unknown> }
      ? {
           update: <Args extends SqlUpdateArgs>(args: Args) => PostgresTableUpdateResult<SelectUpdateTable<T>, Args>;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Delete: true }
      ? {
           delete: <Args extends SqlDeleteArgs>(args: Args) => PostgresDeleteResult<SelectDeleteTable<T>, Args>;
        }
      : unknown) &
   (T extends { Select: Record<string, unknown>; Insert: Record<string, unknown> }
      ? {
           upsert: (args: PostgresUpsertArgs) => PostgresUpsertResult<SelectInsertTable<T>>;
        }
      : unknown);

function buildFindByExpand<T extends { Select: Record<string, unknown> }>(
   table: SqlTable<T>,
   fields: Partial<T["Select"]>,
) {
   const cols = table.cols;
   const pairs: Sql[] = [];
   for (const [key, value] of Object.entries(fields)) {
      if (value === undefined) continue;
      const col = cols[`$${key}` as `$${string}`];
      ok(col, `Column not found: ${key}`);
      pairs.push(sql`${col} = ${value}`.inline());
   }
   if (!pairs.length) return raw.BLANK;
   return pairs.slice(1).reduce((acc, pair) => sql`${acc} and ${pair}`.inline(), pairs[0]!);
}

function postgresFind<T extends { Select: Record<string, unknown> }, Params extends Partial<T["Select"]>>(
   table: SqlTable<T>,
): PostgresQueryHandler<{ Params: Params; Row: T["Select"] }> {
   const whereExpand = expand<Params>(
      Object.fromEntries(Object.values(table.cols).map((col) => [col.key, null])) as Record<keyof Params, null>,
      (params) => {
      if (!params) return null;
      return buildFindByExpand(table, params as Partial<T["Select"]>) as ReturnType<typeof buildFindByExpand>;
   });

   return postgresSql`
      ${info({ driver: "postgres" }) ?? raw.BLANK}
      select ${row(table.$$)}
      from ${table}
      ${sql`where ${whereExpand}`.inline("default")}
   ` as unknown as PostgresQueryHandler<{ Params: Params; Row: T["Select"] }>;
}

/**
 * Creates a `PostgresTableHandler` for the given table, providing typed query
 * factories for all CRUD operations enabled in the table's `crud` config.
 *
 * Used in generated files. Call the returned methods to get executable query
 * objects — each method returns a `PostgresQueryHandler` ready for `.getAll()`,
 * `.getOneRequired()`, or `.getOneOptional()`.
 *
 * @param table - The generated table constant to create a handler for.
 *
 * @example
 * const AccountHandler = newPostgresTableHandler(Account);
 *
 * const account = await AccountHandler.findById()
 *   .getOneRequired({ db: pool, params: { accountId: "123" } });
 *
 * const accounts = await AccountHandler.select({ WHERE: sql`${Account.$active} = true` })
 *   .getAll({ db: pool });
 */
export function newPostgresTableHandler<
   T extends {
      Select: Record<string, unknown>;
      Insert?: Record<string, unknown>;
      Update?: Record<string, unknown>;
      Delete?: boolean;
   },
>(table: SqlTable<T>): PostgresTableHandler<T> {
   const { select, insert, update, delete: delete$ } = table.crud;
   const handler: Record<string, unknown> = {};

   handler.findById = () => postgresFind<T, PkFields<T> & Partial<T["Select"]>>(table);
   handler.findBy = () => postgresFind<T, Partial<T["Select"]>>(table);

   if (select) {
      handler.select = <Args extends SqlSelectArgs>(args: Args) =>
         postgresSelect(table as SqlTable<T & { Select: Record<string, unknown> }>, args);
   }
   if (insert) {
      handler.upsert = (args: PostgresUpsertArgs) =>
         postgresUpsert(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         );
      handler.insertRows = () =>
         postgresInsertRows(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
         );
      handler.insertFrom = <
         Args extends SqlInsertFromArgs<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
      >(
         args: Args,
      ) =>
         postgresInsertFrom(
            table as SqlTable<T & { Select: Record<string, unknown>; Insert: Record<string, unknown> }>,
            args,
         );
   }
   if (update) {
      handler.update = <Args extends SqlUpdateArgs>(args: Args) =>
         postgresUpdate(
            table as SqlTable<T & { Select: Record<string, unknown>; Update: Record<string, unknown> }>,
            args,
         );
   }
   if (delete$) {
      handler.delete = <Args extends SqlDeleteArgs>(args: Args) =>
         postgresDelete(table as SqlTable<T & { Select: Record<string, unknown>; Delete: true }>, args);
   }

   return handler as PostgresTableHandler<T>;
}
